package bootstrapcheck

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

func TestRunExercisesDeterministicRecoveryWorkflow(t *testing.T) {
	t.Parallel()

	repositoryRoot := t.TempDir()
	if err := os.WriteFile(
		filepath.Join(repositoryRoot, "go.mod"),
		[]byte("module "+spiceModule+"\n"),
		0o600,
	); err != nil {
		t.Fatal(err)
	}
	var operations []string
	runner := func(
		_ context.Context,
		directory string,
		_ []string,
		name string,
		arguments ...string,
	) ([]byte, error) {
		operations = append(
			operations,
			name+" "+strings.Join(arguments, " "),
		)
		if name == "go" && slices.Contains(arguments, "list") {
			if slices.Contains(arguments, "./cmd/spice") {
				return []byte(
					spiceModule + "/internal/cli\n" +
						spiceModule + "/internal/spicegen/spice\n" +
						spiceModule + "/internal/spicegen/spice/sources/internal_/autoconfigure\n",
				), nil
			}
			return []byte("github.com/StevenBuglione/spice/internal/cli\n"), nil
		}
		if name == "go" {
			return nil, nil
		}
		executable := strings.TrimSuffix(
			strings.ToLower(filepath.Base(name)),
			".exe",
		)
		if executable == "spice-production" {
			if len(arguments) == 1 && arguments[0] == "version" {
				return []byte("spice 0.1.0-dev\n"), nil
			}
			if len(arguments) > 0 && arguments[0] == "generate" {
				return []byte("Spice generation is current for target Spice.\n"), nil
			}
		}
		if len(arguments) > 0 && arguments[0] == "generate" {
			if directory == repositoryRoot {
				return []byte("Spice generation is current for target Spice.\n"), nil
			}
			generated := filepath.Join(
				directory,
				"internal",
				"spicegen",
				"bootstrap",
				"spice_contracts_gen.go",
			)
			if slices.Contains(arguments, "--check") {
				content, err := os.ReadFile(generated)
				if err != nil {
					return nil, err
				}
				if strings.Contains(string(content), "@broken") {
					return []byte(
						"owned generated file was modified after its manifest was written",
					), errors.New("manual edit")
				}
				return nil, nil
			}
			if err := os.MkdirAll(filepath.Dir(generated), 0o750); err != nil {
				return nil, err
			}
			if err := os.WriteFile(
				generated,
				[]byte(
					"// Code generated by Spice. DO NOT EDIT.\npackage spicegen\n",
				),
				0o600,
			); err != nil {
				return nil, err
			}
			manifest := filepath.Join(
				directory,
				".spice",
				"bootstrap.manifest.json",
			)
			if err := os.MkdirAll(filepath.Dir(manifest), 0o750); err != nil {
				return nil, err
			}
			if err := os.WriteFile(manifest, []byte("{}\n"), 0o600); err != nil {
				return nil, err
			}
			return nil, nil
		}
		return []byte("Spice bootstrap ready.\n"), nil
	}

	if err := run(t.Context(), repositoryRoot, runner); err != nil {
		t.Fatalf("run() error = %v", err)
	}
	if len(operations) != 15 {
		t.Fatalf("operations = %#v, want 15", operations)
	}
	for _, expected := range []string{
		"go build -mod=vendor -trimpath -o",
		"./cmd/spice-bootstrap",
		"./cmd/spice",
		"generate --check --target Spice",
		"generate . ./component",
		"generate --check . ./component",
	} {
		if !containsOperation(operations, expected) {
			t.Fatalf("operations = %#v, missing %q", operations, expected)
		}
	}
}

func TestRunRejectsInvalidSetupAndCompilerDependency(t *testing.T) {
	t.Parallel()

	//nolint:staticcheck // The internal contract deliberately rejects nil.
	if err := run(nil, t.TempDir(), execute); err == nil ||
		!strings.Contains(err.Error(), "context is nil") {
		t.Fatalf("run(nil) error = %v", err)
	}
	if err := run(t.Context(), t.TempDir(), nil); err == nil ||
		!strings.Contains(err.Error(), "command runner is nil") {
		t.Fatalf("run(nil runner) error = %v", err)
	}
	if err := checkCompilerDependencies([]byte(
		spiceModule + "/internal/spicegen/commerce\n",
	)); err == nil || !strings.Contains(err.Error(), "generated application") {
		t.Fatalf("checkCompilerDependencies() error = %v", err)
	}
	if err := checkCompilerDependencies([]byte(
		spiceModule + "/compiler/generate\n",
	)); err != nil {
		t.Fatalf("checkCompilerDependencies(valid) error = %v", err)
	}
	if err := checkProductionDependencies([]byte(
		spiceModule + "/internal/spicegen/spice\n" +
			spiceModule + "/internal/spicegen/spice/sources/internal_/spiceapp\n",
	)); err != nil {
		t.Fatalf("checkProductionDependencies(valid) error = %v", err)
	}
	if err := checkProductionDependencies([]byte(
		spiceModule + "/internal/cli\n",
	)); err == nil || !strings.Contains(err.Error(), "does not depend") {
		t.Fatalf("checkProductionDependencies(missing) error = %v", err)
	}
	if err := checkProductionDependencies([]byte(
		spiceModule + "/internal/spicegen/spice\n" +
			spiceModule + "/internal/spicegen/commerce\n",
	)); err == nil || !strings.Contains(err.Error(), "unexpected generated target") {
		t.Fatalf("checkProductionDependencies(unexpected) error = %v", err)
	}
	if err := validateExecutable("go"); err != nil {
		t.Fatalf("validateExecutable(go) error = %v", err)
	}
	if err := validateExecutable("curl"); err == nil {
		t.Fatal("validateExecutable(relative) error = nil")
	}
	if err := validateExecutable(
		filepath.Join(t.TempDir(), "unexpected.exe"),
	); err == nil {
		t.Fatal("validateExecutable(unexpected) error = nil")
	}
	if err := validateExecutable(
		filepath.Join(t.TempDir(), "spice-bootstrap.exe"),
	); err != nil {
		t.Fatalf("validateExecutable(proof) error = %v", err)
	}
	if err := validateExecutable(
		filepath.Join(t.TempDir(), "spice-production.exe"),
	); err != nil {
		t.Fatalf("validateExecutable(production) error = %v", err)
	}
}

func TestSnapshotValidationAndComparisonFailures(t *testing.T) {
	t.Parallel()

	if err := validateOwnedOutput(nil); err == nil {
		t.Fatal("validateOwnedOutput(nil) error = nil")
	}
	valid := map[string][]byte{
		".spice/app.manifest.json": []byte("{}"),
		"internal/spicegen/app/spice_contracts_gen.go": []byte(
			"// Code generated by Spice. DO NOT EDIT.",
		),
	}
	if err := validateOwnedOutput(valid); err != nil {
		t.Fatalf("validateOwnedOutput() error = %v", err)
	}
	if err := compareSnapshots(valid, map[string][]byte{}); err == nil {
		t.Fatal("compareSnapshots(count) error = nil")
	}
	if err := compareSnapshots(valid, map[string][]byte{
		".spice/app.manifest.json": []byte("{}"),
		"other":                    []byte("value"),
	}); err == nil {
		t.Fatal("compareSnapshots(missing) error = nil")
	}
	changed := map[string][]byte{
		".spice/app.manifest.json":                     []byte("changed"),
		"internal/spicegen/app/spice_contracts_gen.go": valid["internal/spicegen/app/spice_contracts_gen.go"],
	}
	if err := compareSnapshots(valid, changed); err == nil {
		t.Fatal("compareSnapshots(content) error = nil")
	}
	if _, err := firstGeneratedGoFile(nil); err == nil {
		t.Fatal("firstGeneratedGoFile(nil) error = nil")
	}
}

func TestOfflineEnvironmentReplacesAmbientModuleSettings(t *testing.T) {
	t.Parallel()

	got := offlineEnvironment([]string{
		"PATH=tools",
		"GOPROXY=https://proxy.example",
		"gosumdb=sum.example",
	})
	for _, expected := range []string{
		"PATH=tools",
		"GOPROXY=off",
		"GOSUMDB=off",
		"GOWORK=off",
	} {
		if !slices.Contains(got, expected) {
			t.Fatalf("offlineEnvironment() = %#v, missing %q", got, expected)
		}
	}
	if len(got) != 4 {
		t.Fatalf("offlineEnvironment() = %#v", got)
	}
}

func containsOperation(operations []string, expected string) bool {
	for _, operation := range operations {
		if strings.Contains(operation, expected) {
			return true
		}
	}
	return false
}
