package load

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"
)

const blockingDriverMode = "SPICE_TEST_PACKAGES_DRIVER_BLOCK"

func TestMain(m *testing.M) {
	if os.Getenv(blockingDriverMode) == "1" {
		started := os.Getenv("SPICE_TEST_DRIVER_STARTED")
		pidFile := os.Getenv("SPICE_TEST_DRIVER_PID")
		if started == "" || pidFile == "" {
			os.Exit(2)
		}
		if err := os.WriteFile(pidFile, []byte(strconv.Itoa(os.Getpid())), 0o644); err != nil {
			os.Exit(2)
		}
		if err := os.WriteFile(started, []byte("started"), 0o644); err != nil {
			os.Exit(2)
		}
		for {
			time.Sleep(time.Hour)
		}
	}
	os.Exit(m.Run())
}

func TestLoadHonorsEnvironment(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/environment\n\ngo 1.23.0\n",
		"selected/default.go": `//go:build !spice_env

package selected

var Default int
`,
		"selected/environment.go": `//go:build spice_env

package selected

var FromEnvironment int
`,
	})

	program, err := Load(context.Background(), Options{
		Dir: dir,
		Env: replaceEnvironmentValue(os.Environ(), "GOFLAGS", "-tags=spice_env"),
	}, "./...")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	if symbolByID(program.Symbols(), "example.com/environment/selected.FromEnvironment") == nil {
		t.Fatalf("environment-selected declaration missing: %v", symbolIDs(program.Symbols()))
	}
	if symbolByID(program.Symbols(), "example.com/environment/selected.Default") != nil {
		t.Fatalf("default declaration present despite GOFLAGS environment: %v", symbolIDs(program.Symbols()))
	}
}

func TestLoadReturnsStableSymbolOrder(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/order\n\ngo 1.23.0\n",
		"order/order.go": `package order

var Zulu int
const Alpha = 1
type Middle struct{}
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./order")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	got := symbolIDs(program.Symbols())
	want := []string{
		stableSymbolID(SymbolPackage, "example.com/order/order", "", ""),
		stableSymbolID(SymbolType, "example.com/order/order", "", "Middle"),
		stableSymbolID(SymbolVariable, "example.com/order/order", "", "Zulu"),
		stableSymbolID(SymbolConstant, "example.com/order/order", "", "Alpha"),
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("symbol IDs = %v, want exact stable order %v", got, want)
	}
}

func TestLoadReturnsStableDiagnosticOrder(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/diagnostics\n\ngo 1.23.0\n",
		"zbroken/z.go": `package zbroken

var Value string = 1
`,
		"abroken/a.go": `package abroken

var Value string = 1
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./zbroken", "./abroken")
	if err == nil {
		t.Fatal("Load() error = nil, want type errors")
	}
	diagnostics := program.Diagnostics()
	got := make([]string, len(diagnostics))
	for i, diagnostic := range diagnostics {
		got[i] = diagnostic.PackagePath + "|" + diagnostic.Kind
	}
	want := []string{
		"example.com/diagnostics/abroken|list",
		"example.com/diagnostics/abroken|type",
		"example.com/diagnostics/zbroken|list",
		"example.com/diagnostics/zbroken|type",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("diagnostics = %v, want exact stable order %v", got, want)
	}
}

func TestLoadCgoUsesSourceDirectoryAndOmitsSyntheticSymbols(t *testing.T) {
	requireCgo(t)

	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/cgosource\n\ngo 1.23.0\n",
		"catalog/catalog.go": `package catalog

/*
static int answer(void) { return 42; }
*/
import "C"

type Service struct{}
var Value = int(C.answer())
func Build() *Service { return &Service{} }
`,
		"catalog/generated.go": `// Code generated by the Spice cgo fixture. DO NOT EDIT.
package catalog

const Generated = 7
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./catalog")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}

	packages := program.Packages()
	if len(packages) != 1 {
		t.Fatalf("packages = %#v, want one cgo package", packages)
	}
	pkg := packages[0]
	sourceDir := filepath.Join(dir, "catalog")
	if got, want := pkg.Dir, sourceDir; got != want {
		t.Fatalf("package directory = %q, want source directory %q", got, want)
	}
	if !sort.StringsAreSorted(pkg.CompiledGoFiles) {
		t.Fatalf("compiled Go files are not sorted: %v", pkg.CompiledGoFiles)
	}
	if len(pkg.Files) != len(pkg.CompiledGoFiles) || len(pkg.Syntax) != len(pkg.CompiledGoFiles) {
		t.Fatalf("file model lengths: files=%d compiled=%d syntax=%d", len(pkg.Files), len(pkg.CompiledGoFiles), len(pkg.Syntax))
	}
	for i, file := range pkg.Files {
		if file.PhysicalPath != pkg.CompiledGoFiles[i] || file.Syntax != pkg.Syntax[i] {
			t.Fatalf("file association %d = %#v, compiled=%q syntax=%p", i, file, pkg.CompiledGoFiles[i], pkg.Syntax[i])
		}
		if file.Syntax != nil {
			physical := filepath.Clean(pkg.Raw.Fset.PositionFor(file.Syntax.Pos(), false).Filename)
			if physical != file.PhysicalPath {
				t.Fatalf("file association %d physical syntax path = %q, want %q", i, physical, file.PhysicalPath)
			}
		}
	}
	hasCacheBackedInput := false
	for _, file := range pkg.CompiledGoFiles {
		if filepath.Dir(file) != sourceDir {
			hasCacheBackedInput = true
			break
		}
	}
	if !hasCacheBackedInput {
		t.Fatalf("compiled Go files = %v, want cgo cache-backed inputs proving integration path executed", pkg.CompiledGoFiles)
	}

	symbols := program.Symbols()
	assertUniqueSymbolIDs(t, symbols)
	if got, want := symbolIDs(symbols), []string{
		stableSymbolID(SymbolPackage, "example.com/cgosource/catalog", "", ""),
		stableSymbolID(SymbolType, "example.com/cgosource/catalog", "", "Service"),
		stableSymbolID(SymbolFunction, "example.com/cgosource/catalog", "", "Build"),
		stableSymbolID(SymbolVariable, "example.com/cgosource/catalog", "", "Value"),
		stableSymbolID(SymbolConstant, "example.com/cgosource/catalog", "", "Generated"),
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("symbol IDs = %v, want source declarations only %v", got, want)
	}

	catalogSource := filepath.Join(sourceDir, "catalog.go")
	generatedSource := filepath.Join(sourceDir, "generated.go")
	wantPosition := map[string]string{
		"example.com/cgosource/catalog":           catalogSource,
		"example.com/cgosource/catalog.Build":     catalogSource,
		"example.com/cgosource/catalog.Generated": generatedSource,
		"example.com/cgosource/catalog.Service":   catalogSource,
		"example.com/cgosource/catalog.Value":     catalogSource,
	}
	for _, symbol := range symbols {
		filename := filepath.Clean(symbol.Position.Filename)
		if filename != wantPosition[symbol.DisplayLabel] {
			t.Fatalf("symbol %q position = %q, want source file %q", symbol.ID, filename, wantPosition[symbol.DisplayLabel])
		}
		if strings.Contains(symbol.Name, "_C") || strings.HasPrefix(symbol.Name, "_cgo") || strings.HasPrefix(symbol.Name, "__cgo") {
			t.Fatalf("cgo synthetic declaration entered symbol catalog: %q", symbol.ID)
		}
	}
}

func TestLoadRetainsLineMappedSourceWithPhysicalAndDisplayPositions(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/linemapped\n\ngo 1.23.0\n",
		"app/app.go": `package app

//line generated/schema.proto:40
var Value int
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./app")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	value := symbolByID(program.Symbols(), "example.com/linemapped/app.Value")
	if value == nil {
		t.Fatalf("line-mapped declaration missing: %v", symbolIDs(program.Symbols()))
	}
	physical := filepath.Join(dir, "app", "app.go")
	if got := filepath.Clean(value.PhysicalPosition.Filename); got != physical {
		t.Fatalf("physical filename = %q, want %q", got, physical)
	}
	display := filepath.Join(dir, "app", "generated", "schema.proto")
	if got := filepath.Clean(value.Position.Filename); got != display || value.Position.Line != 40 {
		t.Fatalf("display position = %s, want %s:40", value.Position, display)
	}
}

func TestLoadReturnsDiagnosticsByNumericPosition(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/numericdiagnostics\n\ngo 1.23.0\n",
		"broken/broken.go": `package broken
var Early string = 1







var Late string = 2
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./broken")
	if err == nil {
		t.Fatal("Load() error = nil, want type errors")
	}
	var lines []int
	for _, diagnostic := range program.Diagnostics() {
		if diagnostic.Kind == "type" {
			lines = append(lines, diagnostic.Line)
		}
	}
	if got, want := lines, []int{2, 10}; !reflect.DeepEqual(got, want) {
		t.Fatalf("type diagnostic lines = %v, want numeric order %v; diagnostics=%#v", got, want, program.Diagnostics())
	}
}

func TestLoadCancelsActivePackageDriver(t *testing.T) {
	executable, err := os.Executable()
	if err != nil {
		t.Fatalf("os.Executable(): %v", err)
	}
	dir := writeModule(t, map[string]string{
		"go.mod":     "module example.com/cancelactive\n\ngo 1.23.0\n",
		"app/app.go": "package app\n",
	})
	signalDir := t.TempDir()
	started := filepath.Join(signalDir, "started")
	pidFile := filepath.Join(signalDir, "pid")
	environment := os.Environ()
	environment = replaceEnvironmentValue(environment, "GOPACKAGESDRIVER", executable)
	environment = replaceEnvironmentValue(environment, blockingDriverMode, "1")
	environment = replaceEnvironmentValue(environment, "SPICE_TEST_DRIVER_STARTED", started)
	environment = replaceEnvironmentValue(environment, "SPICE_TEST_DRIVER_PID", pidFile)

	ctx, cancel := context.WithCancel(context.Background())
	result := make(chan struct {
		program *Program
		err     error
	}, 1)
	go func() {
		program, loadErr := Load(ctx, Options{Dir: dir, Env: environment}, "./...")
		result <- struct {
			program *Program
			err     error
		}{program: program, err: loadErr}
	}()

	waitForPath(t, started, 5*time.Second)
	cancel()
	select {
	case loaded := <-result:
		if !errors.Is(loaded.err, context.Canceled) {
			t.Fatalf("Load() error = %v, want context.Canceled", loaded.err)
		}
		if loaded.program != nil {
			t.Fatalf("Load() program = %#v, want nil", loaded.program)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("Load() did not return after cancelling an active package driver")
	}

	if runtime.GOOS == "linux" {
		pidBytes, err := os.ReadFile(pidFile)
		if err != nil {
			t.Fatalf("ReadFile(pid): %v", err)
		}
		pid, err := strconv.Atoi(strings.TrimSpace(string(pidBytes)))
		if err != nil {
			t.Fatalf("driver pid = %q: %v", pidBytes, err)
		}
		deadline := time.Now().Add(2 * time.Second)
		for {
			_, statErr := os.Stat(filepath.Join("/proc", strconv.Itoa(pid)))
			if os.IsNotExist(statErr) {
				break
			}
			if time.Now().After(deadline) {
				t.Fatalf("package driver process %d still exists after Load returned", pid)
			}
			time.Sleep(10 * time.Millisecond)
		}
	}
}

func waitForPath(t *testing.T, path string, timeout time.Duration) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for {
		if _, err := os.Stat(path); err == nil {
			return
		} else if !os.IsNotExist(err) {
			t.Fatalf("Stat(%q): %v", path, err)
		}
		if time.Now().After(deadline) {
			t.Fatalf("timed out waiting for %q", path)
		}
		time.Sleep(10 * time.Millisecond)
	}
}

func requireCgo(t *testing.T) {
	t.Helper()
	output, err := exec.Command("go", "env", "CGO_ENABLED").Output()
	if err != nil {
		t.Fatalf("go env CGO_ENABLED: %v", err)
	}
	if strings.TrimSpace(string(output)) != "1" {
		t.Skip("cgo is disabled for this Go toolchain")
	}
	compilerOutput, err := exec.Command("go", "env", "CC").Output()
	if err != nil {
		t.Fatalf("go env CC: %v", err)
	}
	compilerFields := strings.Fields(string(compilerOutput))
	if len(compilerFields) == 0 {
		t.Skip("cgo C compiler is not configured")
	}
	if _, err := exec.LookPath(compilerFields[0]); err != nil {
		t.Skipf("cgo C compiler %q is unavailable", compilerFields[0])
	}
}

func TestLoadOmitsNonAddressableDeclarationsAndReturnsUniqueSymbolIDs(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/identity\n\ngo 1.23.0\n",
		"catalog/first.go": `package catalog

func init() {}

type _ int
func _() {}
var _ = 1
const _ = 2

type Service struct{}
func (Service) _() {}
func (Service) Start() {}

var First int
const FirstConstant = 3
`,
		"catalog/second.go": `package catalog

func init() {}

type _ string
func _() {}
var _ = 4
const _ = 5

func (Service) _() {}

func Build() *Service { return &Service{} }
const Second = 6
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./...")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}

	symbols := program.Symbols()
	assertUniqueSymbolIDs(t, symbols)
	if got, want := symbolIDs(symbols), []string{
		stableSymbolID(SymbolPackage, "example.com/identity/catalog", "", ""),
		stableSymbolID(SymbolType, "example.com/identity/catalog", "", "Service"),
		stableSymbolID(SymbolFunction, "example.com/identity/catalog", "", "Build"),
		stableSymbolID(SymbolMethod, "example.com/identity/catalog", "Service", "Start"),
		stableSymbolID(SymbolVariable, "example.com/identity/catalog", "", "First"),
		stableSymbolID(SymbolConstant, "example.com/identity/catalog", "", "FirstConstant"),
		stableSymbolID(SymbolConstant, "example.com/identity/catalog", "", "Second"),
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("symbol IDs = %v, want every non-addressable declaration omitted as %v", got, want)
	}
	for _, symbol := range symbols {
		if symbol.Name == "_" || symbol.Name == "init" {
			t.Fatalf("non-addressable %s declaration %q entered symbol catalog: %v", symbol.Kind, symbol.ID, symbolIDs(symbols))
		}
	}
}

func TestStableSymbolIDEncoding(t *testing.T) {
	tests := []struct {
		name        string
		kind        SymbolKind
		packagePath string
		receiver    string
		declaration string
		want        string
	}{
		{
			name:        "package",
			kind:        SymbolPackage,
			packagePath: "example.com/foo.bar",
			want:        "spice:symbol:v1|package|19:example.com/foo.bar|0:|0:",
		},
		{
			name:        "type",
			kind:        SymbolType,
			packagePath: "example.com/foo.bar",
			declaration: "T",
			want:        "spice:symbol:v1|type|19:example.com/foo.bar|0:|1:T",
		},
		{
			name:        "function",
			kind:        SymbolFunction,
			packagePath: "example.com/foo.bar",
			declaration: "Build",
			want:        "spice:symbol:v1|function|19:example.com/foo.bar|0:|5:Build",
		},
		{
			name:        "method",
			kind:        SymbolMethod,
			packagePath: "example.com/foo.bar",
			receiver:    "T",
			declaration: "M",
			want:        "spice:symbol:v1|method|19:example.com/foo.bar|1:T|1:M",
		},
		{
			name:        "variable",
			kind:        SymbolVariable,
			packagePath: "example.com/foo.bar",
			declaration: "Value",
			want:        "spice:symbol:v1|variable|19:example.com/foo.bar|0:|5:Value",
		},
		{
			name:        "constant",
			kind:        SymbolConstant,
			packagePath: "example.com/foo.bar",
			declaration: "Answer",
			want:        "spice:symbol:v1|constant|19:example.com/foo.bar|0:|6:Answer",
		},
		{
			name:        "UTF-8 byte lengths and delimiter-like text",
			kind:        SymbolMethod,
			packagePath: "example.com/a|b:c/9",
			receiver:    "Δ",
			declaration: "方法",
			want:        "spice:symbol:v1|method|19:example.com/a|b:c/9|2:Δ|6:方法",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if got := stableSymbolID(test.kind, test.packagePath, test.receiver, test.declaration); got != test.want {
				t.Fatalf("stableSymbolID() = %q, want %q", got, test.want)
			}
		})
	}
}

func TestLoadCollisionFreeStableSymbolIDs(t *testing.T) {
	const modulePath = "example.com/collisionmatrix"
	dir := writeModule(t, map[string]string{
		"go.mod": "module " + modulePath + "\n\ngo 1.23.0\n",
		"p/p.go": `package p

const C = 1
var V = 2
type T struct{}
func F() {}
func (T) M() {}
`,
		"p.C/c.go":   "package c\n",
		"p.F/f.go":   "package f\n",
		"p.T/t.go":   "package t\n",
		"p.V/v.go":   "package v\n",
		"p.T.M/m.go": "package m\n",
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./...")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}

	base := modulePath + "/p"
	wantPackagePaths := []string{base, base + ".C", base + ".F", base + ".T", base + ".T.M", base + ".V"}
	if got := packagePaths(program.Packages()); !reflect.DeepEqual(got, wantPackagePaths) {
		t.Fatalf("package paths = %v, want %v", got, wantPackagePaths)
	}

	symbols := program.Symbols()
	assertUniqueSymbolIDs(t, symbols)
	wantIDs := map[string]struct{}{
		stableSymbolID(SymbolPackage, base, "", ""):        {},
		stableSymbolID(SymbolConstant, base, "", "C"):      {},
		stableSymbolID(SymbolFunction, base, "", "F"):      {},
		stableSymbolID(SymbolType, base, "", "T"):          {},
		stableSymbolID(SymbolVariable, base, "", "V"):      {},
		stableSymbolID(SymbolMethod, base, "T", "M"):       {},
		stableSymbolID(SymbolPackage, base+".C", "", ""):   {},
		stableSymbolID(SymbolPackage, base+".F", "", ""):   {},
		stableSymbolID(SymbolPackage, base+".T", "", ""):   {},
		stableSymbolID(SymbolPackage, base+".T.M", "", ""): {},
		stableSymbolID(SymbolPackage, base+".V", "", ""):   {},
	}
	if len(symbols) != len(wantIDs) {
		t.Fatalf("symbol count = %d, want %d: %v", len(symbols), len(wantIDs), symbolIDs(symbols))
	}
	for _, symbol := range symbols {
		if _, ok := wantIDs[symbol.ID]; !ok {
			t.Errorf("unexpected symbol: kind=%s path=%q receiver=%q name=%q id=%q", symbol.Kind, symbol.PackagePath, symbol.Receiver, symbol.Name, symbol.ID)
		}
	}

	packageSymbolsByPath := make(map[string]Symbol)
	for _, symbol := range symbols {
		if symbol.Kind == SymbolPackage {
			packageSymbolsByPath[symbol.PackagePath] = symbol
		}
	}
	for _, pkg := range program.Packages() {
		symbol, ok := packageSymbolsByPath[pkg.Path]
		if !ok {
			t.Fatalf("package %q has no package symbol", pkg.Path)
		}
		if pkg.ID != symbol.ID {
			t.Fatalf("package %q ID = %q, package symbol ID = %q", pkg.Path, pkg.ID, symbol.ID)
		}
		if symbol.DisplayLabel != pkg.Path {
			t.Fatalf("package %q display label = %q", pkg.Path, symbol.DisplayLabel)
		}
	}

	for _, collision := range []struct {
		declarationKind SymbolKind
		declarationName string
		packagePath     string
	}{
		{SymbolConstant, "C", base + ".C"},
		{SymbolFunction, "F", base + ".F"},
		{SymbolType, "T", base + ".T"},
		{SymbolVariable, "V", base + ".V"},
	} {
		declarationID := stableSymbolID(collision.declarationKind, base, "", collision.declarationName)
		packageID := stableSymbolID(SymbolPackage, collision.packagePath, "", "")
		if declarationID == packageID {
			t.Fatalf("canonical IDs collide for declaration %q and package %q: %q", collision.declarationName, collision.packagePath, declarationID)
		}
		declaration := symbolByID(symbols, declarationID)
		pkg := symbolByID(symbols, packageID)
		if declaration == nil || pkg == nil {
			t.Fatalf("missing collision-matrix records declaration=%q package=%q", declarationID, packageID)
		}
		if declaration.DisplayLabel != pkg.DisplayLabel {
			t.Fatalf("display labels = %q and %q, want the readable legacy collision to remain display-only", declaration.DisplayLabel, pkg.DisplayLabel)
		}
	}

	methodID := stableSymbolID(SymbolMethod, base, "T", "M")
	methodPackageID := stableSymbolID(SymbolPackage, base+".T.M", "", "")
	method := symbolByID(symbols, methodID)
	methodPackage := symbolByID(symbols, methodPackageID)
	if method == nil || methodPackage == nil {
		t.Fatalf("missing method collision records method=%q package=%q", methodID, methodPackageID)
	}
	if method.ID == methodPackage.ID || method.DisplayLabel != methodPackage.DisplayLabel {
		t.Fatalf("method/package identity separation failed: method=%#v package=%#v", method, methodPackage)
	}
}

func replaceEnvironmentValue(environment []string, name, value string) []string {
	prefix := name + "="
	result := make([]string, 0, len(environment)+1)
	for _, entry := range environment {
		if strings.HasPrefix(entry, prefix) {
			continue
		}
		result = append(result, entry)
	}
	return append(result, prefix+value)
}
