//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: examples/commerce/orders/events.go:29

package spicegen

import (
	orders "github.com/StevenBuglione/spice/examples/commerce/orders"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Constructab6c60ed179d performs the direct construction selected for spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|12:NewViewAudit.
func Constructab6c60ed179d() (*orders.ViewAudit, spicelifecycle.Cleanup, error) {
	value := orders.NewViewAudit()
	return value, nil, nil
}
