//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: examples/commerce/main.go:19

package spicegen

// ApplicationTargetCommerce_9d5bf597 identifies the generated target selected by spice:symbol:v1|function|49:github.com/StevenBuglione/spice/examples/commerce|0:|4:main.
const ApplicationTargetCommerce_9d5bf597 = "commerce"
