// Code generated by Spice. DO NOT EDIT.
//go:build !spice_generate

package spicegen

import (
	context "context"
	flag "flag"
	fmt "fmt"
	io "io"
	slog "log/slog"
	http "net/http"
	os "os"
	signal "os/signal"
	syscall "syscall"
	time "time"

	spiceconfig "github.com/StevenBuglione/spice/config"
	memory "github.com/StevenBuglione/spice/examples/petclinic/memory"
	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	system "github.com/StevenBuglione/spice/examples/petclinic/system"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
	spicemanagement "github.com/StevenBuglione/spice/management"
	spiceobservability "github.com/StevenBuglione/spice/observability"
	spiceview "github.com/StevenBuglione/spice/view"
	spiceweb "github.com/StevenBuglione/spice/web"
)

const TargetID = "petclinic"

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// PetclinicDatabase is bean "newPetclinicDatabase".
	PetclinicDatabase *memory.Database
	// Renderer is bean "newRenderer".
	Renderer *spiceview.Renderer
	// Mux is bean "newMux".
	Mux *http.ServeMux
	// VetRepository is bean "vetRepository".
	VetRepository *memory.VetRepository
	// OwnerRepository is bean "ownerRepository".
	OwnerRepository *memory.OwnerRepository
	// PetTypeRepository is bean "petTypeRepository".
	PetTypeRepository *memory.PetTypeRepository
	// WelcomeController is bean "welcomeController".
	WelcomeController *system.WelcomeController
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
	mux             *http.ServeMux
	handler         http.Handler
}

type ApplicationOptions struct {
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	ErrorMapper               spiceweb.ErrorMapper
	MaxRequestBodyBytes       int64
	HTTPObservers             []spiceweb.HTTPObserver
	Middleware                []spiceweb.Middleware
	Logger                    *slog.Logger
	Observers                 []spicelifecycle.Observer
}

func ConfigurationSchema() (spiceconfig.Schema, error) {
	return spiceconfig.NewSchema(
		spiceconfig.Property{
			Key:         "spice.shutdown-timeout",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_SHUTDOWN_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
	)
}

func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {
	return NewApplicationWithOptions(ctx, ApplicationOptions{Observers: observers})
}

func NewApplicationWithOptions(ctx context.Context, options ApplicationOptions) (*Application, error) {
	if ctx == nil {
		return nil, fmt.Errorf("construct application petclinic: context is nil")
	}
	application := &Application{coordinator: spicelifecycle.NewCoordinator()}
	observers := append([]spicelifecycle.Observer(nil), options.Observers...)
	httpObservers := append([]spiceweb.HTTPObserver(nil), options.HTTPObservers...)
	_ = httpObservers
	managementMetrics := spicemanagement.NewHTTPMetrics()
	httpObservers = append([]spiceweb.HTTPObserver{managementMetrics}, httpObservers...)
	logger := options.Logger
	if logger == nil {
		logger = slog.New(slog.NewJSONHandler(os.Stderr, nil))
	}
	lifecycleLogs, err := spiceobservability.NewSlogLifecycleObserver(logger)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure lifecycle logging: %w", err))
	}
	observers = append([]spicelifecycle.Observer{lifecycleLogs}, observers...)
	httpLogs, err := spiceobservability.NewSlogHTTPObserver(logger)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure HTTP logging: %w", err))
	}
	httpObservers = append(httpObservers[:1], append([]spiceweb.HTTPObserver{httpLogs}, httpObservers[1:]...)...)
	for index, observer := range observers {
		if err := application.coordinator.RegisterObserver(observer); err != nil {
			return nil, fmt.Errorf("register lifecycle observer %d: %w", index, err)
		}
	}
	configurationSchema, err := ConfigurationSchema()
	if err != nil {
		return nil, fmt.Errorf("construct configuration schema for application petclinic: %w", err)
	}
	configurationSnapshot, err := spiceconfig.Resolve(
		ctx,
		configurationSchema,
		spiceconfig.Options{
			Profiles:     options.Profiles,
			AllowUnknown: options.AllowUnknownConfiguration,
		},
		options.Sources...,
	)
	if err != nil {
		return nil, fmt.Errorf("resolve configuration for application petclinic: %w", err)
	}
	application.shutdownTimeout, err = configurationSnapshot.Duration("spice.shutdown-timeout")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application petclinic: %w", err))
	}
	if application.shutdownTimeout <= 0 {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application petclinic: duration must be positive"))
	}
	provider0, err := memory.NewPetclinicDatabase()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|20:NewPetclinicDatabase (*github.com/StevenBuglione/spice/examples/petclinic/memory.Database): %w", err))
	}
	_ = provider0
	provider1, err := presentation.NewRenderer()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|11:NewRenderer (*github.com/StevenBuglione/spice/view.Renderer): %w", err))
	}
	_ = provider1
	provider2 := presentation.NewMux()
	_ = provider2
	provider3, err := memory.NewVetRepository(provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|13:VetRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.VetRepository): %w", err))
	}
	_ = provider3
	provider4, err := memory.NewOwnerRepository(provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|15:OwnerRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.OwnerRepository): %w", err))
	}
	_ = provider4
	provider5, err := memory.NewPetTypeRepository(provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|17:PetTypeRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.PetTypeRepository): %w", err))
	}
	_ = provider5
	provider6 := system.NewWelcomeController()
	_ = provider6
	application.components = Components{
		PetclinicDatabase: provider0,
		Renderer:          provider1,
		Mux:               provider2,
		VetRepository:     provider3,
		OwnerRepository:   provider4,
		PetTypeRepository: provider5,
		WelcomeController: provider6,
	}
	routeMux := provider2
	application.mux = routeMux
	application.handler = routeMux
	routeObservation0, routeObservationErr0 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|57:github.com/StevenBuglione/spice/examples/petclinic/system|17:WelcomeController|4:Show", Module: "", Method: "GET", Pattern: "/"}, httpObservers...)
	if routeObservationErr0 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET / observation: %w", routeObservationErr0))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			if writeErr := spiceweb.WriteProblem(writer, problem); writeErr != nil {
				return
			}
			return
		}
		requestValue := system.WelcomeRequest{}
		responseValue, routeErr := provider6.Show(httpRequest.Context(), requestValue)
		if routeErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, routeErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if writeErr := provider1.Respond(httpRequest.Context(), writer, responseValue); writeErr != nil {
			return
		}
	}), routeObservation0, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /: %w", routeErr))
	}
	managementChecks, err := spicemanagement.LifecycleChecks(TargetID, "github.com/StevenBuglione/spice/examples/petclinic", application.State)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management lifecycle checks: %w", err))
	}
	managementManager, err := spicemanagement.New(managementChecks...)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management checks: %w", err))
	}
	managementConfiguration, err := spicemanagement.NewConfigurationReport(configurationSchema, configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management configuration report: %w", err))
	}
	managementModules, err := spicemanagement.NewModuleReport(
		[]spicemanagement.ModuleDefinition{},
		[]spicemanagement.ModuleEdge{},
		[]string{},
	)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management module report: %w", err))
	}
	managementHandler, err := spicemanagement.NewHandler(spicemanagement.HandlerOptions{
		Manager: managementManager,
		Info: map[string]string{
			"application": TargetID,
			"module":      "github.com/StevenBuglione/spice/examples/petclinic",
			"framework":   "Spice",
		},
		Metrics:       managementMetrics,
		Configuration: &managementConfiguration,
		Modules:       &managementModules,
		Expose: []spicemanagement.Endpoint{
			spicemanagement.EndpointConfigProps,
			spicemanagement.EndpointHealth,
			spicemanagement.EndpointInfo,
			spicemanagement.EndpointLiveness,
			spicemanagement.EndpointMetrics,
			spicemanagement.EndpointModules,
			spicemanagement.EndpointReadiness,
		},
	})
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management handler: %w", err))
	}
	if err := spiceweb.Register(routeMux, managementHandler.Pattern(), managementHandler); err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register management routes: %w", err))
	}
	return application, nil
}

func (application *Application) State() spicelifecycle.State {
	if application == nil || application.coordinator == nil {
		return spicelifecycle.StateInvalid
	}
	return application.coordinator.State()
}

func (application *Application) Start(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("start application: application is nil")
	}
	return application.coordinator.Start(ctx, application.hooks)
}

func (application *Application) Stop(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("stop application: application is nil")
	}
	return application.coordinator.Stop(ctx)
}

func (application *Application) ShutdownTimeout() time.Duration {
	if application == nil {
		return 0
	}
	return application.shutdownTimeout
}

func (application *Application) RegisterObserver(observer spicelifecycle.Observer) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("register lifecycle observer: application is nil")
	}
	return application.coordinator.RegisterObserver(observer)
}

func (application *Application) Run(ctx context.Context, shutdown spicelifecycle.ContextFactory) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("run application: application is nil")
	}
	return application.coordinator.Run(ctx, application.hooks, shutdown)
}

// Components returns a typed snapshot of constructed singleton beans.
func (application *Application) Components() Components {
	if application == nil {
		return Components{}
	}
	return application.components
}

func (application *Application) Handler() http.Handler {
	if application == nil {
		return nil
	}
	return application.handler
}

type ShutdownContextFactory func(time.Duration) (context.Context, context.CancelFunc)

type CommandOptions struct {
	Context         context.Context
	Arguments       []string
	Stdout          io.Writer
	Stderr          io.Writer
	Logger          *slog.Logger
	ShutdownTimeout time.Duration
	ShutdownContext ShutdownContextFactory
	Application     ApplicationOptions
}

func Main(arguments []string) int {
	logger := slog.New(slog.NewJSONHandler(os.Stderr, nil))
	environment, err := spiceconfig.OSEnvironment("SPICE_")
	if err != nil {
		logger.Error("Spice command configuration failed", slog.Any("error", err))
		return ExitFailure
	}
	runContext, stopSignals := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stopSignals()
	return RunCommand(CommandOptions{
		Context:   runContext,
		Arguments: arguments,
		Stdout:    os.Stdout,
		Stderr:    os.Stderr,
		Logger:    logger,
		Application: ApplicationOptions{
			Sources: []spiceconfig.Source{environment},
		},
	})
}

func RunCommand(options CommandOptions) int {
	stdout := options.Stdout
	if stdout == nil {
		stdout = io.Discard
	}
	stderr := options.Stderr
	if stderr == nil {
		stderr = io.Discard
	}
	logger := options.Logger
	if logger == nil {
		logger = slog.New(slog.NewJSONHandler(stderr, nil))
	}
	ctx := options.Context
	if ctx == nil {
		return commandFailure(context.Background(), logger, "Spice command context is nil", nil)
	}
	if options.ShutdownTimeout < 0 {
		return commandFailure(ctx, logger, "Spice shutdown timeout is invalid", nil)
	}

	flags := flag.NewFlagSet(TargetID, flag.ContinueOnError)
	flags.SetOutput(stderr)
	check := flags.Bool("check", false, "construct the generated application and exit")
	if err := flags.Parse(options.Arguments); err != nil {
		logger.ErrorContext(ctx, "Spice command arguments are invalid", slog.Any("error", err))
		return ExitUsage
	}
	if flags.NArg() != 0 {
		if _, err := fmt.Fprintf(stderr, "%s does not accept positional arguments\n", TargetID); err != nil {
			logger.ErrorContext(ctx, "Spice command usage output failed", slog.Any("error", err))
		}
		return ExitUsage
	}

	applicationOptions := options.Application
	applicationOptions.Logger = logger
	logger.InfoContext(ctx, "Spice application constructing", slog.String("application", TargetID))
	application, err := NewApplicationWithOptions(ctx, applicationOptions)
	if err != nil {
		return commandFailure(ctx, logger, "Spice application construction failed", err)
	}

	shutdownTimeout := application.shutdownTimeout
	if options.ShutdownTimeout > 0 {
		shutdownTimeout = options.ShutdownTimeout
	}
	shutdownContext := options.ShutdownContext
	if shutdownContext == nil {
		shutdownContext = func(timeout time.Duration) (context.Context, context.CancelFunc) {
			return context.WithTimeout(context.Background(), timeout)
		}
	}
	shutdown := func() (context.Context, context.CancelFunc) {
		return shutdownContext(shutdownTimeout)
	}

	if *check {
		if err := stopCheckedApplication(application, shutdown); err != nil {
			return commandFailure(ctx, logger, "Spice application check cleanup failed", err)
		}
		if _, err := fmt.Fprintf(stdout, "Spice %s ready.\n", TargetID); err != nil {
			return commandFailure(ctx, logger, "Spice readiness output failed", err)
		}
		return ExitSuccess
	}

	logger.InfoContext(ctx, "Spice application starting", slog.String("application", TargetID))
	if err := application.Run(ctx, shutdown); err != nil {
		return commandFailure(ctx, logger, "Spice application run failed", err)
	}
	logger.InfoContext(context.Background(), "Spice application stopped", slog.String("application", TargetID))
	return ExitSuccess
}

func stopCheckedApplication(
	application *Application,
	shutdown spicelifecycle.ContextFactory,
) error {
	shutdownContext, cancel := shutdown()
	if shutdownContext == nil || cancel == nil {
		return fmt.Errorf("check application: shutdown context factory returned a nil context or cancel function")
	}
	defer cancel()
	return application.Stop(shutdownContext)
}

func commandFailure(
	ctx context.Context,
	logger *slog.Logger,
	message string,
	err error,
) int {
	if err == nil {
		logger.ErrorContext(ctx, message)
	} else {
		logger.ErrorContext(ctx, message, slog.Any("error", err))
	}
	return ExitFailure
}
