// Code generated by Spice. DO NOT EDIT.
//go:build !spice_generate

package spicegen

import (
	context "context"
	flag "flag"
	fmt "fmt"
	io "io"
	slog "log/slog"
	http "net/http"
	os "os"
	signal "os/signal"
	syscall "syscall"
	time "time"

	spiceconfig "github.com/StevenBuglione/spice/config"
	memory "github.com/StevenBuglione/spice/examples/petclinic/memory"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	system "github.com/StevenBuglione/spice/examples/petclinic/system"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
	spicemanagement "github.com/StevenBuglione/spice/management"
	spiceobservability "github.com/StevenBuglione/spice/observability"
	spiceview "github.com/StevenBuglione/spice/view"
	spiceweb "github.com/StevenBuglione/spice/web"
)

const TargetID = "petclinic"

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// PetclinicDatabase is bean "newPetclinicDatabase".
	PetclinicDatabase *memory.Database
	// Renderer is bean "newRenderer".
	Renderer *spiceview.Renderer
	// Mux is bean "newMux".
	Mux *http.ServeMux
	// VetRepository is bean "vetRepository".
	VetRepository *memory.VetRepository
	// OwnerRepository is bean "ownerRepository".
	OwnerRepository *memory.OwnerRepository
	// Controller is bean "controller".
	Controller *owner.Controller
	// PetTypeRepository is bean "petTypeRepository".
	PetTypeRepository *memory.PetTypeRepository
	// WelcomeController is bean "welcomeController".
	WelcomeController *system.WelcomeController
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
	mux             *http.ServeMux
	handler         http.Handler
}

type ApplicationOptions struct {
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	ErrorMapper               spiceweb.ErrorMapper
	MaxRequestBodyBytes       int64
	HTTPObservers             []spiceweb.HTTPObserver
	Middleware                []spiceweb.Middleware
	Logger                    *slog.Logger
	Observers                 []spicelifecycle.Observer
}

func ConfigurationSchema() (spiceconfig.Schema, error) {
	return spiceconfig.NewSchema(
		spiceconfig.Property{
			Key:         "spice.shutdown-timeout",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_SHUTDOWN_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
	)
}

func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {
	return NewApplicationWithOptions(ctx, ApplicationOptions{Observers: observers})
}

func NewApplicationWithOptions(ctx context.Context, options ApplicationOptions) (*Application, error) {
	if ctx == nil {
		return nil, fmt.Errorf("construct application petclinic: context is nil")
	}
	application := &Application{coordinator: spicelifecycle.NewCoordinator()}
	observers := append([]spicelifecycle.Observer(nil), options.Observers...)
	httpObservers := append([]spiceweb.HTTPObserver(nil), options.HTTPObservers...)
	_ = httpObservers
	managementMetrics := spicemanagement.NewHTTPMetrics()
	httpObservers = append([]spiceweb.HTTPObserver{managementMetrics}, httpObservers...)
	logger := options.Logger
	if logger == nil {
		logger = slog.New(slog.NewJSONHandler(os.Stderr, nil))
	}
	lifecycleLogs, err := spiceobservability.NewSlogLifecycleObserver(logger)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure lifecycle logging: %w", err))
	}
	observers = append([]spicelifecycle.Observer{lifecycleLogs}, observers...)
	httpLogs, err := spiceobservability.NewSlogHTTPObserver(logger)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure HTTP logging: %w", err))
	}
	httpObservers = append(httpObservers[:1], append([]spiceweb.HTTPObserver{httpLogs}, httpObservers[1:]...)...)
	for index, observer := range observers {
		if err := application.coordinator.RegisterObserver(observer); err != nil {
			return nil, fmt.Errorf("register lifecycle observer %d: %w", index, err)
		}
	}
	configurationSchema, err := ConfigurationSchema()
	if err != nil {
		return nil, fmt.Errorf("construct configuration schema for application petclinic: %w", err)
	}
	configurationSnapshot, err := spiceconfig.Resolve(
		ctx,
		configurationSchema,
		spiceconfig.Options{
			Profiles:     options.Profiles,
			AllowUnknown: options.AllowUnknownConfiguration,
		},
		options.Sources...,
	)
	if err != nil {
		return nil, fmt.Errorf("resolve configuration for application petclinic: %w", err)
	}
	application.shutdownTimeout, err = configurationSnapshot.Duration("spice.shutdown-timeout")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application petclinic: %w", err))
	}
	if application.shutdownTimeout <= 0 {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application petclinic: duration must be positive"))
	}
	provider0, err := memory.NewPetclinicDatabase()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|20:NewPetclinicDatabase (*github.com/StevenBuglione/spice/examples/petclinic/memory.Database): %w", err))
	}
	_ = provider0
	provider1, err := presentation.NewRenderer()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|11:NewRenderer (*github.com/StevenBuglione/spice/view.Renderer): %w", err))
	}
	_ = provider1
	provider2 := presentation.NewMux()
	_ = provider2
	provider3, err := memory.NewVetRepository(provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|13:VetRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.VetRepository): %w", err))
	}
	_ = provider3
	provider4, err := memory.NewOwnerRepository(provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|15:OwnerRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.OwnerRepository): %w", err))
	}
	_ = provider4
	provider5, err := owner.NewController(provider4)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|10:Controller (*github.com/StevenBuglione/spice/examples/petclinic/owner.Controller): %w", err))
	}
	_ = provider5
	provider6, err := memory.NewPetTypeRepository(provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|17:PetTypeRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.PetTypeRepository): %w", err))
	}
	_ = provider6
	provider7 := system.NewWelcomeController()
	_ = provider7
	application.components = Components{
		PetclinicDatabase: provider0,
		Renderer:          provider1,
		Mux:               provider2,
		VetRepository:     provider3,
		OwnerRepository:   provider4,
		Controller:        provider5,
		PetTypeRepository: provider6,
		WelcomeController: provider7,
	}
	routeMux := provider2
	application.mux = routeMux
	application.handler = routeMux
	routeObservation0, routeObservationErr0 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|4:Find", Module: "", Method: "GET", Pattern: "/owners"}, httpObservers...)
	if routeObservationErr0 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners observation: %w", routeObservationErr0))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			if writeErr := spiceweb.WriteProblem(writer, problem); writeErr != nil {
				return
			}
			return
		}
		requestValue := owner.FindOwnersRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationQuery, "lastName", httpRequest.URL.Query()["lastName"], false)
		if bindErr0 != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, bindErr0, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if present0 {
			requestValue.LastName = string(raw0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationQuery, "page", httpRequest.URL.Query()["page"], false)
		if bindErr1 != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, bindErr1, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if present1 {
			parsed1, parseErr1 := spiceweb.Integer(spiceweb.LocationQuery, "page", raw1, 0)
			if parseErr1 != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, parseErr1, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			requestValue.Page = int(parsed1)
		}
		responseValue, routeErr := provider5.Find(httpRequest.Context(), requestValue)
		if routeErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, routeErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if writeErr := provider1.Respond(httpRequest.Context(), writer, responseValue); writeErr != nil {
			return
		}
	}), routeObservation0, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners: %w", routeErr))
	}
	routeObservation1, routeObservationErr1 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|8:FindForm", Module: "", Method: "GET", Pattern: "/owners/find"}, httpObservers...)
	if routeObservationErr1 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/find observation: %w", routeObservationErr1))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/find", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			if writeErr := spiceweb.WriteProblem(writer, problem); writeErr != nil {
				return
			}
			return
		}
		requestValue := owner.FindOwnerFormRequest{}
		responseValue, routeErr := provider5.FindForm(httpRequest.Context(), requestValue)
		if routeErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, routeErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if writeErr := provider1.Respond(httpRequest.Context(), writer, responseValue); writeErr != nil {
			return
		}
	}), routeObservation1, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/find: %w", routeErr))
	}
	routeObservation2, routeObservationErr2 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|7:NewForm", Module: "", Method: "GET", Pattern: "/owners/new"}, httpObservers...)
	if routeObservationErr2 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/new observation: %w", routeObservationErr2))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/new", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			if writeErr := spiceweb.WriteProblem(writer, problem); writeErr != nil {
				return
			}
			return
		}
		requestValue := owner.NewOwnerRequest{}
		responseValue, routeErr := provider5.NewForm(httpRequest.Context(), requestValue)
		if routeErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, routeErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if writeErr := provider1.Respond(httpRequest.Context(), writer, responseValue); writeErr != nil {
			return
		}
	}), routeObservation2, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/new: %w", routeErr))
	}
	routeObservation3, routeObservationErr3 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|4:Show", Module: "", Method: "GET", Pattern: "/owners/{ownerId}"}, httpObservers...)
	if routeObservationErr3 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/{ownerId} observation: %w", routeObservationErr3))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/{ownerId}", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			if writeErr := spiceweb.WriteProblem(writer, problem); writeErr != nil {
				return
			}
			return
		}
		requestValue := owner.OwnerIDRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, bindErr0, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, parseErr0, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		responseValue, routeErr := provider5.Show(httpRequest.Context(), requestValue)
		if routeErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, routeErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if writeErr := provider1.Respond(httpRequest.Context(), writer, responseValue); writeErr != nil {
			return
		}
	}), routeObservation3, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/{ownerId}: %w", routeErr))
	}
	routeObservation4, routeObservationErr4 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|8:EditForm", Module: "", Method: "GET", Pattern: "/owners/{ownerId}/edit"}, httpObservers...)
	if routeObservationErr4 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/{ownerId}/edit observation: %w", routeObservationErr4))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/{ownerId}/edit", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			if writeErr := spiceweb.WriteProblem(writer, problem); writeErr != nil {
				return
			}
			return
		}
		requestValue := owner.OwnerIDRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, bindErr0, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, parseErr0, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		responseValue, routeErr := provider5.EditForm(httpRequest.Context(), requestValue)
		if routeErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, routeErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if writeErr := provider1.Respond(httpRequest.Context(), writer, responseValue); writeErr != nil {
			return
		}
	}), routeObservation4, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/{ownerId}/edit: %w", routeErr))
	}
	routeObservation5, routeObservationErr5 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|6:Create", Module: "", Method: "POST", Pattern: "/owners/new"}, httpObservers...)
	if routeObservationErr5 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route POST /owners/new observation: %w", routeObservationErr5))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "POST /owners/new", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			if writeErr := spiceweb.WriteProblem(writer, problem); writeErr != nil {
				return
			}
			return
		}
		requestValue := owner.OwnerFormRequest{}
		bindingResult, bindingResultErr := spiceweb.NewBindingResult()
		if bindingResultErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, bindingResultErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		formValues, formErr := spiceweb.DecodeForm(httpRequest, options.MaxRequestBodyBytes)
		if formErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(formErr)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if unknownFormErr := spiceweb.RejectUnknownForm(formValues, []string{"firstName", "lastName", "address", "city", "telephone"}); unknownFormErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(unknownFormErr)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		}
		raw0, present0, bindErr0 := spiceweb.FormValue(formValues, "firstName", true)
		if bindErr0 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr0)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if present0 {
			requestValue.FirstName = string(raw0)
		}
		raw1, present1, bindErr1 := spiceweb.FormValue(formValues, "lastName", true)
		if bindErr1 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr1)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if present1 {
			requestValue.LastName = string(raw1)
		}
		raw2, present2, bindErr2 := spiceweb.FormValue(formValues, "address", true)
		if bindErr2 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr2)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if present2 {
			requestValue.Address = string(raw2)
		}
		raw3, present3, bindErr3 := spiceweb.FormValue(formValues, "city", true)
		if bindErr3 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr3)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if present3 {
			requestValue.City = string(raw3)
		}
		raw4, present4, bindErr4 := spiceweb.FormValue(formValues, "telephone", true)
		if bindErr4 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr4)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if present4 {
			requestValue.Telephone = string(raw4)
		}
		responseValue, routeErr := provider5.Create(httpRequest.Context(), requestValue, bindingResult)
		if routeErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, routeErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if writeErr := provider1.Respond(httpRequest.Context(), writer, responseValue); writeErr != nil {
			return
		}
	}), routeObservation5, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route POST /owners/new: %w", routeErr))
	}
	routeObservation6, routeObservationErr6 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|6:Update", Module: "", Method: "POST", Pattern: "/owners/{ownerId}/edit"}, httpObservers...)
	if routeObservationErr6 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route POST /owners/{ownerId}/edit observation: %w", routeObservationErr6))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "POST /owners/{ownerId}/edit", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			if writeErr := spiceweb.WriteProblem(writer, problem); writeErr != nil {
				return
			}
			return
		}
		requestValue := owner.EditOwnerRequest{}
		bindingResult, bindingResultErr := spiceweb.NewBindingResult()
		if bindingResultErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, bindingResultErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		formValues, formErr := spiceweb.DecodeForm(httpRequest, options.MaxRequestBodyBytes)
		if formErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(formErr)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if unknownFormErr := spiceweb.RejectUnknownForm(formValues, []string{"firstName", "lastName", "address", "city", "telephone"}); unknownFormErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(unknownFormErr)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, bindErr0, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, parseErr0, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.FormValue(formValues, "firstName", true)
		if bindErr1 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr1)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if present1 {
			requestValue.FirstName = string(raw1)
		}
		raw2, present2, bindErr2 := spiceweb.FormValue(formValues, "lastName", true)
		if bindErr2 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr2)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if present2 {
			requestValue.LastName = string(raw2)
		}
		raw3, present3, bindErr3 := spiceweb.FormValue(formValues, "address", true)
		if bindErr3 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr3)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if present3 {
			requestValue.Address = string(raw3)
		}
		raw4, present4, bindErr4 := spiceweb.FormValue(formValues, "city", true)
		if bindErr4 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr4)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if present4 {
			requestValue.City = string(raw4)
		}
		raw5, present5, bindErr5 := spiceweb.FormValue(formValues, "telephone", true)
		if bindErr5 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr5)
			if rejectErr != nil {
				if writeErr := spiceweb.WriteError(writer, httpRequest, rejectErr, options.ErrorMapper); writeErr != nil {
					return
				}
				return
			}
			bindingResult = updatedBindingResult
		} else if present5 {
			requestValue.Telephone = string(raw5)
		}
		responseValue, routeErr := provider5.Update(httpRequest.Context(), requestValue, bindingResult)
		if routeErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, routeErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if writeErr := provider1.Respond(httpRequest.Context(), writer, responseValue); writeErr != nil {
			return
		}
	}), routeObservation6, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route POST /owners/{ownerId}/edit: %w", routeErr))
	}
	routeObservation7, routeObservationErr7 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|57:github.com/StevenBuglione/spice/examples/petclinic/system|17:WelcomeController|4:Show", Module: "", Method: "GET", Pattern: "/"}, httpObservers...)
	if routeObservationErr7 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET / observation: %w", routeObservationErr7))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			if writeErr := spiceweb.WriteProblem(writer, problem); writeErr != nil {
				return
			}
			return
		}
		requestValue := system.WelcomeRequest{}
		responseValue, routeErr := provider7.Show(httpRequest.Context(), requestValue)
		if routeErr != nil {
			if writeErr := spiceweb.WriteError(writer, httpRequest, routeErr, options.ErrorMapper); writeErr != nil {
				return
			}
			return
		}
		if writeErr := provider1.Respond(httpRequest.Context(), writer, responseValue); writeErr != nil {
			return
		}
	}), routeObservation7, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /: %w", routeErr))
	}
	managementChecks, err := spicemanagement.LifecycleChecks(TargetID, "github.com/StevenBuglione/spice/examples/petclinic", application.State)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management lifecycle checks: %w", err))
	}
	managementManager, err := spicemanagement.New(managementChecks...)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management checks: %w", err))
	}
	managementConfiguration, err := spicemanagement.NewConfigurationReport(configurationSchema, configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management configuration report: %w", err))
	}
	managementModules, err := spicemanagement.NewModuleReport(
		[]spicemanagement.ModuleDefinition{},
		[]spicemanagement.ModuleEdge{},
		[]string{},
	)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management module report: %w", err))
	}
	managementHandler, err := spicemanagement.NewHandler(spicemanagement.HandlerOptions{
		Manager: managementManager,
		Info: map[string]string{
			"application": TargetID,
			"module":      "github.com/StevenBuglione/spice/examples/petclinic",
			"framework":   "Spice",
		},
		Metrics:       managementMetrics,
		Configuration: &managementConfiguration,
		Modules:       &managementModules,
		Expose: []spicemanagement.Endpoint{
			spicemanagement.EndpointConfigProps,
			spicemanagement.EndpointHealth,
			spicemanagement.EndpointInfo,
			spicemanagement.EndpointLiveness,
			spicemanagement.EndpointMetrics,
			spicemanagement.EndpointModules,
			spicemanagement.EndpointReadiness,
		},
	})
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management handler: %w", err))
	}
	if err := spiceweb.Register(routeMux, managementHandler.Pattern(), managementHandler); err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register management routes: %w", err))
	}
	return application, nil
}

func (application *Application) State() spicelifecycle.State {
	if application == nil || application.coordinator == nil {
		return spicelifecycle.StateInvalid
	}
	return application.coordinator.State()
}

func (application *Application) Start(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("start application: application is nil")
	}
	return application.coordinator.Start(ctx, application.hooks)
}

func (application *Application) Stop(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("stop application: application is nil")
	}
	return application.coordinator.Stop(ctx)
}

func (application *Application) ShutdownTimeout() time.Duration {
	if application == nil {
		return 0
	}
	return application.shutdownTimeout
}

func (application *Application) RegisterObserver(observer spicelifecycle.Observer) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("register lifecycle observer: application is nil")
	}
	return application.coordinator.RegisterObserver(observer)
}

func (application *Application) Run(ctx context.Context, shutdown spicelifecycle.ContextFactory) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("run application: application is nil")
	}
	return application.coordinator.Run(ctx, application.hooks, shutdown)
}

// Components returns a typed snapshot of constructed singleton beans.
func (application *Application) Components() Components {
	if application == nil {
		return Components{}
	}
	return application.components
}

func (application *Application) Handler() http.Handler {
	if application == nil {
		return nil
	}
	return application.handler
}

type ShutdownContextFactory func(time.Duration) (context.Context, context.CancelFunc)

type CommandOptions struct {
	Context         context.Context
	Arguments       []string
	Stdout          io.Writer
	Stderr          io.Writer
	Logger          *slog.Logger
	ShutdownTimeout time.Duration
	ShutdownContext ShutdownContextFactory
	Application     ApplicationOptions
}

func Main(arguments []string) int {
	logger := slog.New(slog.NewJSONHandler(os.Stderr, nil))
	environment, err := spiceconfig.OSEnvironment("SPICE_")
	if err != nil {
		logger.Error("Spice command configuration failed", slog.Any("error", err))
		return ExitFailure
	}
	runContext, stopSignals := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stopSignals()
	return RunCommand(CommandOptions{
		Context:   runContext,
		Arguments: arguments,
		Stdout:    os.Stdout,
		Stderr:    os.Stderr,
		Logger:    logger,
		Application: ApplicationOptions{
			Sources: []spiceconfig.Source{environment},
		},
	})
}

func RunCommand(options CommandOptions) int {
	stdout := options.Stdout
	if stdout == nil {
		stdout = io.Discard
	}
	stderr := options.Stderr
	if stderr == nil {
		stderr = io.Discard
	}
	logger := options.Logger
	if logger == nil {
		logger = slog.New(slog.NewJSONHandler(stderr, nil))
	}
	ctx := options.Context
	if ctx == nil {
		return commandFailure(context.Background(), logger, "Spice command context is nil", nil)
	}
	if options.ShutdownTimeout < 0 {
		return commandFailure(ctx, logger, "Spice shutdown timeout is invalid", nil)
	}

	flags := flag.NewFlagSet(TargetID, flag.ContinueOnError)
	flags.SetOutput(stderr)
	check := flags.Bool("check", false, "construct the generated application and exit")
	if err := flags.Parse(options.Arguments); err != nil {
		logger.ErrorContext(ctx, "Spice command arguments are invalid", slog.Any("error", err))
		return ExitUsage
	}
	if flags.NArg() != 0 {
		if _, err := fmt.Fprintf(stderr, "%s does not accept positional arguments\n", TargetID); err != nil {
			logger.ErrorContext(ctx, "Spice command usage output failed", slog.Any("error", err))
		}
		return ExitUsage
	}

	applicationOptions := options.Application
	applicationOptions.Logger = logger
	logger.InfoContext(ctx, "Spice application constructing", slog.String("application", TargetID))
	application, err := NewApplicationWithOptions(ctx, applicationOptions)
	if err != nil {
		return commandFailure(ctx, logger, "Spice application construction failed", err)
	}

	shutdownTimeout := application.shutdownTimeout
	if options.ShutdownTimeout > 0 {
		shutdownTimeout = options.ShutdownTimeout
	}
	shutdownContext := options.ShutdownContext
	if shutdownContext == nil {
		shutdownContext = func(timeout time.Duration) (context.Context, context.CancelFunc) {
			return context.WithTimeout(context.Background(), timeout)
		}
	}
	shutdown := func() (context.Context, context.CancelFunc) {
		return shutdownContext(shutdownTimeout)
	}

	if *check {
		if err := stopCheckedApplication(application, shutdown); err != nil {
			return commandFailure(ctx, logger, "Spice application check cleanup failed", err)
		}
		if _, err := fmt.Fprintf(stdout, "Spice %s ready.\n", TargetID); err != nil {
			return commandFailure(ctx, logger, "Spice readiness output failed", err)
		}
		return ExitSuccess
	}

	logger.InfoContext(ctx, "Spice application starting", slog.String("application", TargetID))
	if err := application.Run(ctx, shutdown); err != nil {
		return commandFailure(ctx, logger, "Spice application run failed", err)
	}
	logger.InfoContext(context.Background(), "Spice application stopped", slog.String("application", TargetID))
	return ExitSuccess
}

func stopCheckedApplication(
	application *Application,
	shutdown spicelifecycle.ContextFactory,
) error {
	shutdownContext, cancel := shutdown()
	if shutdownContext == nil || cancel == nil {
		return fmt.Errorf("check application: shutdown context factory returned a nil context or cancel function")
	}
	defer cancel()
	return application.Stop(shutdownContext)
}

func commandFailure(
	ctx context.Context,
	logger *slog.Logger,
	message string,
	err error,
) int {
	if err == nil {
		logger.ErrorContext(ctx, message)
	} else {
		logger.ErrorContext(ctx, message, slog.Any("error", err))
	}
	return ExitFailure
}
