package cli

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/StevenBuglione/spice/compiler/load"
)

func TestRunVersion(t *testing.T) {
	t.Parallel()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run([]string{"version"}, &stdout, &stderr)
	if code != 0 || !strings.Contains(stdout.String(), Version) {
		t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout.String(), stderr.String())
	}
}

func TestRunVerifyAcceptsValidBuiltIns(t *testing.T) {
	t.Parallel()
	root := writeGoSource(t, `package sample

import "net/http"

// @Controller(prefix="/users")
type Controller struct{}

// @Bean
func NewController() *Controller { return &Controller{} }

// @Get("/{id}")
func (*Controller) Get(http.ResponseWriter, *http.Request) {}
`)
	code, stdout, stderr := runModule(root, "verify", ".")
	if code != 0 || !strings.Contains(stdout, "verification passed") {
		t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout, stderr)
	}
}

func TestRunLoadsOnceAndPassesPatternsUnchanged(t *testing.T) {
	t.Parallel()
	root := writeModule(t, map[string]string{
		"a/a.go": "package a\n\n// @Service\ntype A struct{}\n",
		"b/b.go": "package b\n\n// @Service\ntype B struct{}\n",
	})
	calls := 0
	var received []string
	loader := func(ctx context.Context, options load.Options, patterns ...string) (*load.Program, error) {
		calls++
		received = append([]string(nil), patterns...)
		return load.Load(ctx, options, patterns...)
	}
	var stdout, stderr bytes.Buffer
	code := run([]string{"annotations", "./a", "./b"}, &stdout, &stderr, load.Options{Dir: root}, loader)
	if code != 0 || calls != 1 || !reflect.DeepEqual(received, []string{"./a", "./b"}) {
		t.Fatalf("code=%d calls=%d patterns=%v stdout=%q stderr=%q", code, calls, received, stdout.String(), stderr.String())
	}
}

func TestRunVerifyIgnoresBuildTagExcludedAnnotation(t *testing.T) {
	t.Parallel()
	root := writeModule(t, map[string]string{
		"active.go": "package sample\n\n// @Service\ntype Active struct{}\n",
		"excluded.go": `//go:build spice_never

package sample

// @UnknownAnnotation
func Excluded() {}
`,
	})
	code, stdout, stderr := runModule(root, "verify", ".")
	if code != 0 || !strings.Contains(stdout, "1 annotations") {
		t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout, stderr)
	}
}

func TestRunVerifyIncludesCommittedGeneratedDependencies(t *testing.T) {
	t.Parallel()
	root := writeModule(t, map[string]string{
		"app/application.go": `package app

// @Application
func Example() {}
`,
		"cmd/example/main.go": `package main

import generated "example.com/fixture/internal/spicegen/example"

func main() {
	_ = generated.TargetID
}
`,
		"internal/spicegen/example/zz_spice_gen.go": `// Code generated by Spice. DO NOT EDIT.
//go:build !spice_generate

package spicegen

const TargetID = "example"
`,
	})
	code, stdout, stderr := runModule(root, "verify", "./...")
	if code != 0 || !strings.Contains(stdout, "verification passed") {
		t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout, stderr)
	}
}

func TestRunVerifyRejectsResolutionFailures(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name, source, expected string
	}{
		{"grouped", "package sample\n\n// @Configuration\ntype ( A struct{}; B struct{} )\n", "grouped declaration with 2 specs"},
		{"multi-name", "package sample\n\n// @Service\nvar Primary, Fallback int\n", "value declaration with 2 names"},
		{"blank", "package sample\n\n// @Service\nvar _ int\n", "cannot target blank identifier _"},
		{"malformed", "package sample\n\n// @Controller(prefix=)\ntype Controller struct{}\n", "unsupported argument value"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			code, stdout, stderr := runModule(writeGoSource(t, test.source), "verify", ".")
			if code != 1 || !strings.Contains(stderr, test.expected) {
				t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout, stderr)
			}
		})
	}
}

func TestRunVerifyRejectsArgumentFailures(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name     string
		source   string
		expected []string
	}{
		{name: "missing", source: "package sample\n\n// @Get\nfunc (Controller) Get() {}\ntype Controller struct{}\n", expected: []string{`requires argument "path"`}},
		{name: "unknown", source: "package sample\n\n// @Controller(prefx=\"/users\")\ntype Controller struct{}\n", expected: []string{`does not define argument "prefx"`, "available arguments: aliases, constructor, name, prefix"}},
		{name: "wrong kind", source: "package sample\n\n// @Controller(prefix=3)\ntype Controller struct{}\n", expected: []string{`argument "prefix" requires string, got integer`}},
		{name: "duplicate", source: "package sample\n\ntype Controller struct{}\n\n// @Get(\"/{id}\", path=\"/{other}\")\nfunc (Controller) Get() {}\n", expected: []string{`assigns argument "path" more than once`}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			code, stdout, stderr := runModule(writeGoSource(t, test.source), "verify", ".")
			if code != 1 {
				t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout, stderr)
			}
			for _, expected := range test.expected {
				if !strings.Contains(stderr, expected) {
					t.Fatalf("stderr=%q missing=%q", stderr, expected)
				}
			}
		})
	}
}

func TestRunVerifyRejectsInvalidTargetAndUnknownAnnotation(t *testing.T) {
	t.Parallel()
	tests := []struct{ source, expected string }{
		{"package sample\n\n// @Controller(prefix=\"/users\")\nfunc NewController() {}\n", "allowed target: type"},
		{"package sample\n\n// @custom.Feature\nfunc Feature() {}\n", "annotation @custom.Feature is not imported"},
	}
	for _, test := range tests {
		code, _, stderr := runModule(writeGoSource(t, test.source), "verify", ".")
		if code != 1 || !strings.Contains(stderr, test.expected) {
			t.Fatalf("code=%d stderr=%q", code, stderr)
		}
	}
}

func TestRunUsesDisplayPositionAndStableOutput(t *testing.T) {
	t.Parallel()
	root := writeGoSource(t, "package sample\n\n//line generated/schema.go:40\n// @Service\ntype Service struct{}\n")
	var first string
	for run := range 10 {
		code, stdout, stderr := runModule(root, "annotations", ".")
		if code != 0 || !strings.Contains(filepath.ToSlash(stdout), "generated/schema.go:40 type Service @Service") {
			t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout, stderr)
		}
		if run == 0 {
			first = stdout
		} else if stdout != first {
			t.Fatalf("output changed: first=%q next=%q", first, stdout)
		}
	}
}

func TestRunVerifyPreservesPhysicalDiagnosticOrderAcrossLineDirectives(t *testing.T) {
	t.Parallel()
	root := writeGoSource(t, `package sample

//line z.go:100
// @UnknownA
var First int

//line a.go:1
// @UnknownB
var Second int
`)
	var first string
	for run := range 10 {
		code, stdout, stderr := runModule(root, "verify", ".")
		if code != 1 || stdout != "" {
			t.Fatalf("run=%d code=%d stdout=%q stderr=%q", run, code, stdout, stderr)
		}
		normalized := filepath.ToSlash(stderr)
		zIndex := strings.Index(
			normalized,
			"z.go:100:1: [spice.resolution.annotation-import] annotation @UnknownA is not imported",
		)
		aIndex := strings.Index(
			normalized,
			"a.go:1:1: [spice.resolution.annotation-import] annotation @UnknownB is not imported",
		)
		if zIndex < 0 || aIndex < 0 || zIndex >= aIndex {
			t.Fatalf("run=%d diagnostics not in physical order: %q", run, stderr)
		}
		if run == 0 {
			first = stderr
		} else if stderr != first {
			t.Fatalf("run=%d output changed: first=%q next=%q", run, first, stderr)
		}
	}
}

func TestRunFailsBeforeValidationForBrokenOrMissingPackage(t *testing.T) {
	t.Parallel()
	root := writeGoSource(t, "package sample\n\n// @UnknownAnnotation\nvar Value string = 1\n")
	code, _, stderr := runModule(root, "verify", ".")
	if code != 1 || !strings.Contains(stderr, "cannot use") || strings.Contains(stderr, "unknown annotation") {
		t.Fatalf("code=%d stderr=%q", code, stderr)
	}
	code, _, stderr = runModule(root, "verify", "./missing")
	if code != 1 || !strings.Contains(stderr, "directory not found") {
		t.Fatalf("code=%d stderr=%q", code, stderr)
	}
}

func TestRunVerifyProviderGraph(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name       string
		source     string
		wantCode   int
		wantOutput []string
	}{
		{
			name: "valid",
			source: `package sample

type Config struct{}
type Service struct{}
// @Bean
func ConfigProvider() Config { panic("must not execute") }
// @Bean
func ServiceProvider(Config) Service { panic("must not execute") }
`,
			wantCode:   0,
			wantOutput: []string{"verification passed"},
		},
		{
			name: "missing",
			source: `package sample

type Service struct{}
// @Bean
func ServiceProvider(config string) Service { panic("must not execute") }
`,
			wantCode:   1,
			wantOutput: []string{"requires exact type string", `parameter 0 "config"`, "provider graph error"},
		},
		{
			name: "cycle",
			source: `package sample

type A struct{}
type B struct{}
// @Bean
func AProvider(B) A { panic("must not execute") }
// @Bean
func BProvider(A) B { panic("must not execute") }
`,
			wantCode:   1,
			wantOutput: []string{"provider dependency cycle", "AProvider", "BProvider", "provider graph error"},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			code, stdout, stderr := runModule(writeGoSource(t, test.source), "verify", ".")
			if code != test.wantCode {
				t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout, stderr)
			}
			output := stdout + stderr
			for _, expected := range test.wantOutput {
				if !strings.Contains(output, expected) {
					t.Fatalf("output=%q missing=%q", output, expected)
				}
			}
		})
	}
}

func TestRunUnknownCommand(t *testing.T) {
	t.Parallel()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	if code := Run([]string{"missing"}, &stdout, &stderr); code != 2 || !strings.Contains(stderr.String(), "unknown command") {
		t.Fatalf("code=%d stderr=%q", code, stderr.String())
	}
}

func TestRunReturnsFailureWhenOutputCannotBeWritten(t *testing.T) {
	t.Parallel()
	failing := errorWriter{}
	for _, arguments := range [][]string{
		nil,
		{"help"},
		{"version"},
		{"missing"},
	} {
		if code := Run(arguments, failing, failing); code != 1 {
			t.Fatalf("Run(%v) code = %d, want 1", arguments, code)
		}
	}

	root := writeGoSource(t, "package sample\n\n// @Service\ntype Service struct{}\n")
	for _, arguments := range [][]string{{"annotations", "."}, {"verify", "."}} {
		code := run(arguments, failing, &bytes.Buffer{}, load.Options{Dir: root}, load.Load)
		if code != 1 {
			t.Fatalf("run(%v) code = %d, want output failure", arguments, code)
		}
	}
	loaderFailure := errors.New("loader failed")
	loader := func(context.Context, load.Options, ...string) (*load.Program, error) {
		return nil, loaderFailure
	}
	if code := run([]string{"verify", "."}, &bytes.Buffer{}, failing, load.Options{}, loader); code != 1 {
		t.Fatalf("run(loader failure) code = %d, want 1", code)
	}
}

func TestReportDiagnosticsReturnsSummaryWriteFailure(t *testing.T) {
	t.Parallel()
	writer := &failAfterWriter{writesRemaining: 1}
	err := reportDiagnostics(writer, []diagnosticStub{{message: "diagnostic"}}, "summary")
	if err == nil {
		t.Fatal("reportDiagnostics() error = nil")
	}
}

func runModule(root string, arguments ...string) (int, string, string) {
	var stdout, stderr bytes.Buffer
	code := run(arguments, &stdout, &stderr, load.Options{Dir: root}, load.Load)
	return code, stdout.String(), stderr.String()
}

func writeGoSource(t *testing.T, source string) string {
	t.Helper()
	return writeModule(t, map[string]string{"sample.go": source})
}

func writeModule(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	normalized := make(map[string]string, len(files))
	usesAnnotations := false
	for path, source := range files {
		if filepath.Ext(path) == ".go" {
			source, usesAnnotations = withTestAnnotationImports(
				source,
				usesAnnotations,
			)
		}
		normalized[path] = source
	}
	goMod := normalized["go.mod"]
	if goMod == "" {
		goMod = "module example.com/fixture\n\ngo 1.26.0\n"
	}
	if usesAnnotations {
		goMod = withTestAnnotationTool(t, goMod)
	}
	if err := os.WriteFile(
		filepath.Join(root, "go.mod"),
		[]byte(goMod),
		0o600,
	); err != nil {
		t.Fatal(err)
	}
	for path, source := range normalized {
		if path == "go.mod" {
			continue
		}
		full := filepath.Join(root, filepath.FromSlash(path))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(source), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func withTestAnnotationImports(
	source string,
	alreadyFound bool,
) (string, bool) {
	if strings.Contains(source, "// @import") {
		return source, true
	}
	type descriptorImport struct {
		symbols   []string
		namespace string
		path      string
	}
	imports := []descriptorImport{
		{
			symbols: []string{
				"Application",
				"Bean",
				"Configuration",
				"Fallback",
				"Implements",
				"Order",
				"Primary",
				"Prototype",
				"Qualifier",
				"Repository",
				"RequestScope",
				"Service",
				"SessionScope",
				"Singleton",
			},
			path: "github.com/StevenBuglione/spice/annotation/core",
		},
		{
			symbols: []string{"OnStart", "OnStop"},
			path:    "github.com/StevenBuglione/spice/annotation/lifecycle",
		},
		{
			symbols: []string{"Module", "NamedInterface"},
			path:    "github.com/StevenBuglione/spice/annotation/modulith",
		},
		{
			symbols: []string{"Controller", "Get", "Post"},
			path:    "github.com/StevenBuglione/spice/annotation/web",
		},
		{
			namespace: "async",
			path:      "github.com/StevenBuglione/spice/annotation/async",
		},
		{
			namespace: "cache",
			path:      "github.com/StevenBuglione/spice/annotation/cache",
		},
		{
			namespace: "data",
			path:      "github.com/StevenBuglione/spice/annotation/data",
		},
		{
			namespace: "event",
			path:      "github.com/StevenBuglione/spice/annotation/event",
		},
		{
			namespace: "management",
			path:      "github.com/StevenBuglione/spice/annotation/management",
		},
		{
			namespace: "observability",
			path:      "github.com/StevenBuglione/spice/annotation/observability",
		},
		{
			namespace: "schedule",
			path:      "github.com/StevenBuglione/spice/annotation/schedule",
		},
		{
			namespace: "security",
			path:      "github.com/StevenBuglione/spice/annotation/security",
		},
	}
	var directives []string
	for _, item := range imports {
		if item.namespace != "" {
			if strings.Contains(
				source,
				"// @"+item.namespace+".",
			) {
				directives = append(
					directives,
					"// @import * as "+item.namespace+
						` from "`+item.path+`"`,
				)
			}
			continue
		}
		var selected []string
		for _, symbol := range item.symbols {
			if strings.Contains(source, "// @"+symbol) {
				selected = append(selected, symbol)
			}
		}
		if len(selected) != 0 {
			directives = append(
				directives,
				"// @import { "+strings.Join(selected, ", ")+
					` } from "`+item.path+`"`,
			)
		}
	}
	if len(directives) == 0 {
		return source, alreadyFound
	}
	return strings.TrimRight(source, "\r\n") + "\n\n" +
		strings.Join(directives, "\n") + "\n", true
}

func withTestAnnotationTool(t *testing.T, content string) string {
	t.Helper()
	lines := strings.Split(content, "\n")
	for index, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "go ") {
			lines[index] = "go 1.26.0"
			break
		}
	}
	content = strings.Join(lines, "\n")
	if !strings.Contains(
		content,
		"tool github.com/StevenBuglione/spice/cmd/spice-annotation-core",
	) {
		content += "\ntool github.com/StevenBuglione/spice/cmd/spice-annotation-core\n"
	}
	if strings.Contains(
		content,
		"module github.com/StevenBuglione/spice",
	) {
		return content
	}
	if !strings.Contains(
		content,
		"require github.com/StevenBuglione/spice ",
	) {
		content += "\nrequire github.com/StevenBuglione/spice v0.0.0\n"
	}
	if !strings.Contains(
		content,
		"replace github.com/StevenBuglione/spice =>",
	) {
		repository, err := filepath.Abs(filepath.Join("..", ".."))
		if err != nil {
			t.Fatal(err)
		}
		content += "\nreplace github.com/StevenBuglione/spice => " +
			filepath.ToSlash(repository) + "\n"
	}
	return content
}

type errorWriter struct{}

func (errorWriter) Write([]byte) (int, error) {
	return 0, errors.New("write failed")
}

type failAfterWriter struct {
	writesRemaining int
}

func (writer *failAfterWriter) Write(data []byte) (int, error) {
	if writer.writesRemaining == 0 {
		return 0, errors.New("write failed")
	}
	writer.writesRemaining--
	return len(data), nil
}

type diagnosticStub struct {
	message string
}

func (diagnostic diagnosticStub) Error() string {
	return diagnostic.message
}
