//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: examples/commerce/inventory/inventory.go:28
// Source: examples/commerce/inventory/inventory.go:42

package spicegen

import (
	fmt "fmt"

	spiceconfig "github.com/StevenBuglione/spice/config"
	inventory "github.com/StevenBuglione/spice/examples/commerce/inventory"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct538781be5a86 performs the direct construction selected for spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/commerce/inventory|0:|10:NewService.
func Construct538781be5a86(dependency0 inventory.Settings) (*inventory.Service, spicelifecycle.Cleanup, error) {
	value, err := inventory.NewService(dependency0)
	if err != nil {
		var zero *inventory.Service
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/commerce/inventory|0:|10:NewService (*github.com/StevenBuglione/spice/examples/commerce/inventory.Service): %w", err)
	}
	return value, nil, nil
}

// Bind8a49b112910c binds the validated configuration declared by spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/commerce/inventory|0:|8:Settings.
func Bind8a49b112910c(configurationSnapshot spiceconfig.Snapshot) (inventory.Settings, error) {
	value := inventory.Settings{}
	if _, configured := configurationSnapshot.Lookup("commerce.inventory.sku"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("commerce.inventory.sku")
		if valueErr != nil {
			return inventory.Settings{}, fmt.Errorf("decode configuration property commerce.inventory.sku for github.com/StevenBuglione/spice/examples/commerce/inventory.Settings.SKU: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.SKU = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("commerce.inventory.initial-stock"); configured {
		rawValue, valueErr := configurationSnapshot.Integer("commerce.inventory.initial-stock")
		if valueErr != nil {
			return inventory.Settings{}, fmt.Errorf("decode configuration property commerce.inventory.initial-stock for github.com/StevenBuglione/spice/examples/commerce/inventory.Settings.InitialStock: %w", valueErr)
		}
		convertedValue := int(rawValue)
		if int64(convertedValue) != rawValue {
			return inventory.Settings{}, fmt.Errorf("decode configuration property commerce.inventory.initial-stock for github.com/StevenBuglione/spice/examples/commerce/inventory.Settings.InitialStock: value is outside int")
		}
		value.InitialStock = convertedValue
	}
	return value, nil
}
