package style

import (
	"context"
	"maps"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/spice-framework/toolchain/compiler/load"
	"github.com/spice-framework/toolchain/compiler/provider"
	"github.com/spice-framework/toolchain/compiler/resolve"
	"github.com/spice-framework/toolchain/internal/testannotation"
	"github.com/spice-framework/toolchain/internal/testsupport"
)

func TestBuildAcceptsJavaStructuredSource(t *testing.T) {
	program, resolution, providers := loadStyleFixture(t, map[string]string{
		"app/doc.go": `// Package app owns workers.
package app
`,
		"app/runner.go": `package app

type Runner interface {
	Run()
}
`,
		"app/worker.go": `package app

// @Component
// @Implements(Runner)
type Worker struct{}

func NewWorker() *Worker { return &Worker{} }

func (*Worker) Run() {}
`,
		"app/status.go": `package app

// @Enum
type Status string

const StatusReady Status = "ready"

func ParseStatus(value string) (Status, bool) {
	status := Status(value)
	return status, status.Valid()
}

func (status Status) Valid() bool { return status == StatusReady }
`,
		"app/external.go": `package app

type External struct{}
`,
		"app/external_bean.go": `package app

// @Bean
func NewExternalBean() *External { return &External{} }
`,
		"app/event.go": `package app

type Event struct{}
`,
		"app/event_topic.go": `package app

import "github.com/spice-framework/spice/event"

// @event.Topic
func EventTopic() event.Publisher[Event] { panic("metadata only") }
`,
		"app/generated.go": `// Code generated by a test. DO NOT EDIT.
package app

type GeneratedOne struct{}
type GeneratedTwo struct{}
func helper() {}
`,
		"app/worker_test.go": `package app

type TestOnlyOne struct{}
type TestOnlyTwo struct{}
func testHelper() {}
`,
	})
	diagnostics := Build(
		program,
		resolution,
		providers,
		ProfileJavaStructured,
	).Diagnostics()
	if len(diagnostics) != 0 {
		t.Fatalf("Build() diagnostics = %v", diagnosticStrings(diagnostics))
	}
}

func TestBuildRejectsJavaStructuredViolations(t *testing.T) {
	tests := []struct {
		name  string
		files map[string]string
		want  string
	}{
		{
			name: "one type per file",
			files: map[string]string{
				"app/types.go": "package app\n\ntype First struct{}\ntype Second struct{}\n",
			},
			want: "file.one-primary-type",
		},
		{
			name: "receiver colocation",
			files: map[string]string{
				"app/worker.go":        "package app\n\ntype Worker struct{}\n",
				"app/worker_method.go": "package app\n\nfunc (*Worker) Run() {}\n",
			},
			want: "file.method-owner",
		},
		{
			name: "free function",
			files: map[string]string{
				"app/worker.go": "package app\n\ntype Worker struct{}\n\nfunc normalize() {}\n",
			},
			want: "function.package-level",
		},
		{
			name: "package bean",
			files: map[string]string{
				"app/dependency.go": "package app\n\ntype Dependency struct{}\n\n// @Bean\nfunc NewDependency() *Dependency { return &Dependency{} }\n",
			},
			want: "function.package-level",
		},
		{
			name: "function topic",
			files: map[string]string{
				"app/event.go": `package app

import "github.com/spice-framework/spice/event"

type Event struct{}

// @event.Topic
func EventTopic() event.Publisher[Event] { panic("metadata only") }
`,
			},
			want: "function.package-level",
		},
		{
			name: "generic constructor",
			files: map[string]string{
				"app/worker.go": "package app\n\n// @Service\ntype Worker struct{}\n\nfunc New() *Worker { return &Worker{} }\n",
			},
			want: "constructor.name",
		},
		{
			name: "missing explicit constructor",
			files: map[string]string{
				"app/worker.go": "package app\n\n// @Service\ntype Worker struct{}\n",
			},
			want: "constructor.explicit",
		},
		{
			name: "constructor file",
			files: map[string]string{
				"app/worker.go":             "package app\n\n// @Service\ntype Worker struct{}\n",
				"app/worker_constructor.go": "package app\n\nfunc NewWorker() *Worker { return &Worker{} }\n",
			},
			want: "constructor.location",
		},
		{
			name: "package file declaration",
			files: map[string]string{
				"app/doc.go": "package app\n\nconst Name = \"app\"\n",
			},
			want: "file.unrelated-declaration",
		},
		{
			name: "mutable global",
			files: map[string]string{
				"app/value.go": "package app\n\nvar value int\n",
			},
			want: "package.mutable-global",
		},
		{
			name: "init",
			files: map[string]string{
				"app/value.go": "package app\n\nfunc init() {}\n",
			},
			want: "function.init",
		},
		{
			name: "implicit managed interface",
			files: map[string]string{
				"app/runner.go": "package app\n\ntype Runner interface { Run() }\n",
				"app/worker.go": "package app\n\n// @Component\ntype Worker struct{}\n\nfunc (*Worker) Run() {}\n",
			},
			want: "bean.interface-binding",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			program, resolution, providers := loadStyleFixture(t, test.files)
			diagnostics := Build(
				program,
				resolution,
				providers,
				ProfileJavaStructured,
			).Diagnostics()
			if !containsKind(diagnostics, test.want) {
				t.Fatalf(
					"Build() diagnostics = %v, want kind %q",
					diagnosticStrings(diagnostics),
					test.want,
				)
			}
		})
	}
}

func TestBuildDoesNothingWithoutProfile(t *testing.T) {
	program, resolution, providers := loadStyleFixture(t, map[string]string{
		"app/app.go": "package app\n\ntype First struct{}\ntype Second struct{}\nfunc helper() {}\n",
	})
	if diagnostics := Build(
		program,
		resolution,
		providers,
		ProfileNone,
	).Diagnostics(); len(diagnostics) != 0 {
		t.Fatalf("Build(ProfileNone) diagnostics = %v", diagnostics)
	}
}

func TestBuildConfiguredHonorsSharedRuleLevels(t *testing.T) {
	program, resolution, providers := loadStyleFixture(t, map[string]string{
		"app/types.go": "package app\n\ntype First struct{}\ntype Second struct{}\n\nfunc helper() {}\n",
	})
	configuration, err := DecodeConfiguration(canonicalTestConfiguration(t))
	if err != nil {
		t.Fatal(err)
	}
	configuration.Rules.OnePrimaryTypePerFile = RuleLevelOff
	configuration.Rules.PackageFunctions = RuleLevelOff
	configuration.Rules.BanMutablePackageState = RuleLevelOff
	if diagnostics := BuildConfigured(program, resolution, providers, configuration).Diagnostics(); len(diagnostics) != 0 {
		t.Fatalf("BuildConfigured() diagnostics = %v", diagnosticStrings(diagnostics))
	}
}

func TestBuildConfiguredRejectsInvalidConfigurationAndNilProgram(t *testing.T) {
	configuration, err := DecodeConfiguration(canonicalTestConfiguration(t))
	if err != nil {
		t.Fatal(err)
	}
	invalid := configuration.Clone()
	invalid.Rules.ExplicitManagedScopes = RuleLevelError
	if diagnostics := BuildConfigured(nil, resolve.Result{}, provider.Catalog{}, invalid).Diagnostics(); !containsKind(diagnostics, "configuration.unsupported-rule") {
		t.Fatalf("invalid configuration diagnostics = %v", diagnosticStrings(diagnostics))
	}
	if diagnostics := BuildConfigured(nil, resolve.Result{}, provider.Catalog{}, configuration).Diagnostics(); !containsKind(diagnostics, "internal") {
		t.Fatalf("nil program diagnostics = %v", diagnosticStrings(diagnostics))
	}
}

func TestValidateProfileRejectsUnknownName(t *testing.T) {
	if err := ValidateProfile("java"); err == nil ||
		!strings.Contains(err.Error(), "java-structured") {
		t.Fatalf("ValidateProfile(java) error = %v", err)
	}
}

func loadStyleFixture(
	t *testing.T,
	files map[string]string,
) (*load.Program, resolve.Result, provider.Catalog) {
	t.Helper()
	root := t.TempDir()
	core := testsupport.CoreDirectory(t)
	allFiles := map[string]string{
		"go.mod": "module example.com/style\n\ngo 1.26.0\n\n" +
			"require github.com/spice-framework/spice v0.0.0\n\n" +
			"replace github.com/spice-framework/spice => " +
			filepath.ToSlash(core) + "\n",
	}
	maps.Copy(allFiles, files)
	paths := make([]string, 0, len(allFiles))
	for name := range allFiles {
		paths = append(paths, name)
	}
	sort.Strings(paths)
	for _, name := range paths {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(allFiles[name]), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	program, err := load.Load(
		context.Background(),
		load.Options{Dir: root},
		"./app",
	)
	if err != nil {
		t.Fatalf("load.Load() error = %v", err)
	}
	resolution := resolve.Annotations(program)
	if len(resolution.Diagnostics) != 0 {
		t.Fatalf("resolve.Annotations() diagnostics = %v", resolution.Diagnostics)
	}
	resolution, err = testannotation.AttachOfficial(resolution)
	if err != nil {
		t.Fatalf("AttachOfficial() error = %v", err)
	}
	providers := provider.Build(program, resolution)
	if diagnostics := providers.Diagnostics(); len(diagnostics) != 0 {
		t.Fatalf("provider.Build() diagnostics = %v", diagnostics)
	}
	return program, resolution, providers
}

func containsKind(diagnostics []Diagnostic, wanted string) bool {
	for _, diagnostic := range diagnostics {
		if diagnostic.Kind == wanted {
			return true
		}
	}
	return false
}

func diagnosticStrings(diagnostics []Diagnostic) []string {
	result := make([]string, len(diagnostics))
	for index, diagnostic := range diagnostics {
		result[index] = diagnostic.Error()
	}
	return result
}
