// Package generate renders deterministic generated application plans from one
// validated Spice application model. It performs no filesystem writes.
package generate

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"go/token"
	"go/types"
	"io/fs"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/StevenBuglione/spice/compiler/application"
	"github.com/StevenBuglione/spice/compiler/configuration"
	"github.com/StevenBuglione/spice/compiler/controller"
	"github.com/StevenBuglione/spice/compiler/load"
	"github.com/StevenBuglione/spice/compiler/provider"
	runtimeconfig "github.com/StevenBuglione/spice/config"
)

const (
	// SchemaVersion is the current generated ownership manifest schema.
	SchemaVersion = 1
	// GeneratorVersion is recorded in manifests to make generator compatibility
	// explicit during freshness checks.
	GeneratorVersion = "0.1.0-dev"
	// GoFormatLine is the supported Go formatter compatibility line.
	GoFormatLine = "1.26"
	// AnalysisBuildTag excludes committed generated packages while Spice
	// analyzes source, allowing stale output to be regenerated safely.
	AnalysisBuildTag = "spice_generate"

	generatedFilename = "zz_spice_gen.go"
	configPath        = "github.com/StevenBuglione/spice/config"
	lifecyclePath     = "github.com/StevenBuglione/spice/lifecycle"
	webPath           = "github.com/StevenBuglione/spice/web"
)

var targetIDPattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// Target identifies one module-scoped generated application output.
type Target struct {
	ID           string
	ModulePath   string
	ModuleRoot   string
	PackagePath  string
	OutputDir    string
	ManifestPath string
}

// TargetSummary is the safe, serializable subset of a generation target.
type TargetSummary struct {
	ID           string `json:"id"`
	ModulePath   string `json:"module"`
	PackagePath  string `json:"package"`
	OutputDir    string `json:"output_dir"`
	ManifestPath string `json:"manifest_path"`
}

// ManifestFile records one generated file owned by a target.
type ManifestFile struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

// Manifest is the deterministic generated-file ownership record.
type Manifest struct {
	Schema           int            `json:"schema"`
	Target           TargetSummary  `json:"target"`
	GeneratorVersion string         `json:"generator_version"`
	GoFormatLine     string         `json:"go_format_line"`
	InputSHA256      string         `json:"input_sha256"`
	Files            []ManifestFile `json:"files"`
}

// File is one generated file in a render plan.
type File struct {
	Path    string
	Mode    fs.FileMode
	SHA256  string
	content []byte
}

// Content returns a defensive copy of the generated bytes.
func (f File) Content() []byte {
	return append([]byte(nil), f.content...)
}

// Plan is a deterministic in-memory generation result.
type Plan struct {
	target          Target
	files           []File
	manifest        Manifest
	manifestContent []byte
}

// Target returns the plan's target.
func (p Plan) Target() Target {
	return p.target
}

// Files returns defensive copies sorted by module-relative path.
func (p Plan) Files() []File {
	result := make([]File, len(p.files))
	copy(result, p.files)
	for index := range result {
		result[index].content = append([]byte(nil), p.files[index].content...)
	}
	return result
}

// Manifest returns a defensive copy of the ownership manifest.
func (p Plan) Manifest() Manifest {
	result := p.manifest
	result.Files = append([]ManifestFile(nil), p.manifest.Files...)
	return result
}

// ManifestContent returns the exact canonical manifest bytes.
func (p Plan) ManifestContent() []byte {
	return append([]byte(nil), p.manifestContent...)
}

// Diagnostic is one deterministic generation failure.
type Diagnostic struct {
	Position         token.Position
	PhysicalPosition token.Position
	TargetID         string
	Kind             string
	Message          string
}

// Error renders a compiler-style diagnostic.
func (d Diagnostic) Error() string {
	position := d.Position
	if position.Filename == "" {
		position.Filename = "<generation>"
	}
	if position.Line <= 0 {
		position.Line = 1
	}
	if position.Column <= 0 {
		position.Column = 1
	}
	return fmt.Sprintf("%s:%d:%d: %s", position.Filename, position.Line, position.Column, d.Message)
}

// DefaultTarget derives the standard module-scoped output for one application
// marker: internal/spicegen/<lowercase-function-name> and
// .spice/<target>.manifest.json.
func DefaultTarget(program *load.Program, applicationTarget application.Target) (Target, []Diagnostic) {
	if program == nil {
		return Target{}, []Diagnostic{{
			Kind:    "invalid-program",
			Message: "derive generation target: loaded program is nil",
		}}
	}
	pkg, ok := packageByPath(program.Packages(), applicationTarget.PackagePath)
	if !ok || pkg.Raw == nil || pkg.Raw.Module == nil {
		return Target{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"module",
			fmt.Sprintf(
				"@Application target %s is not owned by a Go module; select a module-backed package",
				applicationTarget.SymbolID,
			),
		)}
	}
	id := strings.ToLower(applicationTarget.Name)
	outputDir := path.Join("internal", "spicegen", id)
	target := Target{
		ID:           id,
		ModulePath:   pkg.Raw.Module.Path,
		ModuleRoot:   pkg.Raw.Module.Dir,
		PackagePath:  path.Join(pkg.Raw.Module.Path, outputDir),
		OutputDir:    outputDir,
		ManifestPath: path.Join(".spice", id+".manifest.json"),
	}
	if diagnostics := validateTarget(target, applicationTarget); len(diagnostics) != 0 {
		return Target{}, diagnostics
	}
	return target, nil
}

// Render creates canonical generated Go and ownership manifest bytes entirely
// in memory. It consumes the application model's existing order and edges and
// never reloads packages, rebuilds dependency resolution, or executes source.
func Render(
	program *load.Program,
	model application.Model,
	applicationTarget application.Target,
	target Target,
) (Plan, []Diagnostic) {
	if program == nil {
		return Plan{}, []Diagnostic{{
			Kind:    "invalid-program",
			Message: "render application: loaded program is nil",
		}}
	}
	if diagnostics := model.Diagnostics(); len(diagnostics) != 0 {
		return Plan{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"invalid-model",
			fmt.Sprintf("render application: model has %d diagnostic(s)", len(diagnostics)),
		)}
	}
	if diagnostics := validateTarget(target, applicationTarget); len(diagnostics) != 0 {
		return Plan{}, diagnostics
	}
	if !containsTarget(model.Targets(), applicationTarget.SymbolID) {
		return Plan{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"unknown-target",
			fmt.Sprintf("application target %s is not present in the supplied model", applicationTarget.SymbolID),
		)}
	}
	if diagnostics := validateRenderable(program, model, applicationTarget, target); len(diagnostics) != 0 {
		return Plan{}, diagnostics
	}

	source, renderErr := renderSource(model, applicationTarget, target)
	if renderErr != nil {
		return Plan{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"render",
			fmt.Sprintf("render generated Go: %v", renderErr),
		)}
	}
	generatedPath := path.Join(target.OutputDir, generatedFilename)
	file := File{
		Path:    generatedPath,
		Mode:    0o644,
		SHA256:  contentHash(source),
		content: source,
	}
	inputHash, hashErr := modelHash(model, applicationTarget, target)
	if hashErr != nil {
		return Plan{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"input-hash",
			fmt.Sprintf("hash application model: %v", hashErr),
		)}
	}
	manifest := Manifest{
		Schema:           SchemaVersion,
		Target:           summarizeTarget(target),
		GeneratorVersion: GeneratorVersion,
		GoFormatLine:     GoFormatLine,
		InputSHA256:      inputHash,
		Files: []ManifestFile{{
			Path:   file.Path,
			SHA256: file.SHA256,
		}},
	}
	manifestContent, manifestErr := json.MarshalIndent(manifest, "", "  ")
	if manifestErr != nil {
		return Plan{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"manifest",
			fmt.Sprintf("encode generation manifest: %v", manifestErr),
		)}
	}
	manifestContent = append(manifestContent, '\n')
	return Plan{
		target:          target,
		files:           []File{file},
		manifest:        manifest,
		manifestContent: manifestContent,
	}, nil
}

func renderSource(
	model application.Model,
	applicationTarget application.Target,
	target Target,
) ([]byte, error) {
	providers := model.Providers()
	configTypes := model.Configurations()
	controllers := model.Controllers()
	aliases := importAliases(providers, configTypes, controllers)
	hasOptions := len(configTypes) != 0 || len(controllers) != 0
	providerModules := providerModuleIDs(model, providers)
	dependencies, err := dependencyVariables(model, providers)
	if err != nil {
		return nil, err
	}
	providerVariables := make(map[string]string, len(providers))
	for index, item := range providers {
		providerVariables[item.SymbolID] = providerVariable(index)
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by Spice. DO NOT EDIT.\n")
	source.WriteString("//go:build !" + AnalysisBuildTag + "\n\n")
	source.WriteString("package spicegen\n\n")
	writeImports(&source, aliases)
	fmt.Fprintf(&source, "const TargetID = %s\n\n", strconv.Quote(target.ID))
	source.WriteString("type Application struct {\n")
	source.WriteString("\tcoordinator *spicelifecycle.Coordinator\n")
	source.WriteString("\thooks []spicelifecycle.Hook\n")
	if len(controllers) != 0 {
		source.WriteString("\thandler http.Handler\n")
	}
	source.WriteString("}\n\n")
	if hasOptions {
		writeApplicationOptions(&source, len(configTypes) != 0, len(controllers) != 0)
	}
	if len(configTypes) != 0 {
		writeConfigurationAPI(&source, configTypes)
	}
	if hasOptions {
		source.WriteString("func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {\n")
		source.WriteString("\treturn NewApplicationWithOptions(ctx, ApplicationOptions{Observers: observers})\n")
		source.WriteString("}\n\n")
		source.WriteString("func NewApplicationWithOptions(ctx context.Context, options ApplicationOptions) (*Application, error) {\n")
	} else {
		source.WriteString("func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {\n")
	}
	fmt.Fprintf(
		&source,
		"\tif ctx == nil {\n\t\treturn nil, fmt.Errorf(%s)\n\t}\n",
		strconv.Quote("construct application "+target.ID+": context is nil"),
	)
	source.WriteString("\tapplication := &Application{coordinator: spicelifecycle.NewCoordinator()}\n")
	if hasOptions {
		source.WriteString("\tobservers := options.Observers\n")
	}
	source.WriteString("\tfor index, observer := range observers {\n")
	source.WriteString("\t\tif err := application.coordinator.RegisterObserver(observer); err != nil {\n")
	source.WriteString("\t\t\treturn nil, fmt.Errorf(\"register lifecycle observer %d: %w\", index, err)\n")
	source.WriteString("\t\t}\n")
	source.WriteString("\t}\n")
	if len(configTypes) != 0 {
		writeConfigurationResolution(&source, target)
	}
	if providerErr := writeProviders(
		&source,
		providers,
		configTypes,
		aliases,
		dependencies,
		providerModules,
	); providerErr != nil {
		return nil, providerErr
	}
	if len(controllers) != 0 {
		writeControllerRoutes(&source, controllers, providers, providerVariables, aliases)
	}
	writeHooks(&source, model, providerVariables, providerModules)
	source.WriteString("\treturn application, nil\n")
	source.WriteString("}\n\n")
	writeLifecycleMethods(&source)
	if len(controllers) != 0 {
		writeHandlerMethod(&source)
	}

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source for %s: %w", applicationTarget.SymbolID, err)
	}
	return formatted, nil
}

func writeProviders(
	source *bytes.Buffer,
	providers []provider.Provider,
	configTypes []configuration.Type,
	aliases map[string]string,
	dependencies map[string][]string,
	providerModules map[string]string,
) error {
	configByProvider := configurationProviderIndex(configTypes)
	for index, item := range providers {
		switch item.Source {
		case provider.SourceBean:
			writeProviderCall(
				source,
				item,
				index,
				aliases,
				dependencies[item.SymbolID],
				providerModules[item.SymbolID],
			)
		case provider.SourceConfiguration:
			configType, ok := configByProvider[item.SymbolID]
			if !ok {
				return fmt.Errorf("configuration provider %s has no typed configuration metadata", item.SymbolID)
			}
			writeConfigurationBinder(source, configType, index, aliases)
		default:
			return fmt.Errorf("provider %s has unsupported source %q", item.SymbolID, item.Source)
		}
	}
	return nil
}

func writeControllerRoutes(
	source *bytes.Buffer,
	controllers []controller.Controller,
	providers []provider.Provider,
	providerVariables map[string]string,
	aliases map[string]string,
) {
	muxVariable := ""
	for _, item := range providers {
		if pointerNamedType(item.Output, "net/http", "ServeMux") {
			muxVariable = providerVariables[item.SymbolID]
			break
		}
	}
	if muxVariable == "" {
		source.WriteString("\trouteMux := http.NewServeMux()\n")
	} else {
		fmt.Fprintf(source, "\trouteMux := %s\n", muxVariable)
	}
	source.WriteString("\tapplication.handler = routeMux\n")
	for _, item := range controllers {
		receiver := providerVariables[item.ProviderID]
		for _, route := range item.Routes() {
			pattern := route.HTTPMethod + " " + route.Path
			if route.Raw {
				fmt.Fprintf(
					source,
					"\tif routeErr := spiceweb.Register(routeMux, %s, http.HandlerFunc(%s.%s)); routeErr != nil {\n",
					strconv.Quote(pattern),
					receiver,
					route.Name,
				)
				writeRouteRegistrationError(source, pattern)
				continue
			}
			writeTypedRoute(source, route, receiver, pattern, aliases)
		}
	}
}

func writeTypedRoute(
	source *bytes.Buffer,
	route controller.Route,
	receiver string,
	pattern string,
	aliases map[string]string,
) {
	fmt.Fprintf(
		source,
		"\tif routeErr := spiceweb.Register(routeMux, %s, http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {\n",
		strconv.Quote(pattern),
	)
	if !route.NoContent {
		source.WriteString("\t\tif !spiceweb.AcceptsJSON(httpRequest.Header.Get(\"Accept\")) {\n")
		source.WriteString("\t\t\tproblem := spiceweb.Problem{\n")
		source.WriteString("\t\t\t\tType: \"about:blank\",\n")
		source.WriteString("\t\t\t\tTitle: \"Not Acceptable\",\n")
		source.WriteString("\t\t\t\tStatus: http.StatusNotAcceptable,\n")
		source.WriteString("\t\t\t\tDetail: \"the endpoint produces application/json\",\n")
		source.WriteString("\t\t\t}\n")
		source.WriteString("\t\t\tif writeErr := spiceweb.WriteProblem(writer, problem); writeErr != nil {\n")
		source.WriteString("\t\t\t\treturn\n")
		source.WriteString("\t\t\t}\n")
		source.WriteString("\t\t\treturn\n")
		source.WriteString("\t\t}\n")
	}
	fmt.Fprintf(source, "\t\trequestValue := %s{}\n", renderedType(route.Request, aliases))
	for _, binding := range route.Bindings() {
		writeRequestBinding(source, binding, aliases)
	}
	if route.ValidatorID != "" {
		source.WriteString("\t\tif validationErr := spiceweb.Validate(httpRequest.Context(), requestValue.Validate); validationErr != nil {\n")
		writeGeneratedError(source, "validationErr", 3)
		source.WriteString("\t\t\treturn\n")
		source.WriteString("\t\t}\n")
	}
	if route.NoContent {
		fmt.Fprintf(
			source,
			"\t\t_, routeErr := %s.%s(httpRequest.Context(), requestValue)\n",
			receiver,
			route.Name,
		)
	} else {
		fmt.Fprintf(
			source,
			"\t\tresponseValue, routeErr := %s.%s(httpRequest.Context(), requestValue)\n",
			receiver,
			route.Name,
		)
	}
	source.WriteString("\t\tif routeErr != nil {\n")
	writeGeneratedError(source, "routeErr", 3)
	source.WriteString("\t\t\treturn\n")
	source.WriteString("\t\t}\n")
	if route.NoContent {
		source.WriteString("\t\tif writeErr := spiceweb.WriteNoContent(writer); writeErr != nil {\n")
	} else {
		source.WriteString("\t\tif writeErr := spiceweb.WriteJSON(writer, http.StatusOK, responseValue); writeErr != nil {\n")
	}
	source.WriteString("\t\t\treturn\n")
	source.WriteString("\t\t}\n")
	source.WriteString("\t})); routeErr != nil {\n")
	writeRouteRegistrationError(source, pattern)
}

func writeRouteRegistrationError(source *bytes.Buffer, pattern string) {
	fmt.Fprintf(
		source,
		"\t\treturn nil, application.coordinator.Abort(ctx, fmt.Errorf(%s, routeErr))\n",
		strconv.Quote("register generated route "+pattern+": %w"),
	)
	source.WriteString("\t}\n")
}

func writeRequestBinding(source *bytes.Buffer, binding controller.Binding, aliases map[string]string) {
	if binding.Location == controller.Body {
		fmt.Fprintf(
			source,
			"\t\tif bindErr := spiceweb.DecodeJSON(httpRequest, &requestValue.%s, options.MaxRequestBodyBytes); bindErr != nil {\n",
			binding.Field,
		)
		writeGeneratedError(source, "bindErr", 3)
		source.WriteString("\t\t\treturn\n")
		source.WriteString("\t\t}\n")
		return
	}
	index := strconv.Itoa(binding.Index)
	values := bindingValues(binding)
	fmt.Fprintf(
		source,
		"\t\traw%s, present%s, bindErr%s := spiceweb.Parameter(%s, %s, %s, %t)\n",
		index,
		index,
		index,
		bindingLocation(binding.Location),
		strconv.Quote(binding.Name),
		values,
		binding.Required,
	)
	fmt.Fprintf(source, "\t\tif bindErr%s != nil {\n", index)
	writeGeneratedError(source, "bindErr"+index, 3)
	source.WriteString("\t\t\treturn\n")
	source.WriteString("\t\t}\n")
	fmt.Fprintf(source, "\t\tif present%s {\n", index)
	writeScalarAssignment(source, binding, index, aliases)
	source.WriteString("\t\t}\n")
}

func writeScalarAssignment(
	source *bytes.Buffer,
	binding controller.Binding,
	index string,
	aliases map[string]string,
) {
	typeName := renderedType(binding.Type, aliases)
	if binding.Kind == controller.ScalarString {
		fmt.Fprintf(source, "\t\t\trequestValue.%s = %s(raw%s)\n", binding.Field, typeName, index)
		return
	}
	accessor := "Boolean"
	extra := ""
	if binding.Kind == controller.ScalarInteger {
		accessor = "Integer"
		extra = ", " + strconv.Itoa(integerBitSize(binding.Type))
	}
	if binding.Kind == controller.ScalarDuration {
		accessor = "Duration"
	}
	fmt.Fprintf(
		source,
		"\t\t\tparsed%s, parseErr%s := spiceweb.%s(%s, %s, raw%s%s)\n",
		index,
		index,
		accessor,
		bindingLocation(binding.Location),
		strconv.Quote(binding.Name),
		index,
		extra,
	)
	fmt.Fprintf(source, "\t\t\tif parseErr%s != nil {\n", index)
	writeGeneratedError(source, "parseErr"+index, 4)
	source.WriteString("\t\t\t\treturn\n")
	source.WriteString("\t\t\t}\n")
	fmt.Fprintf(source, "\t\t\trequestValue.%s = %s(parsed%s)\n", binding.Field, typeName, index)
}

func writeGeneratedError(source *bytes.Buffer, variable string, tabs int) {
	indent := strings.Repeat("\t", tabs)
	fmt.Fprintf(
		source,
		"%sif writeErr := spiceweb.WriteError(writer, httpRequest, %s, options.ErrorMapper); writeErr != nil {\n",
		indent,
		variable,
	)
	fmt.Fprintf(source, "%s\treturn\n", indent)
	fmt.Fprintf(source, "%s}\n", indent)
}

func bindingValues(binding controller.Binding) string {
	switch binding.Location {
	case controller.Path:
		return "[]string{httpRequest.PathValue(" + strconv.Quote(binding.Name) + ")}"
	case controller.Query:
		return "httpRequest.URL.Query()[" + strconv.Quote(binding.Name) + "]"
	case controller.Header:
		return "httpRequest.Header.Values(" + strconv.Quote(binding.Name) + ")"
	case controller.Body:
		return "nil"
	}
	return "nil"
}

func bindingLocation(location controller.Location) string {
	switch location {
	case controller.Path:
		return "spiceweb.LocationPath"
	case controller.Query:
		return "spiceweb.LocationQuery"
	case controller.Header:
		return "spiceweb.LocationHeader"
	case controller.Body:
		return "spiceweb.LocationBody"
	}
	return "spiceweb.LocationQuery"
}

func integerBitSize(value types.Type) int {
	basic, ok := types.Unalias(value).Underlying().(*types.Basic)
	if !ok {
		return 0
	}
	if basic.Kind() == types.Int8 {
		return 8
	}
	if basic.Kind() == types.Int16 {
		return 16
	}
	if basic.Kind() == types.Int32 {
		return 32
	}
	if basic.Kind() == types.Int64 {
		return 64
	}
	return 0
}

func pointerNamedType(value types.Type, packagePath, name string) bool {
	pointer, ok := types.Unalias(value).(*types.Pointer)
	if !ok {
		return false
	}
	named, ok := types.Unalias(pointer.Elem()).(*types.Named)
	return ok && named.Obj() != nil && named.Obj().Pkg() != nil &&
		named.Obj().Pkg().Path() == packagePath && named.Obj().Name() == name
}

func writeApplicationOptions(source *bytes.Buffer, hasConfiguration, hasControllers bool) {
	source.WriteString("type ApplicationOptions struct {\n")
	if hasConfiguration {
		source.WriteString("\tProfiles []string\n")
		source.WriteString("\tSources []spiceconfig.Source\n")
		source.WriteString("\tAllowUnknownConfiguration bool\n")
	}
	if hasControllers {
		source.WriteString("\tErrorMapper spiceweb.ErrorMapper\n")
		source.WriteString("\tMaxRequestBodyBytes int64\n")
	}
	source.WriteString("\tObservers []spicelifecycle.Observer\n")
	source.WriteString("}\n\n")
}

func writeConfigurationAPI(source *bytes.Buffer, configTypes []configuration.Type) {
	source.WriteString("func ConfigurationSchema() (spiceconfig.Schema, error) {\n")
	source.WriteString("\treturn spiceconfig.NewSchema(\n")
	for _, configType := range configTypes {
		for _, field := range configType.Fields() {
			source.WriteString("\t\tspiceconfig.Property{\n")
			fmt.Fprintf(source, "\t\t\tKey: %s,\n", strconv.Quote(field.Key))
			fmt.Fprintf(source, "\t\t\tKind: %s,\n", configurationKindName(field.Kind))
			if field.Module != "" {
				fmt.Fprintf(source, "\t\t\tModule: %s,\n", strconv.Quote(field.Module))
			}
			if field.Environment != "" {
				fmt.Fprintf(source, "\t\t\tEnvironment: %s,\n", strconv.Quote(field.Environment))
			}
			if field.HasDefault {
				fmt.Fprintf(source, "\t\t\tDefault: %s,\n", strconv.Quote(field.Default))
				source.WriteString("\t\t\tHasDefault: true,\n")
			}
			if field.Required {
				source.WriteString("\t\t\tRequired: true,\n")
			}
			if field.Secret {
				source.WriteString("\t\t\tSecret: true,\n")
			}
			source.WriteString("\t\t},\n")
		}
	}
	source.WriteString("\t)\n")
	source.WriteString("}\n\n")
}

func configurationKindName(kind runtimeconfig.Kind) string {
	switch kind {
	case runtimeconfig.KindString:
		return "spiceconfig.KindString"
	case runtimeconfig.KindBoolean:
		return "spiceconfig.KindBoolean"
	case runtimeconfig.KindInteger:
		return "spiceconfig.KindInteger"
	case runtimeconfig.KindDuration:
		return "spiceconfig.KindDuration"
	default:
		return strconv.Quote(string(kind))
	}
}

func writeConfigurationResolution(source *bytes.Buffer, target Target) {
	source.WriteString("\tconfigurationSchema, err := ConfigurationSchema()\n")
	source.WriteString("\tif err != nil {\n")
	fmt.Fprintf(
		source,
		"\t\treturn nil, fmt.Errorf(%s, err)\n",
		strconv.Quote("construct configuration schema for application "+target.ID+": %w"),
	)
	source.WriteString("\t}\n")
	source.WriteString("\tconfigurationSnapshot, err := spiceconfig.Resolve(\n")
	source.WriteString("\t\tctx,\n")
	source.WriteString("\t\tconfigurationSchema,\n")
	source.WriteString("\t\tspiceconfig.Options{\n")
	source.WriteString("\t\t\tProfiles: options.Profiles,\n")
	source.WriteString("\t\t\tAllowUnknown: options.AllowUnknownConfiguration,\n")
	source.WriteString("\t\t},\n")
	source.WriteString("\t\toptions.Sources...,\n")
	source.WriteString("\t)\n")
	source.WriteString("\tif err != nil {\n")
	fmt.Fprintf(
		source,
		"\t\treturn nil, fmt.Errorf(%s, err)\n",
		strconv.Quote("resolve configuration for application "+target.ID+": %w"),
	)
	source.WriteString("\t}\n")
	source.WriteString("\t_ = configurationSnapshot\n")
}

func writeConfigurationBinder(
	source *bytes.Buffer,
	configType configuration.Type,
	index int,
	aliases map[string]string,
) {
	variable := providerVariable(index)
	fmt.Fprintf(source, "\t%s := %s{}\n", variable, renderedType(configType.Type, aliases))
	for _, field := range configType.Fields() {
		source.WriteString("\tif _, configured := configurationSnapshot.Lookup(")
		source.WriteString(strconv.Quote(field.Key))
		source.WriteString("); configured {\n")
		fmt.Fprintf(
			source,
			"\t\trawValue, valueErr := configurationSnapshot.%s(%s)\n",
			configurationAccessor(field.Kind),
			strconv.Quote(field.Key),
		)
		source.WriteString("\t\tif valueErr != nil {\n")
		fmt.Fprintf(
			source,
			"\t\t\treturn nil, application.coordinator.Abort(ctx, fmt.Errorf(%s, valueErr))\n",
			strconv.Quote(
				"decode configuration property "+field.Key+" for "+
					configType.TypeID+"."+field.Name+": %w",
			),
		)
		source.WriteString("\t\t}\n")
		fmt.Fprintf(
			source,
			"\t\tconvertedValue := %s(rawValue)\n",
			renderedType(field.Type, aliases),
		)
		if field.Kind == runtimeconfig.KindInteger {
			source.WriteString("\t\tif int64(convertedValue) != rawValue {\n")
			fmt.Fprintf(
				source,
				"\t\t\treturn nil, application.coordinator.Abort(ctx, fmt.Errorf(%s))\n",
				strconv.Quote(
					"decode configuration property "+field.Key+" for "+
						configType.TypeID+"."+field.Name+": value is outside "+field.TypeID,
				),
			)
			source.WriteString("\t\t}\n")
		}
		fmt.Fprintf(source, "\t\t%s.%s = convertedValue\n", variable, field.Name)
		source.WriteString("\t}\n")
	}
	fmt.Fprintf(source, "\t_ = %s\n", variable)
}

func configurationAccessor(kind runtimeconfig.Kind) string {
	switch kind {
	case runtimeconfig.KindString:
		return "RequiredString"
	case runtimeconfig.KindBoolean:
		return "Boolean"
	case runtimeconfig.KindInteger:
		return "Integer"
	case runtimeconfig.KindDuration:
		return "Duration"
	default:
		return "RequiredString"
	}
}

func configurationProviderIndex(configTypes []configuration.Type) map[string]configuration.Type {
	result := make(map[string]configuration.Type, len(configTypes))
	for _, configType := range configTypes {
		result[configType.SymbolID] = configType
	}
	return result
}

func renderedType(value types.Type, aliases map[string]string) string {
	return types.TypeString(value, func(pkg *types.Package) string {
		if pkg == nil {
			return ""
		}
		if alias, ok := aliases[pkg.Path()]; ok {
			return alias
		}
		return pkg.Name()
	})
}

func writeImports(source *bytes.Buffer, aliases map[string]string) {
	var standardPaths, applicationPaths []string
	for importPath := range aliases {
		if isStandardImport(importPath) {
			standardPaths = append(standardPaths, importPath)
		} else {
			applicationPaths = append(applicationPaths, importPath)
		}
	}
	sort.Strings(standardPaths)
	sort.Strings(applicationPaths)
	source.WriteString("import (\n")
	writeImportGroup(source, aliases, standardPaths)
	if len(standardPaths) != 0 && len(applicationPaths) != 0 {
		source.WriteByte('\n')
	}
	writeImportGroup(source, aliases, applicationPaths)
	source.WriteString(")\n\n")
}

func isStandardImport(importPath string) bool {
	first, _, _ := strings.Cut(importPath, "/")
	return !strings.Contains(first, ".")
}

func writeImportGroup(source *bytes.Buffer, aliases map[string]string, paths []string) {
	for _, importPath := range paths {
		fmt.Fprintf(source, "\t%s %s\n", aliases[importPath], strconv.Quote(importPath))
	}
}

func writeProviderCall(
	source *bytes.Buffer,
	item provider.Provider,
	index int,
	aliases map[string]string,
	dependencies []string,
	moduleID string,
) {
	variable := providerVariable(index)
	cleanup := fmt.Sprintf("cleanup%d", index)
	call := aliases[item.PackagePath] + "." + item.Name + "(" + strings.Join(dependencies, ", ") + ")"
	switch {
	case item.ReturnsCleanup && item.ReturnsError:
		fmt.Fprintf(source, "\t%s, %s, err := %s\n", variable, cleanup, call)
	case item.ReturnsCleanup:
		fmt.Fprintf(source, "\t%s, %s := %s\n", variable, cleanup, call)
	case item.ReturnsError:
		fmt.Fprintf(source, "\t%s, err := %s\n", variable, call)
	default:
		fmt.Fprintf(source, "\t%s := %s\n", variable, call)
	}
	if item.ReturnsError {
		source.WriteString("\tif err != nil {\n")
		fmt.Fprintf(
			source,
			"\t\treturn nil, application.coordinator.Abort(ctx, fmt.Errorf(%s, err))\n",
			strconv.Quote("construct provider "+item.SymbolID+" ("+item.OutputTypeID+"): %w"),
		)
		source.WriteString("\t}\n")
	}
	if item.ReturnsCleanup {
		fmt.Fprintf(
			source,
			"\tif err := application.coordinator.RegisterModuleCleanup(%s, %s, %s); err != nil {\n",
			strconv.Quote(moduleID),
			strconv.Quote(item.SymbolID),
			cleanup,
		)
		fmt.Fprintf(
			source,
			"\t\treturn nil, application.coordinator.Abort(ctx, fmt.Errorf(%s, err))\n",
			strconv.Quote("register cleanup for provider "+item.SymbolID+": %w"),
		)
		source.WriteString("\t}\n")
	}
	fmt.Fprintf(source, "\t_ = %s\n", variable)
}

func writeHooks(
	source *bytes.Buffer,
	model application.Model,
	providerVariables map[string]string,
	providerModules map[string]string,
) {
	components := model.Components()
	if len(components) == 0 {
		return
	}
	source.WriteString("\tapplication.hooks = []spicelifecycle.Hook{\n")
	for _, component := range components {
		variable := providerVariables[component.Provider.SymbolID]
		source.WriteString("\t\t{\n")
		fmt.Fprintf(source, "\t\t\tID: %s,\n", strconv.Quote(component.Provider.SymbolID))
		fmt.Fprintf(
			source,
			"\t\t\tModule: %s,\n",
			strconv.Quote(providerModules[component.Provider.SymbolID]),
		)
		fmt.Fprintf(source, "\t\t\tStart: %s.%s,\n", variable, component.Start.Method.Name)
		if component.Stop != nil {
			fmt.Fprintf(source, "\t\t\tStop: %s.%s,\n", variable, component.Stop.Method.Name)
		}
		source.WriteString("\t\t},\n")
	}
	source.WriteString("\t}\n")
}

func writeLifecycleMethods(source *bytes.Buffer) {
	source.WriteString(`func (application *Application) State() spicelifecycle.State {
	if application == nil || application.coordinator == nil {
		return spicelifecycle.StateInvalid
	}
	return application.coordinator.State()
}

func (application *Application) Start(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("start application: application is nil")
	}
	return application.coordinator.Start(ctx, application.hooks)
}

func (application *Application) Stop(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("stop application: application is nil")
	}
	return application.coordinator.Stop(ctx)
}

func (application *Application) RegisterObserver(observer spicelifecycle.Observer) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("register lifecycle observer: application is nil")
	}
	return application.coordinator.RegisterObserver(observer)
}

func (application *Application) Run(ctx context.Context, shutdown spicelifecycle.ContextFactory) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("run application: application is nil")
	}
	return application.coordinator.Run(ctx, application.hooks, shutdown)
}
`)
}

func writeHandlerMethod(source *bytes.Buffer) {
	source.WriteString(`
func (application *Application) Handler() http.Handler {
	if application == nil {
		return nil
	}
	return application.handler
}
`)
}

func providerModuleIDs(
	model application.Model,
	providers []provider.Provider,
) map[string]string {
	packageModules := make(map[string]string)
	for _, module := range model.Modules() {
		for _, pkg := range module.Packages() {
			packageModules[pkg.Path] = module.ID
		}
	}
	result := make(map[string]string, len(providers))
	for _, item := range providers {
		result[item.SymbolID] = packageModules[item.PackagePath]
	}
	return result
}

func importAliases(
	providers []provider.Provider,
	configTypes []configuration.Type,
	controllers []controller.Controller,
) map[string]string {
	aliases := map[string]string{
		"context":     "context",
		"fmt":         "fmt",
		lifecyclePath: "spicelifecycle",
	}
	if len(configTypes) != 0 {
		aliases[configPath] = "spiceconfig"
	}
	if len(controllers) != 0 {
		aliases["net/http"] = "http"
		aliases[webPath] = "spiceweb"
	}
	used := map[string]struct{}{
		"Application":               {},
		"ApplicationOptions":        {},
		"ConfigurationSchema":       {},
		"NewApplication":            {},
		"NewApplicationWithOptions": {},
		"TargetID":                  {},
		"context":                   {},
		"fmt":                       {},
		"http":                      {},
		"spiceconfig":               {},
		"spicelifecycle":            {},
		"spiceweb":                  {},
	}
	names := importNames(providers, configTypes, controllers, aliases)
	paths := make([]string, 0, len(names))
	for importPath := range names {
		paths = append(paths, importPath)
	}
	sort.Strings(paths)
	for _, importPath := range paths {
		base := names[importPath]
		alias := base
		for suffix := 2; ; suffix++ {
			if _, exists := used[alias]; !exists {
				break
			}
			alias = base + strconv.Itoa(suffix)
		}
		used[alias] = struct{}{}
		aliases[importPath] = alias
	}
	return aliases
}

func importNames(
	providers []provider.Provider,
	configTypes []configuration.Type,
	controllers []controller.Controller,
	aliases map[string]string,
) map[string]string {
	names := make(map[string]string)
	for _, item := range providers {
		if _, fixed := aliases[item.PackagePath]; fixed {
			continue
		}
		name := "provider"
		if item.Symbol.Object != nil && item.Symbol.Object.Pkg() != nil {
			name = item.Symbol.Object.Pkg().Name()
		}
		names[item.PackagePath] = name
	}
	for _, configType := range configTypes {
		for _, field := range configType.Fields() {
			addTypeImportName(names, aliases, field.Type)
		}
	}
	for _, item := range controllers {
		for _, route := range item.Routes() {
			for _, binding := range route.Bindings() {
				addTypeImportName(names, aliases, binding.Type)
			}
		}
	}
	return names
}

func addTypeImportName(names, aliases map[string]string, value types.Type) {
	var object *types.TypeName
	switch typed := value.(type) {
	case *types.Named:
		object = typed.Obj()
	case *types.Alias:
		object = typed.Obj()
	default:
		return
	}
	if object == nil || object.Pkg() == nil {
		return
	}
	importPath := object.Pkg().Path()
	if _, fixed := aliases[importPath]; fixed {
		return
	}
	names[importPath] = object.Pkg().Name()
}

func dependencyVariables(
	model application.Model,
	providers []provider.Provider,
) (map[string][]string, error) {
	edges := make(map[string]string)
	for _, edge := range model.Edges() {
		key := dependencyKey(edge.ConsumerID, edge.ParameterIndex)
		edges[key] = edge.DependencyID
	}
	variables := make(map[string]string, len(providers))
	for index, item := range providers {
		variables[item.SymbolID] = providerVariable(index)
	}
	result := make(map[string][]string, len(providers))
	for _, item := range providers {
		inputs := make([]string, len(item.Dependencies))
		for _, dependency := range item.Dependencies {
			dependencyID, ok := edges[dependencyKey(item.SymbolID, dependency.Index)]
			if !ok {
				return nil, fmt.Errorf(
					"provider %s parameter %d has no validated graph edge",
					item.SymbolID,
					dependency.Index,
				)
			}
			variable, ok := variables[dependencyID]
			if !ok {
				return nil, fmt.Errorf(
					"provider %s parameter %d references unknown provider %s",
					item.SymbolID,
					dependency.Index,
					dependencyID,
				)
			}
			inputs[dependency.Index] = variable
		}
		result[item.SymbolID] = inputs
	}
	return result, nil
}

func validateTarget(target Target, applicationTarget application.Target) []Diagnostic {
	var diagnostics []Diagnostic
	add := func(kind, message string) {
		diagnostics = append(diagnostics, targetDiagnostic(applicationTarget, kind, message))
	}
	if !targetIDPattern.MatchString(target.ID) {
		add("target-id", fmt.Sprintf("generation target ID %q must match %s", target.ID, targetIDPattern))
	}
	if target.ModulePath == "" {
		add("module-path", "generation target module path is required")
	}
	if target.ModuleRoot == "" {
		add("module-root", "generation target module root is required")
	}
	if target.PackagePath == "" {
		add("package-path", "generated package import path is required")
	}
	if target.OutputDir == "" {
		add("output-dir", "generated output directory is required")
	}
	if target.ManifestPath == "" {
		add("manifest-path", "generated manifest path is required")
	}
	sortDiagnostics(diagnostics)
	return diagnostics
}

func validateRenderable(
	program *load.Program,
	model application.Model,
	applicationTarget application.Target,
	target Target,
) []Diagnostic {
	var diagnostics []Diagnostic
	packages := program.Packages()
	sourcePackage, ok := packageByPath(packages, applicationTarget.PackagePath)
	if ok && sourcePackage.Types != nil {
		for _, imported := range sourcePackage.Types.Imports() {
			if imported.Path() == target.PackagePath {
				diagnostics = append(diagnostics, targetDiagnostic(
					applicationTarget,
					"import-cycle",
					fmt.Sprintf(
						"application package %s imports generated package %s; generated output must be imported only by an outer command package",
						sourcePackage.Path,
						target.PackagePath,
					),
				))
			}
		}
	}
	packageNames := make(map[string]string, len(packages))
	for _, pkg := range packages {
		packageNames[pkg.Path] = pkg.Name
	}
	for _, item := range model.Providers() {
		switch {
		case item.PackagePath == target.PackagePath:
			diagnostics = append(diagnostics, providerRenderDiagnostic(
				applicationTarget,
				item,
				"self-import",
				fmt.Sprintf("provider %s is declared in generated package %s", item.SymbolID, target.PackagePath),
			))
		case packageNames[item.PackagePath] == "main":
			diagnostics = append(diagnostics, providerRenderDiagnostic(
				applicationTarget,
				item,
				"main-package",
				fmt.Sprintf(
					"provider %s is declared in package main, which generated package %s cannot import; move providers into an importable package",
					item.SymbolID,
					target.PackagePath,
				),
			))
		case !token.IsExported(item.Name):
			diagnostics = append(diagnostics, providerRenderDiagnostic(
				applicationTarget,
				item,
				"unexported-provider",
				fmt.Sprintf(
					"provider %s is unexported; target-scoped generated packages require exported @Bean functions",
					item.SymbolID,
				),
			))
		}
	}
	for _, component := range model.Components() {
		methods := []load.Symbol{component.Start.Method}
		if component.Stop != nil {
			methods = append(methods, component.Stop.Method)
		}
		for _, method := range methods {
			if token.IsExported(method.Name) {
				continue
			}
			diagnostics = append(diagnostics, Diagnostic{
				Position:         method.Position,
				PhysicalPosition: method.PhysicalPosition,
				TargetID:         applicationTarget.SymbolID,
				Kind:             "unexported-hook",
				Message: fmt.Sprintf(
					"lifecycle method %s is unexported; target-scoped generated packages require exported hook methods",
					method.ID,
				),
			})
		}
	}
	sortDiagnostics(diagnostics)
	return diagnostics
}

func modelHash(
	model application.Model,
	applicationTarget application.Target,
	target Target,
) (string, error) {
	type inputDependency struct {
		Index int    `json:"index"`
		Type  string `json:"type"`
	}
	type inputProvider struct {
		ID      string            `json:"id"`
		Source  provider.Source   `json:"source"`
		Module  string            `json:"module,omitempty"`
		Output  string            `json:"output"`
		Cleanup bool              `json:"cleanup"`
		Error   bool              `json:"error"`
		Inputs  []inputDependency `json:"inputs"`
	}
	type inputEdge struct {
		Consumer  string `json:"consumer"`
		Parameter int    `json:"parameter"`
		Provider  string `json:"provider"`
	}
	type inputComponent struct {
		Provider string `json:"provider"`
		Start    string `json:"start"`
		Stop     string `json:"stop,omitempty"`
	}
	type inputRoot struct {
		Index    int    `json:"index"`
		Type     string `json:"type"`
		Provider string `json:"provider"`
	}
	type inputConfigurationField struct {
		Index       int                `json:"index"`
		Name        string             `json:"name"`
		Type        string             `json:"type"`
		Key         string             `json:"key"`
		Kind        runtimeconfig.Kind `json:"kind"`
		Module      string             `json:"module,omitempty"`
		Environment string             `json:"environment,omitempty"`
		Default     string             `json:"default,omitempty"`
		HasDefault  bool               `json:"has_default,omitempty"`
		Required    bool               `json:"required,omitempty"`
		Secret      bool               `json:"secret,omitempty"`
	}
	type inputConfiguration struct {
		ID     string                    `json:"id"`
		Type   string                    `json:"type"`
		Prefix string                    `json:"prefix,omitempty"`
		Module string                    `json:"module,omitempty"`
		Fields []inputConfigurationField `json:"fields"`
	}
	type inputBinding struct {
		Index    int                   `json:"index"`
		Field    string                `json:"field"`
		Name     string                `json:"name,omitempty"`
		Location controller.Location   `json:"location"`
		Required bool                  `json:"required"`
		Kind     controller.ScalarKind `json:"kind,omitempty"`
		Type     string                `json:"type"`
	}
	type inputRoute struct {
		ID        string         `json:"id"`
		Method    string         `json:"method"`
		Path      string         `json:"path"`
		Provider  string         `json:"provider"`
		Request   string         `json:"request,omitempty"`
		Response  string         `json:"response,omitempty"`
		Validator string         `json:"validator,omitempty"`
		Raw       bool           `json:"raw,omitempty"`
		NoContent bool           `json:"no_content,omitempty"`
		Bindings  []inputBinding `json:"bindings"`
	}
	type inputController struct {
		ID       string       `json:"id"`
		Module   string       `json:"module,omitempty"`
		Provider string       `json:"provider"`
		Prefix   string       `json:"prefix,omitempty"`
		Routes   []inputRoute `json:"routes"`
	}
	type input struct {
		Schema         int                  `json:"schema"`
		Target         TargetSummary        `json:"target"`
		Symbol         string               `json:"symbol"`
		Providers      []inputProvider      `json:"providers"`
		Configurations []inputConfiguration `json:"configurations"`
		Controllers    []inputController    `json:"controllers"`
		Edges          []inputEdge          `json:"edges"`
		Components     []inputComponent     `json:"components"`
		Roots          []inputRoot          `json:"roots"`
	}
	value := input{
		Schema: SchemaVersion,
		Target: summarizeTarget(target),
		Symbol: applicationTarget.SymbolID,
	}
	providers := model.Providers()
	providerModules := providerModuleIDs(model, providers)
	for _, item := range providers {
		inputs := make([]inputDependency, len(item.Dependencies))
		for index, dependency := range item.Dependencies {
			inputs[index] = inputDependency{Index: dependency.Index, Type: dependency.TypeID}
		}
		value.Providers = append(value.Providers, inputProvider{
			ID:      item.SymbolID,
			Source:  item.Source,
			Module:  providerModules[item.SymbolID],
			Output:  item.OutputTypeID,
			Cleanup: item.ReturnsCleanup,
			Error:   item.ReturnsError,
			Inputs:  inputs,
		})
	}
	for _, configType := range model.Configurations() {
		item := inputConfiguration{
			ID:     configType.SymbolID,
			Type:   configType.TypeID,
			Prefix: configType.Prefix,
			Module: configType.Module,
		}
		for _, field := range configType.Fields() {
			item.Fields = append(item.Fields, inputConfigurationField{
				Index:       field.Index,
				Name:        field.Name,
				Type:        field.TypeID,
				Key:         field.Key,
				Kind:        field.Kind,
				Module:      field.Module,
				Environment: field.Environment,
				Default:     field.Default,
				HasDefault:  field.HasDefault,
				Required:    field.Required,
				Secret:      field.Secret,
			})
		}
		value.Configurations = append(value.Configurations, item)
	}
	for _, item := range model.Controllers() {
		inputItem := inputController{
			ID:       item.SymbolID,
			Module:   item.Module,
			Provider: item.ProviderID,
			Prefix:   item.Prefix,
		}
		for _, route := range item.Routes() {
			routeInput := inputRoute{
				ID:        route.SymbolID,
				Method:    route.HTTPMethod,
				Path:      route.Path,
				Provider:  route.ProviderID,
				Request:   route.RequestTypeID,
				Response:  route.ResponseTypeID,
				Validator: route.ValidatorID,
				Raw:       route.Raw,
				NoContent: route.NoContent,
			}
			for _, binding := range route.Bindings() {
				routeInput.Bindings = append(routeInput.Bindings, inputBinding{
					Index:    binding.Index,
					Field:    binding.Field,
					Name:     binding.Name,
					Location: binding.Location,
					Required: binding.Required,
					Kind:     binding.Kind,
					Type:     binding.TypeID,
				})
			}
			inputItem.Routes = append(inputItem.Routes, routeInput)
		}
		value.Controllers = append(value.Controllers, inputItem)
	}
	for _, edge := range model.Edges() {
		value.Edges = append(value.Edges, inputEdge{
			Consumer:  edge.ConsumerID,
			Parameter: edge.ParameterIndex,
			Provider:  edge.DependencyID,
		})
	}
	for _, component := range model.Components() {
		item := inputComponent{
			Provider: component.Provider.SymbolID,
			Start:    component.Start.MethodID,
		}
		if component.Stop != nil {
			item.Stop = component.Stop.MethodID
		}
		value.Components = append(value.Components, item)
	}
	for _, root := range applicationTarget.Roots() {
		value.Roots = append(value.Roots, inputRoot{
			Index:    root.Index,
			Type:     root.TypeID,
			Provider: root.ProviderID,
		})
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	return contentHash(encoded), nil
}

func contentHash(content []byte) string {
	digest := sha256.Sum256(content)
	return "sha256:" + hex.EncodeToString(digest[:])
}

func summarizeTarget(target Target) TargetSummary {
	return TargetSummary{
		ID:           target.ID,
		ModulePath:   target.ModulePath,
		PackagePath:  target.PackagePath,
		OutputDir:    target.OutputDir,
		ManifestPath: target.ManifestPath,
	}
}

func packageByPath(packages []load.Package, packagePath string) (load.Package, bool) {
	for _, pkg := range packages {
		if pkg.Path == packagePath {
			return pkg, true
		}
	}
	return load.Package{}, false
}

func containsTarget(targets []application.Target, symbolID string) bool {
	for _, target := range targets {
		if target.SymbolID == symbolID {
			return true
		}
	}
	return false
}

func providerVariable(index int) string {
	return "provider" + strconv.Itoa(index)
}

func dependencyKey(providerID string, parameter int) string {
	return providerID + "\x00" + strconv.Itoa(parameter)
}

func providerRenderDiagnostic(
	applicationTarget application.Target,
	item provider.Provider,
	kind string,
	message string,
) Diagnostic {
	return Diagnostic{
		Position:         item.Position,
		PhysicalPosition: item.PhysicalPosition,
		TargetID:         applicationTarget.SymbolID,
		Kind:             kind,
		Message:          message,
	}
}

func targetDiagnostic(target application.Target, kind, message string) Diagnostic {
	return Diagnostic{
		Position:         target.Position,
		PhysicalPosition: target.PhysicalPosition,
		TargetID:         target.SymbolID,
		Kind:             kind,
		Message:          message,
	}
}

func sortDiagnostics(diagnostics []Diagnostic) {
	sort.SliceStable(diagnostics, func(i, j int) bool {
		left, right := diagnostics[i], diagnostics[j]
		if left.PhysicalPosition.Filename != right.PhysicalPosition.Filename {
			return left.PhysicalPosition.Filename < right.PhysicalPosition.Filename
		}
		if left.PhysicalPosition.Offset != right.PhysicalPosition.Offset {
			return left.PhysicalPosition.Offset < right.PhysicalPosition.Offset
		}
		if left.TargetID != right.TargetID {
			return left.TargetID < right.TargetID
		}
		if left.Kind != right.Kind {
			return left.Kind < right.Kind
		}
		return left.Message < right.Message
	})
}
