// Package generate renders deterministic generated application plans from one
// validated Spice application model. It performs no filesystem writes.
package generate

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"go/token"
	"io/fs"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/StevenBuglione/spice/compiler/application"
	"github.com/StevenBuglione/spice/compiler/load"
	"github.com/StevenBuglione/spice/compiler/provider"
)

const (
	// SchemaVersion is the current generated ownership manifest schema.
	SchemaVersion = 1
	// GeneratorVersion is recorded in manifests to make generator compatibility
	// explicit during freshness checks.
	GeneratorVersion = "0.1.0-dev"
	// GoFormatLine is the supported Go formatter compatibility line.
	GoFormatLine = "1.26"
	// AnalysisBuildTag excludes committed generated packages while Spice
	// analyzes source, allowing stale output to be regenerated safely.
	AnalysisBuildTag = "spice_generate"

	generatedFilename = "zz_spice_gen.go"
	lifecyclePath     = "github.com/StevenBuglione/spice/lifecycle"
)

var targetIDPattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// Target identifies one module-scoped generated application output.
type Target struct {
	ID           string
	ModulePath   string
	ModuleRoot   string
	PackagePath  string
	OutputDir    string
	ManifestPath string
}

// TargetSummary is the safe, serializable subset of a generation target.
type TargetSummary struct {
	ID           string `json:"id"`
	ModulePath   string `json:"module"`
	PackagePath  string `json:"package"`
	OutputDir    string `json:"output_dir"`
	ManifestPath string `json:"manifest_path"`
}

// ManifestFile records one generated file owned by a target.
type ManifestFile struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

// Manifest is the deterministic generated-file ownership record.
type Manifest struct {
	Schema           int            `json:"schema"`
	Target           TargetSummary  `json:"target"`
	GeneratorVersion string         `json:"generator_version"`
	GoFormatLine     string         `json:"go_format_line"`
	InputSHA256      string         `json:"input_sha256"`
	Files            []ManifestFile `json:"files"`
}

// File is one generated file in a render plan.
type File struct {
	Path    string
	Mode    fs.FileMode
	SHA256  string
	content []byte
}

// Content returns a defensive copy of the generated bytes.
func (f File) Content() []byte {
	return append([]byte(nil), f.content...)
}

// Plan is a deterministic in-memory generation result.
type Plan struct {
	target          Target
	files           []File
	manifest        Manifest
	manifestContent []byte
}

// Target returns the plan's target.
func (p Plan) Target() Target {
	return p.target
}

// Files returns defensive copies sorted by module-relative path.
func (p Plan) Files() []File {
	result := make([]File, len(p.files))
	copy(result, p.files)
	for index := range result {
		result[index].content = append([]byte(nil), p.files[index].content...)
	}
	return result
}

// Manifest returns a defensive copy of the ownership manifest.
func (p Plan) Manifest() Manifest {
	result := p.manifest
	result.Files = append([]ManifestFile(nil), p.manifest.Files...)
	return result
}

// ManifestContent returns the exact canonical manifest bytes.
func (p Plan) ManifestContent() []byte {
	return append([]byte(nil), p.manifestContent...)
}

// Diagnostic is one deterministic generation failure.
type Diagnostic struct {
	Position         token.Position
	PhysicalPosition token.Position
	TargetID         string
	Kind             string
	Message          string
}

// Error renders a compiler-style diagnostic.
func (d Diagnostic) Error() string {
	position := d.Position
	if position.Filename == "" {
		position.Filename = "<generation>"
	}
	if position.Line <= 0 {
		position.Line = 1
	}
	if position.Column <= 0 {
		position.Column = 1
	}
	return fmt.Sprintf("%s:%d:%d: %s", position.Filename, position.Line, position.Column, d.Message)
}

// DefaultTarget derives the standard module-scoped output for one application
// marker: internal/spicegen/<lowercase-function-name> and
// .spice/<target>.manifest.json.
func DefaultTarget(program *load.Program, applicationTarget application.Target) (Target, []Diagnostic) {
	if program == nil {
		return Target{}, []Diagnostic{{
			Kind:    "invalid-program",
			Message: "derive generation target: loaded program is nil",
		}}
	}
	pkg, ok := packageByPath(program.Packages(), applicationTarget.PackagePath)
	if !ok || pkg.Raw == nil || pkg.Raw.Module == nil {
		return Target{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"module",
			fmt.Sprintf(
				"@Application target %s is not owned by a Go module; select a module-backed package",
				applicationTarget.SymbolID,
			),
		)}
	}
	id := strings.ToLower(applicationTarget.Name)
	outputDir := path.Join("internal", "spicegen", id)
	target := Target{
		ID:           id,
		ModulePath:   pkg.Raw.Module.Path,
		ModuleRoot:   pkg.Raw.Module.Dir,
		PackagePath:  path.Join(pkg.Raw.Module.Path, outputDir),
		OutputDir:    outputDir,
		ManifestPath: path.Join(".spice", id+".manifest.json"),
	}
	if diagnostics := validateTarget(target, applicationTarget); len(diagnostics) != 0 {
		return Target{}, diagnostics
	}
	return target, nil
}

// Render creates canonical generated Go and ownership manifest bytes entirely
// in memory. It consumes the application model's existing order and edges and
// never reloads packages, rebuilds dependency resolution, or executes source.
func Render(
	program *load.Program,
	model application.Model,
	applicationTarget application.Target,
	target Target,
) (Plan, []Diagnostic) {
	if program == nil {
		return Plan{}, []Diagnostic{{
			Kind:    "invalid-program",
			Message: "render application: loaded program is nil",
		}}
	}
	if diagnostics := model.Diagnostics(); len(diagnostics) != 0 {
		return Plan{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"invalid-model",
			fmt.Sprintf("render application: model has %d diagnostic(s)", len(diagnostics)),
		)}
	}
	if diagnostics := validateTarget(target, applicationTarget); len(diagnostics) != 0 {
		return Plan{}, diagnostics
	}
	if !containsTarget(model.Targets(), applicationTarget.SymbolID) {
		return Plan{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"unknown-target",
			fmt.Sprintf("application target %s is not present in the supplied model", applicationTarget.SymbolID),
		)}
	}
	if diagnostics := validateRenderable(program, model, applicationTarget, target); len(diagnostics) != 0 {
		return Plan{}, diagnostics
	}

	source, renderErr := renderSource(model, applicationTarget, target)
	if renderErr != nil {
		return Plan{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"render",
			fmt.Sprintf("render generated Go: %v", renderErr),
		)}
	}
	generatedPath := path.Join(target.OutputDir, generatedFilename)
	file := File{
		Path:    generatedPath,
		Mode:    0o644,
		SHA256:  contentHash(source),
		content: source,
	}
	inputHash, hashErr := modelHash(model, applicationTarget, target)
	if hashErr != nil {
		return Plan{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"input-hash",
			fmt.Sprintf("hash application model: %v", hashErr),
		)}
	}
	manifest := Manifest{
		Schema:           SchemaVersion,
		Target:           summarizeTarget(target),
		GeneratorVersion: GeneratorVersion,
		GoFormatLine:     GoFormatLine,
		InputSHA256:      inputHash,
		Files: []ManifestFile{{
			Path:   file.Path,
			SHA256: file.SHA256,
		}},
	}
	manifestContent, manifestErr := json.MarshalIndent(manifest, "", "  ")
	if manifestErr != nil {
		return Plan{}, []Diagnostic{targetDiagnostic(
			applicationTarget,
			"manifest",
			fmt.Sprintf("encode generation manifest: %v", manifestErr),
		)}
	}
	manifestContent = append(manifestContent, '\n')
	return Plan{
		target:          target,
		files:           []File{file},
		manifest:        manifest,
		manifestContent: manifestContent,
	}, nil
}

func renderSource(
	model application.Model,
	applicationTarget application.Target,
	target Target,
) ([]byte, error) {
	providers := model.Providers()
	aliases := importAliases(providers)
	providerModules := providerModuleIDs(model, providers)
	dependencies, err := dependencyVariables(model, providers)
	if err != nil {
		return nil, err
	}
	providerVariables := make(map[string]string, len(providers))
	for index, item := range providers {
		providerVariables[item.SymbolID] = providerVariable(index)
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by Spice. DO NOT EDIT.\n")
	source.WriteString("//go:build !" + AnalysisBuildTag + "\n\n")
	source.WriteString("package spicegen\n\n")
	writeImports(&source, aliases)
	fmt.Fprintf(&source, "const TargetID = %s\n\n", strconv.Quote(target.ID))
	source.WriteString("type Application struct {\n")
	source.WriteString("\tcoordinator *spicelifecycle.Coordinator\n")
	source.WriteString("\thooks []spicelifecycle.Hook\n")
	source.WriteString("}\n\n")
	source.WriteString("func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {\n")
	fmt.Fprintf(
		&source,
		"\tif ctx == nil {\n\t\treturn nil, fmt.Errorf(%s)\n\t}\n",
		strconv.Quote("construct application "+target.ID+": context is nil"),
	)
	source.WriteString("\tapplication := &Application{coordinator: spicelifecycle.NewCoordinator()}\n")
	source.WriteString("\tfor index, observer := range observers {\n")
	source.WriteString("\t\tif err := application.coordinator.RegisterObserver(observer); err != nil {\n")
	source.WriteString("\t\t\treturn nil, fmt.Errorf(\"register lifecycle observer %d: %w\", index, err)\n")
	source.WriteString("\t\t}\n")
	source.WriteString("\t}\n")
	for index, item := range providers {
		writeProviderCall(
			&source,
			item,
			index,
			aliases,
			dependencies[item.SymbolID],
			providerModules[item.SymbolID],
		)
	}
	writeHooks(&source, model, providerVariables, providerModules)
	source.WriteString("\treturn application, nil\n")
	source.WriteString("}\n\n")
	writeLifecycleMethods(&source)

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source for %s: %w", applicationTarget.SymbolID, err)
	}
	return formatted, nil
}

func writeImports(source *bytes.Buffer, aliases map[string]string) {
	var standardPaths, applicationPaths []string
	for importPath := range aliases {
		if importPath == "context" || importPath == "fmt" {
			standardPaths = append(standardPaths, importPath)
		} else {
			applicationPaths = append(applicationPaths, importPath)
		}
	}
	sort.Strings(standardPaths)
	sort.Strings(applicationPaths)
	source.WriteString("import (\n")
	writeImportGroup(source, aliases, standardPaths)
	if len(standardPaths) != 0 && len(applicationPaths) != 0 {
		source.WriteByte('\n')
	}
	writeImportGroup(source, aliases, applicationPaths)
	source.WriteString(")\n\n")
}

func writeImportGroup(source *bytes.Buffer, aliases map[string]string, paths []string) {
	for _, importPath := range paths {
		fmt.Fprintf(source, "\t%s %s\n", aliases[importPath], strconv.Quote(importPath))
	}
}

func writeProviderCall(
	source *bytes.Buffer,
	item provider.Provider,
	index int,
	aliases map[string]string,
	dependencies []string,
	moduleID string,
) {
	variable := providerVariable(index)
	cleanup := fmt.Sprintf("cleanup%d", index)
	call := aliases[item.PackagePath] + "." + item.Name + "(" + strings.Join(dependencies, ", ") + ")"
	switch {
	case item.ReturnsCleanup && item.ReturnsError:
		fmt.Fprintf(source, "\t%s, %s, err := %s\n", variable, cleanup, call)
	case item.ReturnsCleanup:
		fmt.Fprintf(source, "\t%s, %s := %s\n", variable, cleanup, call)
	case item.ReturnsError:
		fmt.Fprintf(source, "\t%s, err := %s\n", variable, call)
	default:
		fmt.Fprintf(source, "\t%s := %s\n", variable, call)
	}
	if item.ReturnsError {
		source.WriteString("\tif err != nil {\n")
		fmt.Fprintf(
			source,
			"\t\treturn nil, application.coordinator.Abort(ctx, fmt.Errorf(%s, err))\n",
			strconv.Quote("construct provider "+item.SymbolID+" ("+item.OutputTypeID+"): %w"),
		)
		source.WriteString("\t}\n")
	}
	if item.ReturnsCleanup {
		fmt.Fprintf(
			source,
			"\tif err := application.coordinator.RegisterModuleCleanup(%s, %s, %s); err != nil {\n",
			strconv.Quote(moduleID),
			strconv.Quote(item.SymbolID),
			cleanup,
		)
		fmt.Fprintf(
			source,
			"\t\treturn nil, application.coordinator.Abort(ctx, fmt.Errorf(%s, err))\n",
			strconv.Quote("register cleanup for provider "+item.SymbolID+": %w"),
		)
		source.WriteString("\t}\n")
	}
	fmt.Fprintf(source, "\t_ = %s\n", variable)
}

func writeHooks(
	source *bytes.Buffer,
	model application.Model,
	providerVariables map[string]string,
	providerModules map[string]string,
) {
	components := model.Components()
	if len(components) == 0 {
		return
	}
	source.WriteString("\tapplication.hooks = []spicelifecycle.Hook{\n")
	for _, component := range components {
		variable := providerVariables[component.Provider.SymbolID]
		source.WriteString("\t\t{\n")
		fmt.Fprintf(source, "\t\t\tID: %s,\n", strconv.Quote(component.Provider.SymbolID))
		fmt.Fprintf(
			source,
			"\t\t\tModule: %s,\n",
			strconv.Quote(providerModules[component.Provider.SymbolID]),
		)
		fmt.Fprintf(source, "\t\t\tStart: %s.%s,\n", variable, component.Start.Method.Name)
		if component.Stop != nil {
			fmt.Fprintf(source, "\t\t\tStop: %s.%s,\n", variable, component.Stop.Method.Name)
		}
		source.WriteString("\t\t},\n")
	}
	source.WriteString("\t}\n")
}

func writeLifecycleMethods(source *bytes.Buffer) {
	source.WriteString(`func (application *Application) State() spicelifecycle.State {
	if application == nil || application.coordinator == nil {
		return spicelifecycle.StateInvalid
	}
	return application.coordinator.State()
}

func (application *Application) Start(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("start application: application is nil")
	}
	return application.coordinator.Start(ctx, application.hooks)
}

func (application *Application) Stop(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("stop application: application is nil")
	}
	return application.coordinator.Stop(ctx)
}

func (application *Application) RegisterObserver(observer spicelifecycle.Observer) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("register lifecycle observer: application is nil")
	}
	return application.coordinator.RegisterObserver(observer)
}

func (application *Application) Run(ctx context.Context, shutdown spicelifecycle.ContextFactory) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("run application: application is nil")
	}
	return application.coordinator.Run(ctx, application.hooks, shutdown)
}
`)
}

func providerModuleIDs(
	model application.Model,
	providers []provider.Provider,
) map[string]string {
	packageModules := make(map[string]string)
	for _, module := range model.Modules() {
		for _, pkg := range module.Packages() {
			packageModules[pkg.Path] = module.ID
		}
	}
	result := make(map[string]string, len(providers))
	for _, item := range providers {
		result[item.SymbolID] = packageModules[item.PackagePath]
	}
	return result
}

func importAliases(providers []provider.Provider) map[string]string {
	aliases := map[string]string{
		"context":     "context",
		"fmt":         "fmt",
		lifecyclePath: "spicelifecycle",
	}
	used := map[string]struct{}{
		"Application":    {},
		"NewApplication": {},
		"TargetID":       {},
		"context":        {},
		"fmt":            {},
		"spicelifecycle": {},
	}
	names := make(map[string]string)
	for _, item := range providers {
		if _, fixed := aliases[item.PackagePath]; fixed {
			continue
		}
		name := "provider"
		if item.Symbol.Object != nil && item.Symbol.Object.Pkg() != nil {
			name = item.Symbol.Object.Pkg().Name()
		}
		names[item.PackagePath] = name
	}

	paths := make([]string, 0, len(names))
	for importPath := range names {
		paths = append(paths, importPath)
	}
	sort.Strings(paths)
	for _, importPath := range paths {
		base := names[importPath]
		alias := base
		for suffix := 2; ; suffix++ {
			if _, exists := used[alias]; !exists {
				break
			}
			alias = base + strconv.Itoa(suffix)
		}
		used[alias] = struct{}{}
		aliases[importPath] = alias
	}
	return aliases
}

func dependencyVariables(
	model application.Model,
	providers []provider.Provider,
) (map[string][]string, error) {
	edges := make(map[string]string)
	for _, edge := range model.Edges() {
		key := dependencyKey(edge.ConsumerID, edge.ParameterIndex)
		edges[key] = edge.DependencyID
	}
	variables := make(map[string]string, len(providers))
	for index, item := range providers {
		variables[item.SymbolID] = providerVariable(index)
	}
	result := make(map[string][]string, len(providers))
	for _, item := range providers {
		inputs := make([]string, len(item.Dependencies))
		for _, dependency := range item.Dependencies {
			dependencyID, ok := edges[dependencyKey(item.SymbolID, dependency.Index)]
			if !ok {
				return nil, fmt.Errorf(
					"provider %s parameter %d has no validated graph edge",
					item.SymbolID,
					dependency.Index,
				)
			}
			variable, ok := variables[dependencyID]
			if !ok {
				return nil, fmt.Errorf(
					"provider %s parameter %d references unknown provider %s",
					item.SymbolID,
					dependency.Index,
					dependencyID,
				)
			}
			inputs[dependency.Index] = variable
		}
		result[item.SymbolID] = inputs
	}
	return result, nil
}

func validateTarget(target Target, applicationTarget application.Target) []Diagnostic {
	var diagnostics []Diagnostic
	add := func(kind, message string) {
		diagnostics = append(diagnostics, targetDiagnostic(applicationTarget, kind, message))
	}
	if !targetIDPattern.MatchString(target.ID) {
		add("target-id", fmt.Sprintf("generation target ID %q must match %s", target.ID, targetIDPattern))
	}
	if target.ModulePath == "" {
		add("module-path", "generation target module path is required")
	}
	if target.ModuleRoot == "" {
		add("module-root", "generation target module root is required")
	}
	if target.PackagePath == "" {
		add("package-path", "generated package import path is required")
	}
	if target.OutputDir == "" {
		add("output-dir", "generated output directory is required")
	}
	if target.ManifestPath == "" {
		add("manifest-path", "generated manifest path is required")
	}
	sortDiagnostics(diagnostics)
	return diagnostics
}

func validateRenderable(
	program *load.Program,
	model application.Model,
	applicationTarget application.Target,
	target Target,
) []Diagnostic {
	var diagnostics []Diagnostic
	packages := program.Packages()
	sourcePackage, ok := packageByPath(packages, applicationTarget.PackagePath)
	if ok && sourcePackage.Types != nil {
		for _, imported := range sourcePackage.Types.Imports() {
			if imported.Path() == target.PackagePath {
				diagnostics = append(diagnostics, targetDiagnostic(
					applicationTarget,
					"import-cycle",
					fmt.Sprintf(
						"application package %s imports generated package %s; generated output must be imported only by an outer command package",
						sourcePackage.Path,
						target.PackagePath,
					),
				))
			}
		}
	}
	packageNames := make(map[string]string, len(packages))
	for _, pkg := range packages {
		packageNames[pkg.Path] = pkg.Name
	}
	for _, item := range model.Providers() {
		switch {
		case item.PackagePath == target.PackagePath:
			diagnostics = append(diagnostics, providerRenderDiagnostic(
				applicationTarget,
				item,
				"self-import",
				fmt.Sprintf("provider %s is declared in generated package %s", item.SymbolID, target.PackagePath),
			))
		case packageNames[item.PackagePath] == "main":
			diagnostics = append(diagnostics, providerRenderDiagnostic(
				applicationTarget,
				item,
				"main-package",
				fmt.Sprintf(
					"provider %s is declared in package main, which generated package %s cannot import; move providers into an importable package",
					item.SymbolID,
					target.PackagePath,
				),
			))
		case !token.IsExported(item.Name):
			diagnostics = append(diagnostics, providerRenderDiagnostic(
				applicationTarget,
				item,
				"unexported-provider",
				fmt.Sprintf(
					"provider %s is unexported; target-scoped generated packages require exported @Bean functions",
					item.SymbolID,
				),
			))
		}
	}
	for _, component := range model.Components() {
		methods := []load.Symbol{component.Start.Method}
		if component.Stop != nil {
			methods = append(methods, component.Stop.Method)
		}
		for _, method := range methods {
			if token.IsExported(method.Name) {
				continue
			}
			diagnostics = append(diagnostics, Diagnostic{
				Position:         method.Position,
				PhysicalPosition: method.PhysicalPosition,
				TargetID:         applicationTarget.SymbolID,
				Kind:             "unexported-hook",
				Message: fmt.Sprintf(
					"lifecycle method %s is unexported; target-scoped generated packages require exported hook methods",
					method.ID,
				),
			})
		}
	}
	sortDiagnostics(diagnostics)
	return diagnostics
}

func modelHash(
	model application.Model,
	applicationTarget application.Target,
	target Target,
) (string, error) {
	type inputDependency struct {
		Index int    `json:"index"`
		Type  string `json:"type"`
	}
	type inputProvider struct {
		ID      string            `json:"id"`
		Module  string            `json:"module,omitempty"`
		Output  string            `json:"output"`
		Cleanup bool              `json:"cleanup"`
		Error   bool              `json:"error"`
		Inputs  []inputDependency `json:"inputs"`
	}
	type inputEdge struct {
		Consumer  string `json:"consumer"`
		Parameter int    `json:"parameter"`
		Provider  string `json:"provider"`
	}
	type inputComponent struct {
		Provider string `json:"provider"`
		Start    string `json:"start"`
		Stop     string `json:"stop,omitempty"`
	}
	type inputRoot struct {
		Index    int    `json:"index"`
		Type     string `json:"type"`
		Provider string `json:"provider"`
	}
	type input struct {
		Schema     int              `json:"schema"`
		Target     TargetSummary    `json:"target"`
		Symbol     string           `json:"symbol"`
		Providers  []inputProvider  `json:"providers"`
		Edges      []inputEdge      `json:"edges"`
		Components []inputComponent `json:"components"`
		Roots      []inputRoot      `json:"roots"`
	}
	value := input{
		Schema: SchemaVersion,
		Target: summarizeTarget(target),
		Symbol: applicationTarget.SymbolID,
	}
	providers := model.Providers()
	providerModules := providerModuleIDs(model, providers)
	for _, item := range providers {
		inputs := make([]inputDependency, len(item.Dependencies))
		for index, dependency := range item.Dependencies {
			inputs[index] = inputDependency{Index: dependency.Index, Type: dependency.TypeID}
		}
		value.Providers = append(value.Providers, inputProvider{
			ID:      item.SymbolID,
			Module:  providerModules[item.SymbolID],
			Output:  item.OutputTypeID,
			Cleanup: item.ReturnsCleanup,
			Error:   item.ReturnsError,
			Inputs:  inputs,
		})
	}
	for _, edge := range model.Edges() {
		value.Edges = append(value.Edges, inputEdge{
			Consumer:  edge.ConsumerID,
			Parameter: edge.ParameterIndex,
			Provider:  edge.DependencyID,
		})
	}
	for _, component := range model.Components() {
		item := inputComponent{
			Provider: component.Provider.SymbolID,
			Start:    component.Start.MethodID,
		}
		if component.Stop != nil {
			item.Stop = component.Stop.MethodID
		}
		value.Components = append(value.Components, item)
	}
	for _, root := range applicationTarget.Roots() {
		value.Roots = append(value.Roots, inputRoot{
			Index:    root.Index,
			Type:     root.TypeID,
			Provider: root.ProviderID,
		})
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	return contentHash(encoded), nil
}

func contentHash(content []byte) string {
	digest := sha256.Sum256(content)
	return "sha256:" + hex.EncodeToString(digest[:])
}

func summarizeTarget(target Target) TargetSummary {
	return TargetSummary{
		ID:           target.ID,
		ModulePath:   target.ModulePath,
		PackagePath:  target.PackagePath,
		OutputDir:    target.OutputDir,
		ManifestPath: target.ManifestPath,
	}
}

func packageByPath(packages []load.Package, packagePath string) (load.Package, bool) {
	for _, pkg := range packages {
		if pkg.Path == packagePath {
			return pkg, true
		}
	}
	return load.Package{}, false
}

func containsTarget(targets []application.Target, symbolID string) bool {
	for _, target := range targets {
		if target.SymbolID == symbolID {
			return true
		}
	}
	return false
}

func providerVariable(index int) string {
	return "provider" + strconv.Itoa(index)
}

func dependencyKey(providerID string, parameter int) string {
	return providerID + "\x00" + strconv.Itoa(parameter)
}

func providerRenderDiagnostic(
	applicationTarget application.Target,
	item provider.Provider,
	kind string,
	message string,
) Diagnostic {
	return Diagnostic{
		Position:         item.Position,
		PhysicalPosition: item.PhysicalPosition,
		TargetID:         applicationTarget.SymbolID,
		Kind:             kind,
		Message:          message,
	}
}

func targetDiagnostic(target application.Target, kind, message string) Diagnostic {
	return Diagnostic{
		Position:         target.Position,
		PhysicalPosition: target.PhysicalPosition,
		TargetID:         target.SymbolID,
		Kind:             kind,
		Message:          message,
	}
}

func sortDiagnostics(diagnostics []Diagnostic) {
	sort.SliceStable(diagnostics, func(i, j int) bool {
		left, right := diagnostics[i], diagnostics[j]
		if left.PhysicalPosition.Filename != right.PhysicalPosition.Filename {
			return left.PhysicalPosition.Filename < right.PhysicalPosition.Filename
		}
		if left.PhysicalPosition.Offset != right.PhysicalPosition.Offset {
			return left.PhysicalPosition.Offset < right.PhysicalPosition.Offset
		}
		if left.TargetID != right.TargetID {
			return left.TargetID < right.TargetID
		}
		if left.Kind != right.Kind {
			return left.Kind < right.Kind
		}
		return left.Message < right.Message
	})
}
