package generate

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/StevenBuglione/spice/compiler/application"
	"github.com/StevenBuglione/spice/compiler/load"
	"github.com/StevenBuglione/spice/compiler/resolve"
)

func TestRenderProducesDeterministicExecutableApplication(t *testing.T) {
	root := generationFixture(t)
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	if target.ID != "shop" ||
		target.OutputDir != "internal/spicegen/shop" ||
		target.ManifestPath != ".spice/shop.manifest.json" ||
		target.PackagePath != "example.com/shop/internal/spicegen/shop" {
		t.Fatalf("DefaultTarget() = %#v", target)
	}

	var firstSource, firstManifest []byte
	for iteration := range 20 {
		plan, renderDiagnostics := Render(program, model, applicationTarget, target)
		if len(renderDiagnostics) != 0 {
			t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(renderDiagnostics))
		}
		files := plan.Files()
		if len(files) != 1 || files[0].Path != "internal/spicegen/shop/zz_spice_gen.go" {
			t.Fatalf("Files() = %#v", files)
		}
		if iteration == 0 {
			firstSource = files[0].Content()
			firstManifest = plan.ManifestContent()
		} else if !bytes.Equal(firstSource, files[0].Content()) ||
			!bytes.Equal(firstManifest, plan.ManifestContent()) {
			t.Fatalf("Render() changed bytes at iteration %d", iteration)
		}
	}

	for _, required := range []string{
		"// Code generated by Spice. DO NOT EDIT.",
		"//go:build !spice_generate",
		`const TargetID = "shop"`,
		"components.ConfigProvider()",
		"components.StoreProvider(provider0)",
		"components.ServerProvider(provider1)",
		"fmt \"fmt\"\n\n\tcomponents \"example.com/shop/components\"",
		"RegisterCleanup(",
		"Start: provider2.Start",
		"provider2.Stop",
		"func (application *Application) Run(",
	} {
		if !bytes.Contains(firstSource, []byte(required)) {
			t.Fatalf("generated source missing %q:\n%s", required, firstSource)
		}
	}
	assertOrdered(
		t, string(firstSource),
		"components.ConfigProvider()",
		"components.StoreProvider(provider0)",
		"components.ServerProvider(provider1)",
	)
	for _, forbidden := range []string{
		root,
		filepath.ToSlash(root),
		time.Now().Format("2006-01-02"),
	} {
		if forbidden != "" &&
			(bytes.Contains(firstSource, []byte(forbidden)) || bytes.Contains(firstManifest, []byte(forbidden))) {
			t.Fatalf("generated output contains machine-specific value %q", forbidden)
		}
	}

	plan, renderDiagnostics := Render(program, model, applicationTarget, target)
	if len(renderDiagnostics) != 0 {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(renderDiagnostics))
	}
	manifest := plan.Manifest()
	if manifest.Schema != SchemaVersion ||
		manifest.GeneratorVersion != GeneratorVersion ||
		manifest.GoFormatLine != GoFormatLine ||
		!strings.HasPrefix(manifest.InputSHA256, "sha256:") ||
		len(manifest.Files) != 1 ||
		manifest.Files[0].SHA256 != plan.Files()[0].SHA256 {
		t.Fatalf("Manifest() = %#v", manifest)
	}
	var decoded Manifest
	if err := json.Unmarshal(plan.ManifestContent(), &decoded); err != nil {
		t.Fatalf("json.Unmarshal(manifest) error = %v", err)
	}
	if !slices.Equal(decoded.Files, manifest.Files) || decoded.Target != manifest.Target {
		t.Fatalf("decoded manifest = %#v, want %#v", decoded, manifest)
	}

	writePlan(t, root, plan)
	writeTestFile(t, root, "internal/spicegen/shop/zz_spice_gen_test.go", generatedRuntimeTest)
	runGoTest(t, root, "./internal/spicegen/shop")
}

func TestRenderAssignsStableAliasesForPackageNameCollisions(t *testing.T) {
	root := writeModule(t, "example.com/collision", map[string]string{
		"a/providers.go": `package shared

type AlphaValue struct{}

// @Bean
func Alpha() AlphaValue { return AlphaValue{} }
`,
		"b/providers.go": `package shared

type BetaValue struct{}

// @Bean
func Beta() BetaValue { return BetaValue{} }
`,
		"bootstrap/application.go": `package bootstrap

import (
	shareda "example.com/collision/a"
	sharedb "example.com/collision/b"
)

// @Application
func Collision(shareda.AlphaValue, sharedb.BetaValue) {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	plan, diagnostics := Render(program, model, applicationTarget, target)
	if len(diagnostics) != 0 {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	source := string(plan.Files()[0].Content())
	for _, expected := range []string{
		`shared "example.com/collision/a"`,
		`shared2 "example.com/collision/b"`,
		"shared.Alpha()",
		"shared2.Beta()",
	} {
		if !strings.Contains(source, expected) {
			t.Fatalf("source missing %q:\n%s", expected, source)
		}
	}
}

func TestRenderRejectsCodeThatGeneratedPackageCannotAccess(t *testing.T) {
	root := writeModule(t, "example.com/access", map[string]string{
		"app/application.go": `package app

import "context"

type Service struct{}

// @Bean
func privateProvider() Service { return Service{} }

// @OnStart
func (Service) privateStart(context.Context) error { return nil }

// @Application
func Application(Service) {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	_, diagnostics = Render(program, model, applicationTarget, target)
	if len(diagnostics) != 2 ||
		!containsGenerationDiagnostic(diagnostics, "target-scoped generated packages require exported @Bean functions") ||
		!containsGenerationDiagnostic(diagnostics, "target-scoped generated packages require exported hook methods") {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
}

func TestRenderRejectsProviderInMainPackage(t *testing.T) {
	root := writeModule(t, "example.com/command", map[string]string{
		"main.go": `package main

type Service struct{}

// @Bean
func ServiceProvider() Service { return Service{} }

// @Application
func Command(Service) {}

func main() {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, ".")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	_, diagnostics = Render(program, model, applicationTarget, target)
	if len(diagnostics) != 1 ||
		!containsGenerationDiagnostic(diagnostics, "declared in package main") {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
}

func TestRenderRejectsApplicationImportCycle(t *testing.T) {
	root := writeModule(t, "example.com/cycle", map[string]string{
		"app/application.go": `package app

import _ "example.com/cycle/internal/spicegen/application"

// @Application
func Application() {}
`,
		"internal/spicegen/application/existing.go": "package spicegen\n",
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	_, diagnostics = Render(program, model, applicationTarget, target)
	if len(diagnostics) != 1 ||
		!containsGenerationDiagnostic(diagnostics, "imports generated package") {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
}

func TestRenderRejectsInvalidInputs(t *testing.T) {
	root := writeModule(t, "example.com/inputs", map[string]string{
		"app/application.go": `package app

// @Application
func Application() {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	valid, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}

	if _, nilDiagnostics := Render(nil, model, applicationTarget, valid); len(nilDiagnostics) != 1 {
		t.Fatalf("Render(nil) diagnostics = %#v", nilDiagnostics)
	}
	invalidModel := application.Build(nil, resolve.Result{})
	if _, modelDiagnostics := Render(program, invalidModel, applicationTarget, valid); len(modelDiagnostics) != 1 ||
		!containsGenerationDiagnostic(modelDiagnostics, "model has 1 diagnostic") {
		t.Fatalf("Render(invalid model) diagnostics = %#v", modelDiagnostics)
	}
	if _, unknownDiagnostics := Render(program, model, application.Target{}, valid); len(unknownDiagnostics) != 1 ||
		unknownDiagnostics[0].Kind != "unknown-target" {
		t.Fatalf("Render(unknown target) diagnostics = %#v", unknownDiagnostics)
	}

	invalid := Target{ID: "Not-Portable"}
	if _, targetDiagnostics := Render(program, model, applicationTarget, invalid); len(targetDiagnostics) != 6 {
		t.Fatalf("Render(invalid target) diagnostics = %v, want 6", generationDiagnosticStrings(targetDiagnostics))
	}
	if _, defaultDiagnostics := DefaultTarget(nil, applicationTarget); len(defaultDiagnostics) != 1 {
		t.Fatalf("DefaultTarget(nil) diagnostics = %#v", defaultDiagnostics)
	}
	if _, moduleDiagnostics := DefaultTarget(&load.Program{}, applicationTarget); len(moduleDiagnostics) != 1 ||
		moduleDiagnostics[0].Kind != "module" {
		t.Fatalf("DefaultTarget(no module) diagnostics = %#v", moduleDiagnostics)
	}
}

func TestPlanAccessorsReturnDefensiveCopies(t *testing.T) {
	root := writeModule(t, "example.com/copies", map[string]string{
		"app/application.go": `package app

// @Application
func Application() {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	plan, diagnostics := Render(program, model, applicationTarget, target)
	if len(diagnostics) != 0 {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}

	files := plan.Files()
	files[0].content[0] = 'X'
	content := files[0].Content()
	content[0] = 'Y'
	if plan.Files()[0].Content()[0] != '/' {
		t.Fatal("Files or File.Content returned mutable storage")
	}
	manifest := plan.Manifest()
	manifest.Files[0].Path = "changed"
	if plan.Manifest().Files[0].Path == "changed" {
		t.Fatal("Manifest returned mutable file storage")
	}
	manifestContent := plan.ManifestContent()
	manifestContent[0] = 'X'
	if plan.ManifestContent()[0] != '{' {
		t.Fatal("ManifestContent returned mutable storage")
	}
	if plan.Target() != target {
		t.Fatalf("Target() = %#v, want %#v", plan.Target(), target)
	}
}

func TestGenerationHelpers(t *testing.T) {
	t.Parallel()
	digest := contentHash([]byte("spice"))
	if len(digest) != len("sha256:")+sha256HexLength || !strings.HasPrefix(digest, "sha256:") {
		t.Fatalf("contentHash() = %q", digest)
	}
	diagnostic := Diagnostic{Message: "broken"}
	if got := diagnostic.Error(); got != "<generation>:1:1: broken" {
		t.Fatalf("Diagnostic.Error() = %q", got)
	}
}

const sha256HexLength = 64

const generatedRuntimeTest = `package spicegen

import (
	"context"
	"errors"
	"slices"
	"testing"

	"example.com/shop/components"
	"github.com/StevenBuglione/spice/lifecycle"
)

func TestGeneratedApplication(t *testing.T) {
	components.Reset(false)
	application, err := NewApplication(context.Background())
	if err != nil {
		t.Fatalf("NewApplication() error = %v", err)
	}
	if got := application.State(); got != lifecycle.StateConstructed {
		t.Fatalf("State() = %q", got)
	}
	if err := application.Start(context.Background()); err != nil {
		t.Fatalf("Start() error = %v", err)
	}
	if err := application.Stop(context.Background()); err != nil {
		t.Fatalf("Stop() error = %v", err)
	}
	if err := application.Stop(context.Background()); err != nil {
		t.Fatalf("second Stop() error = %v", err)
	}
	want := []string{"construct config", "construct store", "construct server", "start server", "stop server", "cleanup store"}
	if got := components.Trace(); !slices.Equal(got, want) {
		t.Fatalf("trace = %v, want %v", got, want)
	}

	components.Reset(true)
	failed, err := NewApplication(context.Background())
	if failed != nil || !errors.Is(err, components.ErrServer) {
		t.Fatalf("NewApplication(failure) = %#v, %v", failed, err)
	}
	want = []string{"construct config", "construct store", "construct server", "cleanup store"}
	if got := components.Trace(); !slices.Equal(got, want) {
		t.Fatalf("failure trace = %v, want %v", got, want)
	}
}
`

func generationFixture(t *testing.T) string {
	t.Helper()
	return writeModule(t, "example.com/shop", map[string]string{
		"components/providers.go": `package components

import (
	"context"
	"errors"

	"github.com/StevenBuglione/spice/lifecycle"
)

var ErrServer = errors.New("server construction failed")

var (
	trace []string
	fail bool
)

type Config struct{}
type Store struct{}
type Server struct{}

func Reset(shouldFail bool) {
	trace = nil
	fail = shouldFail
}

func Trace() []string {
	return append([]string(nil), trace...)
}

// @Bean
func ConfigProvider() Config {
	trace = append(trace, "construct config")
	return Config{}
}

// @Bean
func StoreProvider(Config) (*Store, lifecycle.Cleanup) {
	trace = append(trace, "construct store")
	return &Store{}, func(context.Context) error {
		trace = append(trace, "cleanup store")
		return nil
	}
}

// @Bean
func ServerProvider(*Store) (*Server, error) {
	trace = append(trace, "construct server")
	if fail {
		return nil, ErrServer
	}
	return &Server{}, nil
}

// @OnStart
func (*Server) Start(context.Context) error {
	trace = append(trace, "start server")
	return nil
}

// @OnStop
func (*Server) Stop(context.Context) error {
	trace = append(trace, "stop server")
	return nil
}
`,
		"bootstrap/application.go": `package bootstrap

import "example.com/shop/components"

// @Application
func Shop(*components.Server) {
	panic("application marker bodies must not execute")
}
`,
	})
}

func buildApplication(
	t *testing.T,
	root string,
	patterns ...string,
) (*load.Program, application.Model, application.Target) {
	t.Helper()
	program, err := load.Load(context.Background(), load.Options{Dir: root}, patterns...)
	if err != nil {
		t.Fatalf("load.Load() error = %v", err)
	}
	resolution := resolve.Annotations(program)
	if len(resolution.Diagnostics) != 0 {
		t.Fatalf("resolve.Annotations() diagnostics = %v", resolution.Diagnostics)
	}
	model := application.Build(program, resolution)
	if diagnostics := model.Diagnostics(); len(diagnostics) != 0 {
		t.Fatalf("application.Build() diagnostics = %v", applicationDiagnosticStrings(diagnostics))
	}
	targets := model.Targets()
	if len(targets) != 1 {
		t.Fatalf("Targets() = %#v, want one", targets)
	}
	return program, model, targets[0]
}

func writeModule(t *testing.T, modulePath string, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	repository := repositoryRoot(t)
	goMod := "module " + modulePath + "\n\ngo 1.26.0\n\n" +
		"require github.com/StevenBuglione/spice v0.0.0\n\n" +
		"replace github.com/StevenBuglione/spice => " + filepath.ToSlash(repository) + "\n"
	writeTestFile(t, root, "go.mod", goMod)
	paths := make([]string, 0, len(files))
	for file := range files {
		paths = append(paths, file)
	}
	sort.Strings(paths)
	for _, file := range paths {
		writeTestFile(t, root, file, files[file])
	}
	return root
}

func writePlan(t *testing.T, root string, plan Plan) {
	t.Helper()
	for _, file := range plan.Files() {
		writeTestFile(t, root, file.Path, string(file.Content()))
	}
	writeTestFile(t, root, plan.Target().ManifestPath, string(plan.ManifestContent()))
}

func writeTestFile(t *testing.T, root, relativePath, content string) {
	t.Helper()
	fullPath := filepath.Join(root, filepath.FromSlash(relativePath))
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(fullPath, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func repositoryRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("filepath.Abs() error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		t.Fatalf("repository root %q: %v", root, err)
	}
	return root
}

func runGoTest(t *testing.T, root string, patterns ...string) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	arguments := append([]string{"test", "-mod=mod", "-count=1"}, patterns...)
	command := exec.CommandContext(ctx, "go", arguments...)
	command.Dir = root
	command.Env = append(os.Environ(), "GOWORK=off", "GOPROXY=off")
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("go %s: %v\n%s", strings.Join(arguments, " "), err, output)
	}
}

func assertOrdered(t *testing.T, content string, values ...string) {
	t.Helper()
	previous := -1
	for _, value := range values {
		index := strings.Index(content, value)
		if index <= previous {
			t.Fatalf("%q is not ordered after prior values in:\n%s", value, content)
		}
		previous = index
	}
}

func containsGenerationDiagnostic(diagnostics []Diagnostic, text string) bool {
	for _, diagnostic := range diagnostics {
		if strings.Contains(diagnostic.Message, text) {
			return true
		}
	}
	return false
}

func generationDiagnosticStrings(diagnostics []Diagnostic) []string {
	result := make([]string, len(diagnostics))
	for index, diagnostic := range diagnostics {
		result[index] = diagnostic.Error()
	}
	return result
}

func applicationDiagnosticStrings(diagnostics []application.Diagnostic) []string {
	result := make([]string, len(diagnostics))
	for index, diagnostic := range diagnostics {
		result[index] = diagnostic.Error()
	}
	return result
}
