package generate

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/StevenBuglione/spice/compiler/application"
	"github.com/StevenBuglione/spice/compiler/load"
	"github.com/StevenBuglione/spice/compiler/resolve"
)

func TestRenderProducesDeterministicExecutableApplication(t *testing.T) {
	root := generationFixture(t)
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	if target.ID != "shop" ||
		target.OutputDir != "internal/spicegen/shop" ||
		target.ManifestPath != ".spice/shop.manifest.json" ||
		target.PackagePath != "example.com/shop/internal/spicegen/shop" {
		t.Fatalf("DefaultTarget() = %#v", target)
	}

	var firstSource, firstManifest []byte
	for iteration := range 20 {
		plan, renderDiagnostics := Render(program, model, applicationTarget, target)
		if len(renderDiagnostics) != 0 {
			t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(renderDiagnostics))
		}
		files := plan.Files()
		if len(files) != 1 || files[0].Path != "internal/spicegen/shop/zz_spice_gen.go" {
			t.Fatalf("Files() = %#v", files)
		}
		if iteration == 0 {
			firstSource = files[0].Content()
			firstManifest = plan.ManifestContent()
		} else if !bytes.Equal(firstSource, files[0].Content()) ||
			!bytes.Equal(firstManifest, plan.ManifestContent()) {
			t.Fatalf("Render() changed bytes at iteration %d", iteration)
		}
	}

	for _, required := range []string{
		"// Code generated by Spice. DO NOT EDIT.",
		"//go:build !spice_generate",
		`const TargetID = "shop"`,
		"components.ConfigProvider()",
		"components.StoreProvider(provider0)",
		"components.ServerProvider(provider1)",
		"fmt \"fmt\"\n\n\tcomponents \"example.com/shop/components\"",
		"RegisterModuleCleanup(",
		"provider2.Start",
		"provider2.Stop",
		`Module: "example.com/shop/components"`,
		"observers ...spicelifecycle.Observer",
		"func (application *Application) RegisterObserver(",
		"func (application *Application) Run(",
	} {
		if !bytes.Contains(firstSource, []byte(required)) {
			t.Fatalf("generated source missing %q:\n%s", required, firstSource)
		}
	}
	assertOrdered(
		t, string(firstSource),
		"components.ConfigProvider()",
		"components.StoreProvider(provider0)",
		"components.ServerProvider(provider1)",
	)
	for _, forbidden := range []string{
		root,
		filepath.ToSlash(root),
		time.Now().Format("2006-01-02"),
	} {
		if forbidden != "" &&
			(bytes.Contains(firstSource, []byte(forbidden)) || bytes.Contains(firstManifest, []byte(forbidden))) {
			t.Fatalf("generated output contains machine-specific value %q", forbidden)
		}
	}

	plan, renderDiagnostics := Render(program, model, applicationTarget, target)
	if len(renderDiagnostics) != 0 {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(renderDiagnostics))
	}
	manifest := plan.Manifest()
	if manifest.Schema != SchemaVersion ||
		manifest.GeneratorVersion != GeneratorVersion ||
		manifest.GoFormatLine != GoFormatLine ||
		!strings.HasPrefix(manifest.InputSHA256, "sha256:") ||
		len(manifest.Files) != 1 ||
		manifest.Files[0].SHA256 != plan.Files()[0].SHA256 {
		t.Fatalf("Manifest() = %#v", manifest)
	}
	var decoded Manifest
	if err := json.Unmarshal(plan.ManifestContent(), &decoded); err != nil {
		t.Fatalf("json.Unmarshal(manifest) error = %v", err)
	}
	if !slices.Equal(decoded.Files, manifest.Files) || decoded.Target != manifest.Target {
		t.Fatalf("decoded manifest = %#v, want %#v", decoded, manifest)
	}

	writePlan(t, root, plan)
	writeTestFile(t, root, "internal/spicegen/shop/zz_spice_gen_test.go", generatedRuntimeTest)
	runGoTest(t, root, "./internal/spicegen/shop")
}

func TestRenderAssignsStableAliasesForPackageNameCollisions(t *testing.T) {
	root := writeModule(t, "example.com/collision", map[string]string{
		"a/providers.go": `package shared

type AlphaValue struct{}

// @Bean
func Alpha() AlphaValue { return AlphaValue{} }
`,
		"b/providers.go": `package shared

type BetaValue struct{}

// @Bean
func Beta() BetaValue { return BetaValue{} }
`,
		"bootstrap/application.go": `package bootstrap

import (
	shareda "example.com/collision/a"
	sharedb "example.com/collision/b"
)

// @Application
func Collision(shareda.AlphaValue, sharedb.BetaValue) {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	plan, diagnostics := Render(program, model, applicationTarget, target)
	if len(diagnostics) != 0 {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	source := string(plan.Files()[0].Content())
	for _, expected := range []string{
		`shared "example.com/collision/a"`,
		`shared2 "example.com/collision/b"`,
		"shared.Alpha()",
		"shared2.Beta()",
	} {
		if !strings.Contains(source, expected) {
			t.Fatalf("source missing %q:\n%s", expected, source)
		}
	}
}

func TestRenderGeneratesTypedConfigurationProviders(t *testing.T) {
	root := writeModule(t, "example.com/configured", map[string]string{
		"shared/level.go": `package shared

type Level string
`,
		"components/application.go": `// Package components owns configured services.
//
// @Module
package components

import (
	"time"

	"example.com/configured/shared"
)

type WorkerCount int8

// @Configuration(prefix="server")
type Settings struct {
	Host string ` + "`spice:\"host,default=localhost\"`" + `
	Port WorkerCount ` + "`spice:\"port,required,env=SERVER_PORT\"`" + `
	Debug bool ` + "`spice:\"debug\"`" + `
	Timeout time.Duration ` + "`spice:\"timeout,default=5s\"`" + `
	Level shared.Level ` + "`spice:\"level,required\"`" + `
	Token string ` + "`spice:\"token,secret\"`" + `
}

type Server struct {
	Settings Settings
}

var captured Settings

func Captured() Settings {
	return captured
}

// @Bean
func NewServer(settings Settings) *Server {
	captured = settings
	return &Server{Settings: settings}
}
`,
		"bootstrap/application.go": `package bootstrap

import "example.com/configured/components"

// @Application
func Configured(*components.Server) {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	plan, diagnostics := Render(program, model, applicationTarget, target)
	if len(diagnostics) != 0 {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	source := string(plan.Files()[0].Content())
	for _, expected := range []string{
		`spiceconfig "github.com/StevenBuglione/spice/config"`,
		"type ApplicationOptions struct",
		"func ConfigurationSchema() (spiceconfig.Schema, error)",
		"func NewApplicationWithOptions(",
		"components.Settings{}",
		"components.WorkerCount(rawValue)",
		"shared.Level(rawValue)",
		"if int64(convertedValue) != rawValue",
		`Key:         "server.port"`,
		`Environment: "SERVER_PORT"`,
		"NewServer(provider0)",
	} {
		if !strings.Contains(source, expected) {
			t.Fatalf("generated source missing %q:\n%s", expected, source)
		}
	}
	assertOrdered(t, source, "components.Settings{}", "components.NewServer(provider0)")

	writePlan(t, root, plan)
	writeTestFile(t, root, "internal/spicegen/configured/configuration_test.go", generatedConfigurationTest)
	runGoTest(t, root, "./internal/spicegen/configured")
}

func TestRenderGeneratesExecutableHTTPAdapters(t *testing.T) {
	root := writeModule(t, "example.com/web", map[string]string{
		"api/api.go": `// Package api owns HTTP delivery.
//
// @Module
package api

import (
	"context"
	"errors"
	"net/http"

	spiceweb "github.com/StevenBuglione/spice/web"
)

type UserID string

type GetRequest struct {
	ID UserID ` + "`path:\"id\"`" + `
	Verbose bool ` + "`query:\"verbose\"`" + `
	Limit int8 ` + "`header:\"X-Limit,required\"`" + `
}

func (request GetRequest) Validate(context.Context) error {
	if request.ID == "invalid" {
		return errors.New("secret validation detail")
	}
	return nil
}

type CreateBody struct {
	Name string ` + "`json:\"name\"`" + `
}

type CreateRequest struct {
	ID UserID ` + "`path:\"id\"`" + `
	Body CreateBody ` + "`body:\"\"`" + `
}

type Response struct {
	ID string ` + "`json:\"id\"`" + `
	Verbose bool ` + "`json:\"verbose\"`" + `
	Limit int8 ` + "`json:\"limit\"`" + `
}

// @Controller(prefix="/users")
type API struct{}

var mux *http.ServeMux

func Mux() *http.ServeMux { return mux }

// @Bean
func NewMux() *http.ServeMux {
	mux = http.NewServeMux()
	return mux
}

// @Bean
func NewAPI() *API { return &API{} }

// @Get("/{id}")
func (*API) Get(_ context.Context, request GetRequest) (Response, error) {
	if request.ID == "conflict" {
		return Response{}, spiceweb.NewError(spiceweb.Problem{
			Title: "Conflict",
			Status: http.StatusConflict,
		}, nil)
	}
	return Response{ID: string(request.ID), Verbose: request.Verbose, Limit: request.Limit}, nil
}

// @Post("/{id}")
func (*API) Create(context.Context, CreateRequest) (spiceweb.NoContent, error) {
	return spiceweb.NoContent{}, nil
}

// @Get("/raw/status")
func (*API) Raw(writer http.ResponseWriter, _ *http.Request) {
	writer.WriteHeader(http.StatusAccepted)
}
`,
		"bootstrap/application.go": `package bootstrap

import "example.com/web/api"

// @Application
func Web(*api.API) {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	plan, diagnostics := Render(program, model, applicationTarget, target)
	if len(diagnostics) != 0 {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	source := string(plan.Files()[0].Content())
	for _, expected := range []string{
		`http "net/http"`,
		`spiceweb "github.com/StevenBuglione/spice/web"`,
		"type ApplicationOptions struct",
		"func (application *Application) Handler() http.Handler",
		`spiceweb.Register(routeMux, "GET /users/{id}"`,
		`spiceweb.Register(routeMux, "POST /users/{id}"`,
		"spiceweb.Parameter(",
		"spiceweb.DecodeJSON(",
		"spiceweb.Validate(",
		"spiceweb.WriteError(",
		"spiceweb.WriteNoContent(",
	} {
		if !strings.Contains(source, expected) {
			t.Fatalf("generated source missing %q:\n%s", expected, source)
		}
	}
	writePlan(t, root, plan)
	writeTestFile(t, root, "internal/spicegen/web/http_test.go", generatedHTTPTest)
	runGoTest(t, root, "./internal/spicegen/web")
}

func TestRenderRejectsCodeThatGeneratedPackageCannotAccess(t *testing.T) {
	root := writeModule(t, "example.com/access", map[string]string{
		"app/application.go": `package app

import "context"

type Service struct{}

// @Bean
func privateProvider() Service { return Service{} }

// @OnStart
func (Service) privateStart(context.Context) error { return nil }

// @Application
func Application(Service) {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	_, diagnostics = Render(program, model, applicationTarget, target)
	if len(diagnostics) != 2 ||
		!containsGenerationDiagnostic(diagnostics, "target-scoped generated packages require exported @Bean functions") ||
		!containsGenerationDiagnostic(diagnostics, "target-scoped generated packages require exported hook methods") {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
}

func TestRenderRejectsProviderInMainPackage(t *testing.T) {
	root := writeModule(t, "example.com/command", map[string]string{
		"main.go": `package main

type Service struct{}

// @Bean
func ServiceProvider() Service { return Service{} }

// @Application
func Command(Service) {}

func main() {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, ".")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	_, diagnostics = Render(program, model, applicationTarget, target)
	if len(diagnostics) != 1 ||
		!containsGenerationDiagnostic(diagnostics, "declared in package main") {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
}

func TestRenderRejectsApplicationImportCycle(t *testing.T) {
	root := writeModule(t, "example.com/cycle", map[string]string{
		"app/application.go": `package app

import _ "example.com/cycle/internal/spicegen/application"

// @Application
func Application() {}
`,
		"internal/spicegen/application/existing.go": "package spicegen\n",
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	_, diagnostics = Render(program, model, applicationTarget, target)
	if len(diagnostics) != 1 ||
		!containsGenerationDiagnostic(diagnostics, "imports generated package") {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
}

func TestRenderRejectsInvalidInputs(t *testing.T) {
	root := writeModule(t, "example.com/inputs", map[string]string{
		"app/application.go": `package app

// @Application
func Application() {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	valid, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}

	if _, nilDiagnostics := Render(nil, model, applicationTarget, valid); len(nilDiagnostics) != 1 {
		t.Fatalf("Render(nil) diagnostics = %#v", nilDiagnostics)
	}
	invalidModel := application.Build(nil, resolve.Result{})
	if _, modelDiagnostics := Render(program, invalidModel, applicationTarget, valid); len(modelDiagnostics) != 1 ||
		!containsGenerationDiagnostic(modelDiagnostics, "model has 1 diagnostic") {
		t.Fatalf("Render(invalid model) diagnostics = %#v", modelDiagnostics)
	}
	if _, unknownDiagnostics := Render(program, model, application.Target{}, valid); len(unknownDiagnostics) != 1 ||
		unknownDiagnostics[0].Kind != "unknown-target" {
		t.Fatalf("Render(unknown target) diagnostics = %#v", unknownDiagnostics)
	}

	invalid := Target{ID: "Not-Portable"}
	if _, targetDiagnostics := Render(program, model, applicationTarget, invalid); len(targetDiagnostics) != 6 {
		t.Fatalf("Render(invalid target) diagnostics = %v, want 6", generationDiagnosticStrings(targetDiagnostics))
	}
	if _, defaultDiagnostics := DefaultTarget(nil, applicationTarget); len(defaultDiagnostics) != 1 {
		t.Fatalf("DefaultTarget(nil) diagnostics = %#v", defaultDiagnostics)
	}
	if _, moduleDiagnostics := DefaultTarget(&load.Program{}, applicationTarget); len(moduleDiagnostics) != 1 ||
		moduleDiagnostics[0].Kind != "module" {
		t.Fatalf("DefaultTarget(no module) diagnostics = %#v", moduleDiagnostics)
	}
}

func TestRenderInputHashTracksModuleOwnership(t *testing.T) {
	files := map[string]string{
		"app/application.go": `package app

import "context"

type Service struct{}

// @Bean
func ServiceProvider() Service { return Service{} }

// @OnStart
func (Service) Start(context.Context) error { return nil }

// @Application
func Application(Service) {}
`,
	}
	withoutRoot := writeModule(t, "example.com/ownership", files)
	program, model, applicationTarget := buildApplication(t, withoutRoot, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	withoutModule, diagnostics := Render(program, model, applicationTarget, target)
	if len(diagnostics) != 0 {
		t.Fatalf("Render(without module) diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}

	files["app/application.go"] = `// Package app is an application module.
//
// @Module
package app

import "context"

type Service struct{}

// @Bean
func ServiceProvider() Service { return Service{} }

// @OnStart
func (Service) Start(context.Context) error { return nil }

// @Application
func Application(Service) {}
`
	withRoot := writeModule(t, "example.com/ownership", files)
	program, model, applicationTarget = buildApplication(t, withRoot, "./...")
	target, diagnostics = DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget(module) diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	withModule, diagnostics := Render(program, model, applicationTarget, target)
	if len(diagnostics) != 0 {
		t.Fatalf("Render(with module) diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	if withoutModule.Manifest().InputSHA256 == withModule.Manifest().InputSHA256 {
		t.Fatal("module ownership did not change the canonical model input hash")
	}
	if bytes.Equal(
		withoutModule.Files()[0].Content(),
		withModule.Files()[0].Content(),
	) {
		t.Fatal("module ownership did not change generated lifecycle metadata")
	}
}

func TestPlanAccessorsReturnDefensiveCopies(t *testing.T) {
	root := writeModule(t, "example.com/copies", map[string]string{
		"app/application.go": `package app

// @Application
func Application() {}
`,
	})
	program, model, applicationTarget := buildApplication(t, root, "./...")
	target, diagnostics := DefaultTarget(program, applicationTarget)
	if len(diagnostics) != 0 {
		t.Fatalf("DefaultTarget() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}
	plan, diagnostics := Render(program, model, applicationTarget, target)
	if len(diagnostics) != 0 {
		t.Fatalf("Render() diagnostics = %v", generationDiagnosticStrings(diagnostics))
	}

	files := plan.Files()
	files[0].content[0] = 'X'
	content := files[0].Content()
	content[0] = 'Y'
	if plan.Files()[0].Content()[0] != '/' {
		t.Fatal("Files or File.Content returned mutable storage")
	}
	manifest := plan.Manifest()
	manifest.Files[0].Path = "changed"
	if plan.Manifest().Files[0].Path == "changed" {
		t.Fatal("Manifest returned mutable file storage")
	}
	manifestContent := plan.ManifestContent()
	manifestContent[0] = 'X'
	if plan.ManifestContent()[0] != '{' {
		t.Fatal("ManifestContent returned mutable storage")
	}
	if plan.Target() != target {
		t.Fatalf("Target() = %#v, want %#v", plan.Target(), target)
	}
}

func TestGenerationHelpers(t *testing.T) {
	t.Parallel()
	digest := contentHash([]byte("spice"))
	if len(digest) != len("sha256:")+sha256HexLength || !strings.HasPrefix(digest, "sha256:") {
		t.Fatalf("contentHash() = %q", digest)
	}
	diagnostic := Diagnostic{Message: "broken"}
	if got := diagnostic.Error(); got != "<generation>:1:1: broken" {
		t.Fatalf("Diagnostic.Error() = %q", got)
	}
}

const sha256HexLength = 64

const generatedRuntimeTest = `package spicegen

import (
	"context"
	"errors"
	"slices"
	"testing"

	"example.com/shop/components"
	"github.com/StevenBuglione/spice/lifecycle"
)

func TestGeneratedApplication(t *testing.T) {
	components.Reset(false)
	var observations []lifecycle.Observation
	application, err := NewApplication(context.Background(), func(_ context.Context, observation lifecycle.Observation) {
		observations = append(observations, observation)
	})
	if err != nil {
		t.Fatalf("NewApplication() error = %v", err)
	}
	if err := application.RegisterObserver(nil); err == nil {
		t.Fatal("RegisterObserver(nil) error = nil")
	}
	if got := application.State(); got != lifecycle.StateConstructed {
		t.Fatalf("State() = %q", got)
	}
	if err := application.Start(context.Background()); err != nil {
		t.Fatalf("Start() error = %v", err)
	}
	if err := application.Stop(context.Background()); err != nil {
		t.Fatalf("Stop() error = %v", err)
	}
	if err := application.Stop(context.Background()); err != nil {
		t.Fatalf("second Stop() error = %v", err)
	}
	want := []string{"construct config", "construct store", "construct server", "start server", "stop server", "cleanup store"}
	if got := components.Trace(); !slices.Equal(got, want) {
		t.Fatalf("trace = %v, want %v", got, want)
	}
	if len(observations) != 6 {
		t.Fatalf("observations = %#v, want 6", observations)
	}
	for _, observation := range observations {
		if observation.Module != "example.com/shop/components" {
			t.Fatalf("observation module = %q", observation.Module)
		}
	}

	components.Reset(true)
	failed, err := NewApplication(context.Background())
	if failed != nil || !errors.Is(err, components.ErrServer) {
		t.Fatalf("NewApplication(failure) = %#v, %v", failed, err)
	}
	want = []string{"construct config", "construct store", "construct server", "cleanup store"}
	if got := components.Trace(); !slices.Equal(got, want) {
		t.Fatalf("failure trace = %v, want %v", got, want)
	}
}
`

const generatedConfigurationTest = `package spicegen

import (
	"context"
	"strings"
	"testing"
	"time"

	"example.com/configured/components"
	"example.com/configured/shared"
	"github.com/StevenBuglione/spice/config"
)

func TestGeneratedConfigurationApplication(t *testing.T) {
	schema, err := ConfigurationSchema()
	if err != nil {
		t.Fatalf("ConfigurationSchema() error = %v", err)
	}
	properties := schema.Properties()
	if len(properties) != 6 {
		t.Fatalf("schema properties = %#v", properties)
	}
	if properties[3].Key != "server.port" || properties[3].Environment != "SERVER_PORT" ||
		properties[3].Module != "example.com/configured/components" {
		t.Fatalf("port property = %#v", properties[3])
	}
	if properties[4].Key != "server.timeout" || properties[5].Key != "server.token" ||
		!properties[5].Secret {
		t.Fatalf("schema metadata = %#v", properties)
	}

	if application, constructionErr := NewApplication(context.Background()); application != nil ||
		constructionErr == nil || !strings.Contains(constructionErr.Error(), "server.level") {
		t.Fatalf("NewApplication() = %#v, %v", application, constructionErr)
	}

	source, err := config.NewMapSource("test", map[string]string{
		"server.port":  "7",
		"server.debug": "true",
		"server.level": "production",
		"server.token": "top-secret",
	})
	if err != nil {
		t.Fatal(err)
	}
	application, err := NewApplicationWithOptions(context.Background(), ApplicationOptions{
		Profiles: []string{"test"},
		Sources: []config.Source{source},
	})
	if err != nil {
		t.Fatalf("NewApplicationWithOptions() error = %v", err)
	}
	if application == nil {
		t.Fatal("NewApplicationWithOptions() application = nil")
	}
	settings := components.Captured()
	if settings.Host != "localhost" || settings.Port != 7 || !settings.Debug ||
		settings.Timeout != 5*time.Second || settings.Level != shared.Level("production") ||
		settings.Token != "top-secret" {
		t.Fatalf("captured settings = %#v", settings)
	}

	overflow, err := config.NewMapSource("overflow", map[string]string{
		"server.port":  "128",
		"server.level": "production",
	})
	if err != nil {
		t.Fatal(err)
	}
	if application, constructionErr := NewApplicationWithOptions(context.Background(), ApplicationOptions{
		Sources: []config.Source{overflow},
	}); application != nil || constructionErr == nil || !strings.Contains(constructionErr.Error(), "outside") {
		t.Fatalf("overflow application = %#v, %v", application, constructionErr)
	}

	unknown, err := config.NewMapSource("unknown", map[string]string{
		"server.port":  "7",
		"server.level": "production",
		"extra.value":  "rejected",
	})
	if err != nil {
		t.Fatal(err)
	}
	if application, constructionErr := NewApplicationWithOptions(context.Background(), ApplicationOptions{
		Sources: []config.Source{unknown},
	}); application != nil || constructionErr == nil || !strings.Contains(constructionErr.Error(), "unknown property") {
		t.Fatalf("unknown application = %#v, %v", application, constructionErr)
	}
	if application, constructionErr := NewApplicationWithOptions(context.Background(), ApplicationOptions{
		Sources: []config.Source{unknown},
		AllowUnknownConfiguration: true,
	}); application == nil || constructionErr != nil {
		t.Fatalf("allowed unknown application = %#v, %v", application, constructionErr)
	}
}
`

const generatedHTTPTest = `package spicegen

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"example.com/web/api"
)

func TestGeneratedHTTPAdapters(t *testing.T) {
	application, err := NewApplication(context.Background())
	if err != nil {
		t.Fatalf("NewApplication() error = %v", err)
	}
	if application.Handler() == nil || application.Handler() != api.Mux() {
		t.Fatalf("Handler() = %#v, mux=%#v", application.Handler(), api.Mux())
	}

	response := request(t, application.Handler(), http.MethodGet, "/users/42?verbose=true", "", map[string]string{
		"Accept":  "application/json",
		"X-Limit": "7",
	})
	if response.Code != http.StatusOK {
		t.Fatalf("GET status = %d, body=%s", response.Code, response.Body.String())
	}
	var body api.Response
	if err := json.Unmarshal(response.Body.Bytes(), &body); err != nil {
		t.Fatal(err)
	}
	if body.ID != "42" || !body.Verbose || body.Limit != 7 {
		t.Fatalf("GET body = %#v", body)
	}

	response = request(t, application.Handler(), http.MethodGet, "/users/42?verbose=secret-invalid", "", map[string]string{
		"Accept":  "application/json",
		"X-Limit": "7",
	})
	if response.Code != http.StatusBadRequest || strings.Contains(response.Body.String(), "secret-invalid") {
		t.Fatalf("binding response = %d %s", response.Code, response.Body.String())
	}

	response = request(t, application.Handler(), http.MethodGet, "/users/invalid", "", map[string]string{
		"Accept":  "application/json",
		"X-Limit": "7",
	})
	if response.Code != http.StatusBadRequest || strings.Contains(response.Body.String(), "secret validation detail") {
		t.Fatalf("validation response = %d %s", response.Code, response.Body.String())
	}

	response = request(t, application.Handler(), http.MethodGet, "/users/42", "", map[string]string{
		"Accept": "text/plain",
	})
	if response.Code != http.StatusNotAcceptable {
		t.Fatalf("negotiation status = %d, body=%s", response.Code, response.Body.String())
	}

	response = request(t, application.Handler(), http.MethodGet, "/users/conflict", "", map[string]string{
		"Accept":  "application/json",
		"X-Limit": "1",
	})
	if response.Code != http.StatusConflict {
		t.Fatalf("controller error status = %d, body=%s", response.Code, response.Body.String())
	}

	response = request(t, application.Handler(), http.MethodPost, "/users/42", ` + "`" + `{"name":"Spice"}` + "`" + `, map[string]string{
		"Content-Type": "application/json",
	})
	if response.Code != http.StatusNoContent || response.Body.Len() != 0 {
		t.Fatalf("POST response = %d %q", response.Code, response.Body.String())
	}

	response = request(t, application.Handler(), http.MethodGet, "/users/raw/status", "", nil)
	if response.Code != http.StatusAccepted {
		t.Fatalf("raw status = %d", response.Code)
	}

	var nilApplication *Application
	if nilApplication.Handler() != nil {
		t.Fatal("nil Application.Handler() is non-nil")
	}
}

func request(
	t *testing.T,
	handler http.Handler,
	method string,
	target string,
	body string,
	headers map[string]string,
) *httptest.ResponseRecorder {
	t.Helper()
	request := httptest.NewRequest(method, target, strings.NewReader(body))
	for name, value := range headers {
		request.Header.Set(name, value)
	}
	response := httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	return response
}
`

func generationFixture(t *testing.T) string {
	t.Helper()
	return writeModule(t, "example.com/shop", map[string]string{
		"components/providers.go": `// Package components contains the generated application fixture.
//
// @Module
package components

import (
	"context"
	"errors"

	"github.com/StevenBuglione/spice/lifecycle"
)

var ErrServer = errors.New("server construction failed")

var (
	trace []string
	fail bool
)

type Config struct{}
type Store struct{}
type Server struct{}

func Reset(shouldFail bool) {
	trace = nil
	fail = shouldFail
}

func Trace() []string {
	return append([]string(nil), trace...)
}

// @Bean
func ConfigProvider() Config {
	trace = append(trace, "construct config")
	return Config{}
}

// @Bean
func StoreProvider(Config) (*Store, lifecycle.Cleanup) {
	trace = append(trace, "construct store")
	return &Store{}, func(context.Context) error {
		trace = append(trace, "cleanup store")
		return nil
	}
}

// @Bean
func ServerProvider(*Store) (*Server, error) {
	trace = append(trace, "construct server")
	if fail {
		return nil, ErrServer
	}
	return &Server{}, nil
}

// @OnStart
func (*Server) Start(context.Context) error {
	trace = append(trace, "start server")
	return nil
}

// @OnStop
func (*Server) Stop(context.Context) error {
	trace = append(trace, "stop server")
	return nil
}
`,
		"bootstrap/application.go": `package bootstrap

import "example.com/shop/components"

// @Application
func Shop(*components.Server) {
	panic("application marker bodies must not execute")
}
`,
	})
}

func buildApplication(
	t *testing.T,
	root string,
	patterns ...string,
) (*load.Program, application.Model, application.Target) {
	t.Helper()
	program, err := load.Load(context.Background(), load.Options{Dir: root}, patterns...)
	if err != nil {
		t.Fatalf("load.Load() error = %v", err)
	}
	resolution := resolve.Annotations(program)
	if len(resolution.Diagnostics) != 0 {
		t.Fatalf("resolve.Annotations() diagnostics = %v", resolution.Diagnostics)
	}
	model := application.Build(program, resolution)
	if diagnostics := model.Diagnostics(); len(diagnostics) != 0 {
		t.Fatalf("application.Build() diagnostics = %v", applicationDiagnosticStrings(diagnostics))
	}
	targets := model.Targets()
	if len(targets) != 1 {
		t.Fatalf("Targets() = %#v, want one", targets)
	}
	return program, model, targets[0]
}

func writeModule(t *testing.T, modulePath string, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	repository := repositoryRoot(t)
	goMod := "module " + modulePath + "\n\ngo 1.26.0\n\n" +
		"require github.com/StevenBuglione/spice v0.0.0\n\n" +
		"replace github.com/StevenBuglione/spice => " + filepath.ToSlash(repository) + "\n"
	writeTestFile(t, root, "go.mod", goMod)
	paths := make([]string, 0, len(files))
	for file := range files {
		paths = append(paths, file)
	}
	sort.Strings(paths)
	for _, file := range paths {
		writeTestFile(t, root, file, files[file])
	}
	return root
}

func writePlan(t *testing.T, root string, plan Plan) {
	t.Helper()
	for _, file := range plan.Files() {
		writeTestFile(t, root, file.Path, string(file.Content()))
	}
	writeTestFile(t, root, plan.Target().ManifestPath, string(plan.ManifestContent()))
}

func writeTestFile(t *testing.T, root, relativePath, content string) {
	t.Helper()
	fullPath := filepath.Join(root, filepath.FromSlash(relativePath))
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(fullPath, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func repositoryRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("filepath.Abs() error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		t.Fatalf("repository root %q: %v", root, err)
	}
	return root
}

func runGoTest(t *testing.T, root string, patterns ...string) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	arguments := append([]string{"test", "-mod=mod", "-count=1"}, patterns...)
	command := exec.CommandContext(ctx, "go", arguments...)
	command.Dir = root
	command.Env = append(os.Environ(), "GOWORK=off", "GOPROXY=off")
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("go %s: %v\n%s", strings.Join(arguments, " "), err, output)
	}
}

func assertOrdered(t *testing.T, content string, values ...string) {
	t.Helper()
	previous := -1
	for _, value := range values {
		index := strings.Index(content, value)
		if index <= previous {
			t.Fatalf("%q is not ordered after prior values in:\n%s", value, content)
		}
		previous = index
	}
}

func containsGenerationDiagnostic(diagnostics []Diagnostic, text string) bool {
	for _, diagnostic := range diagnostics {
		if strings.Contains(diagnostic.Message, text) {
			return true
		}
	}
	return false
}

func generationDiagnosticStrings(diagnostics []Diagnostic) []string {
	result := make([]string, len(diagnostics))
	for index, diagnostic := range diagnostics {
		result[index] = diagnostic.Error()
	}
	return result
}

func applicationDiagnosticStrings(diagnostics []application.Diagnostic) []string {
	result := make([]string, len(diagnostics))
	for index, diagnostic := range diagnostics {
		result[index] = diagnostic.Error()
	}
	return result
}
