//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: examples/commerce/platform/platform.go:27
// Source: examples/commerce/platform/platform.go:39
// Source: examples/commerce/platform/platform.go:55

package spicegen

import (
	fmt "fmt"
	http "net/http"
	time "time"

	spiceconfig "github.com/StevenBuglione/spice/config"
	platform "github.com/StevenBuglione/spice/examples/commerce/platform"
	storage "github.com/StevenBuglione/spice/examples/commerce/storage"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct4f4cdf491aa5 performs the direct construction selected for spice:symbol:v1|function|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|3:Mux.
func Construct4f4cdf491aa5() (*http.ServeMux, spicelifecycle.Cleanup, error) {
	value := platform.Mux()
	return value, nil, nil
}

// Construct593d6230c9aa performs the direct construction selected for spice:symbol:v1|function|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|9:NewServer.
func Construct593d6230c9aa(dependency0 platform.Settings, dependency1 *http.ServeMux, dependency2 *storage.Database) (*platform.Server, spicelifecycle.Cleanup, error) {
	value, err := platform.NewServer(dependency0, dependency1, dependency2)
	if err != nil {
		var zero *platform.Server
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|function|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|9:NewServer (*github.com/StevenBuglione/spice/examples/commerce/platform.Server): %w", err)
	}
	return value, nil, nil
}

// Bindbd78ddfa9f62 binds the validated configuration declared by spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|8:Settings.
func Bindbd78ddfa9f62(configurationSnapshot spiceconfig.Snapshot) (platform.Settings, error) {
	value := platform.Settings{}
	if _, configured := configurationSnapshot.Lookup("commerce.server.address"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("commerce.server.address")
		if valueErr != nil {
			return platform.Settings{}, fmt.Errorf("decode configuration property commerce.server.address for github.com/StevenBuglione/spice/examples/commerce/platform.Settings.Address: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.Address = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("commerce.server.read-header-timeout"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("commerce.server.read-header-timeout")
		if valueErr != nil {
			return platform.Settings{}, fmt.Errorf("decode configuration property commerce.server.read-header-timeout for github.com/StevenBuglione/spice/examples/commerce/platform.Settings.ReadHeaderTimeout: %w", valueErr)
		}
		convertedValue := time.Duration(rawValue)
		value.ReadHeaderTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("commerce.server.read-timeout"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("commerce.server.read-timeout")
		if valueErr != nil {
			return platform.Settings{}, fmt.Errorf("decode configuration property commerce.server.read-timeout for github.com/StevenBuglione/spice/examples/commerce/platform.Settings.ReadTimeout: %w", valueErr)
		}
		convertedValue := time.Duration(rawValue)
		value.ReadTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("commerce.server.write-timeout"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("commerce.server.write-timeout")
		if valueErr != nil {
			return platform.Settings{}, fmt.Errorf("decode configuration property commerce.server.write-timeout for github.com/StevenBuglione/spice/examples/commerce/platform.Settings.WriteTimeout: %w", valueErr)
		}
		convertedValue := time.Duration(rawValue)
		value.WriteTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("commerce.server.idle-timeout"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("commerce.server.idle-timeout")
		if valueErr != nil {
			return platform.Settings{}, fmt.Errorf("decode configuration property commerce.server.idle-timeout for github.com/StevenBuglione/spice/examples/commerce/platform.Settings.IdleTimeout: %w", valueErr)
		}
		convertedValue := time.Duration(rawValue)
		value.IdleTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("commerce.server.developer-token"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("commerce.server.developer-token")
		if valueErr != nil {
			return platform.Settings{}, fmt.Errorf("decode configuration property commerce.server.developer-token for github.com/StevenBuglione/spice/examples/commerce/platform.Settings.DeveloperToken: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.DeveloperToken = convertedValue
	}
	return value, nil
}
