//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"
	http "net/http"
	time "time"

	spiceasync "github.com/StevenBuglione/spice/async"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

func (application *Application) State() spicelifecycle.State {
	if application == nil || application.coordinator == nil {
		return spicelifecycle.StateInvalid
	}
	return application.coordinator.State()
}

func (application *Application) Start(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("start application: application is nil")
	}
	return application.coordinator.Start(ctx, application.hooks)
}

func (application *Application) Stop(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("stop application: application is nil")
	}
	return application.coordinator.Stop(ctx)
}

func (application *Application) ShutdownTimeout() time.Duration {
	if application == nil {
		return 0
	}
	return application.shutdownTimeout
}

func (application *Application) RegisterObserver(observer spicelifecycle.Observer) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("register lifecycle observer: application is nil")
	}
	return application.coordinator.RegisterObserver(observer)
}

func (application *Application) Run(ctx context.Context, shutdown spicelifecycle.ContextFactory) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("run application: application is nil")
	}
	return application.coordinator.Run(ctx, application.hooks, shutdown)
}

// Components returns a typed snapshot of constructed singleton beans.
func (application *Application) Components() Components {
	if application == nil {
		return Components{}
	}
	return application.components
}

func (application *Application) SubmitServiceVerifySKU(admission context.Context, argument1 string) error {
	if application == nil || application.submitServiceVerifySKU == nil {
		return fmt.Errorf("submit asynchronous task spice:symbol:v1|method|59:github.com/StevenBuglione/spice/examples/commerce/inventory|7:Service|9:VerifySKU: application is nil")
	}
	if state := application.State(); state != spicelifecycle.StateReady {
		return fmt.Errorf("submit asynchronous task spice:symbol:v1|method|59:github.com/StevenBuglione/spice/examples/commerce/inventory|7:Service|9:VerifySKU: application state %s is not ready", state)
	}
	return application.submitServiceVerifySKU(admission, argument1)
}

func (application *Application) AsyncSnapshot() spiceasync.Snapshot {
	if application == nil || application.asyncExecutor == nil {
		return spiceasync.Snapshot{Closed: true}
	}
	return application.asyncExecutor.Snapshot()
}

func (application *Application) Handler() http.Handler {
	if application == nil {
		return nil
	}
	return application.handler
}
