//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	sql "database/sql"
	fmt "fmt"
	http "net/http"

	spiceconfig "github.com/StevenBuglione/spice/config"
	spicedata "github.com/StevenBuglione/spice/data"
	orders "github.com/StevenBuglione/spice/examples/commerce/orders"
	spicesecurity "github.com/StevenBuglione/spice/security"
	spiceweb "github.com/StevenBuglione/spice/web"
)

func registerGeneratedRoutefbc15ec550e7(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
	httpObservers []spiceweb.HTTPObserver,
	routeMux *http.ServeMux,
	authorizer *spicesecurity.Authorizer,
) (*Application, error) {
	_ = configurationSnapshot
	_ = dependencies
	_ = httpObservers
	_ = authorizer
	authorizationPolicy0, authorizationPolicy0Err := spicesecurity.NewPolicy(spicesecurity.PolicySpec{
		Definition: spicesecurity.Definition{
			ID:     "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/commerce/orders|10:Controller|5:Place",
			Module: "github.com/StevenBuglione/spice/examples/commerce/orders",
		},
		AllScopes: []string{"orders:write"},
	})
	if authorizationPolicy0Err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct generated authorization policy for route POST /orders: %w", authorizationPolicy0Err))
	}
	authorizationGuard0, authorizationGuard0Err := spicesecurity.Guard(authorizer, authorizationPolicy0, options.AuthorizationWriteFailure)
	if authorizationGuard0Err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct generated authorization guard for route POST /orders: %w", authorizationGuard0Err))
	}
	routeMiddleware0 := append(append([]spiceweb.Middleware(nil), options.Middleware...), authorizationGuard0)
	routeObservation0, routeObservationErr0 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/commerce/orders|10:Controller|5:Place", Module: "github.com/StevenBuglione/spice/examples/commerce/orders", Method: "POST", Pattern: "/orders"}, httpObservers...)
	if routeObservationErr0 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route POST /orders observation: %w", routeObservationErr0))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "POST /orders", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return spiceweb.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceweb.AcceptsJSON(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces application/json",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := orders.PlaceOrderRequest{}
		if bindErr := spiceweb.DecodeJSON(httpRequest, &requestValue.Body, options.MaxRequestBodyBytes); bindErr != nil {
			_ = writeRouteError(bindErr)
			return
		}
		if validationErr := spiceweb.Validate(httpRequest.Context(), requestValue.Validate); validationErr != nil {
			_ = writeRouteError(validationErr)
			return
		}
		var responseValue orders.OrderResponse
		routeErr := dependencies.provider9.Within(httpRequest.Context(), spicedata.Definition{
			ID:        "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/commerce/orders|10:Controller|5:Place",
			Module:    "github.com/StevenBuglione/spice/examples/commerce/orders",
			Isolation: sql.LevelSerializable,
		}, func(transactionContext context.Context, executor spicedata.Executor) error {
			var transactionErr error
			responseValue, transactionErr = dependencies.provider22.Place(transactionContext, executor, requestValue)
			return transactionErr
		})
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = spiceweb.WriteJSON(writer, http.StatusOK, responseValue)
	}), routeObservation0, routeMiddleware0...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route POST /orders: %w", routeErr))
	}
	return application, nil
}
