//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	sql "database/sql"
	fmt "fmt"
	slog "log/slog"
	http "net/http"
	strings "strings"
	time "time"

	spiceasync "github.com/StevenBuglione/spice/async"
	spicebean "github.com/StevenBuglione/spice/bean"
	spicecache "github.com/StevenBuglione/spice/cache"
	spiceconfig "github.com/StevenBuglione/spice/config"
	spicedata "github.com/StevenBuglione/spice/data"
	spiceevent "github.com/StevenBuglione/spice/event"
	inventory "github.com/StevenBuglione/spice/examples/commerce/inventory"
	notifications "github.com/StevenBuglione/spice/examples/commerce/notifications"
	orders "github.com/StevenBuglione/spice/examples/commerce/orders"
	payments "github.com/StevenBuglione/spice/examples/commerce/payments"
	platform "github.com/StevenBuglione/spice/examples/commerce/platform"
	storage "github.com/StevenBuglione/spice/examples/commerce/storage"
	spiceintercept "github.com/StevenBuglione/spice/intercept"
	spiceentrypoint "github.com/StevenBuglione/spice/internal/spicegen/commerce/sources/examples/commerce"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
	spiceschedule "github.com/StevenBuglione/spice/schedule"
	spicesecurity "github.com/StevenBuglione/spice/security"
	spiceweb "github.com/StevenBuglione/spice/web"
)

const TargetID = spiceentrypoint.ApplicationTargetCommerce_9d5bf597

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// ViewAudit is bean "newViewAudit".
	ViewAudit *orders.ViewAudit
	// OrderEvents is bean "OrderEvents".
	OrderEvents spiceevent.Publisher[orders.OrderViewed]
	// Mux is bean "mux".
	Mux *http.ServeMux
	// OrdersSettings is bean "Settings".
	OrdersSettings orders.Settings
	// OrderRepository is bean "orderRepository".
	OrderRepository *storage.OrderRepository
	// StorageSettings is bean "Settings".
	StorageSettings storage.Settings
	// OpenDatabase is bean "openDatabase".
	OpenDatabase *storage.Database
	// Native is bean "native".
	Native *sql.DB
	// ReadExecutor is bean "readExecutor".
	ReadExecutor spicedata.Executor
	// Transactions is bean "transactions".
	Transactions *spicedata.Manager
	// OfflineProcessor is bean "offlineProcessor".
	OfflineProcessor *payments.OfflineProcessor
	// PaymentsSettings is bean "Settings".
	PaymentsSettings payments.Settings
	// StripeProcessor is bean "stripeProcessor".
	StripeProcessor *payments.Service
	// PlatformSettings is bean "Settings".
	PlatformSettings platform.Settings
	// Server is bean "newServer".
	Server *platform.Server
	// InventorySettings is bean "Settings".
	InventorySettings inventory.Settings
	// InventoryService is bean "newService".
	InventoryService *inventory.Service
	// OrdersService is bean "newService".
	OrdersService *orders.Service
	// SystemClock is bean "systemClock".
	SystemClock *notifications.SystemClock
	// NotificationsSettings is bean "Settings".
	NotificationsSettings notifications.Settings
	// Delivery is bean "delivery".
	Delivery *notifications.Delivery
	// Notifier is bean "notifier".
	Notifier *notifications.Notifier
	// Controller is bean "controller".
	Controller *orders.Controller
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// ViewAudit replaces bean "newViewAudit".
	ViewAudit spicebean.Override[*orders.ViewAudit]
	// Mux replaces bean "mux".
	Mux spicebean.Override[*http.ServeMux]
	// OrderRepository replaces bean "orderRepository".
	OrderRepository spicebean.Override[*storage.OrderRepository]
	// OpenDatabase replaces bean "openDatabase".
	OpenDatabase spicebean.Override[*storage.Database]
	// Native replaces bean "native".
	Native spicebean.Override[*sql.DB]
	// ReadExecutor replaces bean "readExecutor".
	ReadExecutor spicebean.Override[spicedata.Executor]
	// Transactions replaces bean "transactions".
	Transactions spicebean.Override[*spicedata.Manager]
	// OfflineProcessor replaces bean "offlineProcessor".
	OfflineProcessor spicebean.Override[*payments.OfflineProcessor]
	// StripeProcessor replaces bean "stripeProcessor".
	StripeProcessor spicebean.Override[*payments.Service]
	// Server replaces bean "newServer".
	Server spicebean.Override[*platform.Server]
	// InventoryService replaces bean "newService".
	InventoryService spicebean.Override[*inventory.Service]
	// OrdersService replaces bean "newService".
	OrdersService spicebean.Override[*orders.Service]
	// SystemClock replaces bean "systemClock".
	SystemClock spicebean.Override[*notifications.SystemClock]
	// Delivery replaces bean "delivery".
	Delivery spicebean.Override[*notifications.Delivery]
	// Notifier replaces bean "notifier".
	Notifier spicebean.Override[*notifications.Notifier]
	// Controller replaces bean "controller".
	Controller spicebean.Override[*orders.Controller]
}

// BeanOverrideLayer is one named immutable override composition layer.
// Layers are applied in order; a later layer deliberately replaces an earlier value.
type BeanOverrideLayer struct {
	Name      string
	Overrides BeanOverrides
}

// ComposeBeanOverrides validates and deterministically composes named layers.
// It never mutates a running application or performs runtime bean lookup.
func ComposeBeanOverrides(layers ...BeanOverrideLayer) (BeanOverrides, error) {
	result := BeanOverrides{}
	seen := make(map[string]int, len(layers))
	for index, layer := range layers {
		if layer.Name == "" || strings.TrimSpace(layer.Name) != layer.Name {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %d requires a non-empty name without surrounding whitespace", index)
		}
		if previous, duplicate := seen[layer.Name]; duplicate {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %q repeats layer %d", layer.Name, previous)
		}
		seen[layer.Name] = index
		if layer.Overrides.ViewAudit.Enabled() {
			result.ViewAudit = layer.Overrides.ViewAudit
		}
		if layer.Overrides.Mux.Enabled() {
			result.Mux = layer.Overrides.Mux
		}
		if layer.Overrides.OrderRepository.Enabled() {
			result.OrderRepository = layer.Overrides.OrderRepository
		}
		if layer.Overrides.OpenDatabase.Enabled() {
			result.OpenDatabase = layer.Overrides.OpenDatabase
		}
		if layer.Overrides.Native.Enabled() {
			result.Native = layer.Overrides.Native
		}
		if layer.Overrides.ReadExecutor.Enabled() {
			result.ReadExecutor = layer.Overrides.ReadExecutor
		}
		if layer.Overrides.Transactions.Enabled() {
			result.Transactions = layer.Overrides.Transactions
		}
		if layer.Overrides.OfflineProcessor.Enabled() {
			result.OfflineProcessor = layer.Overrides.OfflineProcessor
		}
		if layer.Overrides.StripeProcessor.Enabled() {
			result.StripeProcessor = layer.Overrides.StripeProcessor
		}
		if layer.Overrides.Server.Enabled() {
			result.Server = layer.Overrides.Server
		}
		if layer.Overrides.InventoryService.Enabled() {
			result.InventoryService = layer.Overrides.InventoryService
		}
		if layer.Overrides.OrdersService.Enabled() {
			result.OrdersService = layer.Overrides.OrdersService
		}
		if layer.Overrides.SystemClock.Enabled() {
			result.SystemClock = layer.Overrides.SystemClock
		}
		if layer.Overrides.Delivery.Enabled() {
			result.Delivery = layer.Overrides.Delivery
		}
		if layer.Overrides.Notifier.Enabled() {
			result.Notifier = layer.Overrides.Notifier
		}
		if layer.Overrides.Controller.Enabled() {
			result.Controller = layer.Overrides.Controller
		}
	}
	return result, nil
}

// RouteInterceptors configures typed generated route method decorators.
// The first interceptor in each field is the outermost invocation.
type RouteInterceptors struct {
	ControllerCatalog     []spiceintercept.Interceptor[orders.CatalogRequest, orders.CatalogResponse]
	ControllerGet         []spiceintercept.Interceptor[orders.GetOrderRequest, orders.OrderResponse]
	ControllerPlace       []spiceintercept.Interceptor[orders.PlaceOrderRequest, orders.OrderResponse]
	ControllerSendReceipt []spiceintercept.Interceptor[orders.ReceiptRequest, orders.ReceiptResponse]
}

type Application struct {
	coordinator            *spicelifecycle.Coordinator
	hooks                  []spicelifecycle.Hook
	shutdownTimeout        time.Duration
	components             Components
	asyncExecutor          *spiceasync.Executor
	submitServiceVerifySKU func(context.Context, string) error
	mux                    *http.ServeMux
	handler                http.Handler
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	ErrorMapper               spiceweb.ErrorMapper
	MaxRequestBodyBytes       int64
	HTTPObservers             []spiceweb.HTTPObserver
	Middleware                []spiceweb.Middleware
	Interceptors              RouteInterceptors
	AuthorizationObservers    []spicesecurity.Observer
	AuthorizationWriteFailure spicesecurity.WriteFailure
	Logger                    *slog.Logger
	ScheduleContext           context.Context
	ScheduleWaiter            spiceschedule.Waiter
	ScheduleObservers         []spiceschedule.Observer
	AsyncContext              context.Context
	AsyncObservers            []spiceasync.Observer
	EventObservers            []spiceevent.Observer
	CacheClock                func() time.Time
	CacheObservers            []spicecache.Observer
	Observers                 []spicelifecycle.Observer
}
