//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	sql "database/sql"
	fmt "fmt"
	http "net/http"

	spiceconfig "github.com/StevenBuglione/spice/config"
	spicedata "github.com/StevenBuglione/spice/data"
	spiceevent "github.com/StevenBuglione/spice/event"
	inventory "github.com/StevenBuglione/spice/examples/commerce/inventory"
	notifications "github.com/StevenBuglione/spice/examples/commerce/notifications"
	orders "github.com/StevenBuglione/spice/examples/commerce/orders"
	payments "github.com/StevenBuglione/spice/examples/commerce/payments"
	platform "github.com/StevenBuglione/spice/examples/commerce/platform"
	storage "github.com/StevenBuglione/spice/examples/commerce/storage"
	spiceInventory "github.com/StevenBuglione/spice/internal/spicegen/commerce/sources/examples/commerce/inventory"
	spiceNotifications "github.com/StevenBuglione/spice/internal/spicegen/commerce/sources/examples/commerce/notifications"
	spiceOrders "github.com/StevenBuglione/spice/internal/spicegen/commerce/sources/examples/commerce/orders"
	spicePayments "github.com/StevenBuglione/spice/internal/spicegen/commerce/sources/examples/commerce/payments"
	spicePlatform "github.com/StevenBuglione/spice/internal/spicegen/commerce/sources/examples/commerce/platform"
	spiceStorage "github.com/StevenBuglione/spice/internal/spicegen/commerce/sources/examples/commerce/storage"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

type applicationDependencies struct {
	viewAudit             *orders.ViewAudit
	orderEvents           spiceevent.Publisher[orders.OrderViewed]
	mux                   *http.ServeMux
	ordersSettings        orders.Settings
	orderRepository       *storage.OrderRepository
	storageSettings       storage.Settings
	openDatabase          *storage.Database
	native                *sql.DB
	readExecutor          spicedata.Executor
	transactions          *spicedata.Manager
	offlineProcessor      *payments.OfflineProcessor
	paymentsSettings      payments.Settings
	stripeProcessor       *payments.Service
	platformSettings      platform.Settings
	server                *platform.Server
	inventorySettings     inventory.Settings
	inventoryService      *inventory.Service
	ordersService         *orders.Service
	systemClock           *notifications.SystemClock
	notificationsSettings notifications.Settings
	delivery              *notifications.Delivery
	notifier              *notifications.Notifier
	controller            *orders.Controller
}

func constructApplicationDependencies(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
) (*applicationDependencies, error) {
	_ = ctx
	_ = application
	_ = options
	_ = configurationSnapshot
	viewAudit, viewAuditCleanup, err := func() (*orders.ViewAudit, spicelifecycle.Cleanup, error) {
		if options.Overrides.ViewAudit.Enabled() {
			return options.Overrides.ViewAudit.Acquire(ctx)
		}
		return spiceOrders.ConstructViewAudit_ab6c60ed()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean newViewAudit (*github.com/StevenBuglione/spice/examples/commerce/orders.ViewAudit, source spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|12:NewViewAudit): %w", err))
	}
	if viewAuditCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/orders", "spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|12:NewViewAudit", viewAuditCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean newViewAudit (source spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|12:NewViewAudit): %w", err))
		}
	}
	_ = viewAudit
	orderEventsTopic, err := spiceevent.NewTopic(
		spiceevent.Definition{
			ID:     "spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|11:OrderEvents",
			Module: "github.com/StevenBuglione/spice/examples/commerce/orders",
		},
		[]spiceevent.Subscriber[orders.OrderViewed]{
			{
				ID:     "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/commerce/orders|9:ViewAudit|6:Record",
				Module: "github.com/StevenBuglione/spice/examples/commerce/orders",
				Order:  10,
				Handle: viewAudit.Record,
			},
		},
		options.EventObservers...,
	)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct event topic spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|11:OrderEvents (github.com/StevenBuglione/spice/event.Publisher[github.com/StevenBuglione/spice/examples/commerce/orders.OrderViewed]): %w", err))
	}
	var orderEvents spiceevent.Publisher[orders.OrderViewed] = orderEventsTopic
	_ = orderEvents
	mux, muxCleanup, err := func() (*http.ServeMux, spicelifecycle.Cleanup, error) {
		if options.Overrides.Mux.Enabled() {
			return options.Overrides.Mux.Acquire(ctx)
		}
		return spicePlatform.ConstructMux_4f4cdf49()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean mux (*net/http.ServeMux, source spice:symbol:v1|function|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|3:Mux): %w", err))
	}
	if muxCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/platform", "spice:symbol:v1|function|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|3:Mux", muxCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean mux (source spice:symbol:v1|function|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|3:Mux): %w", err))
		}
	}
	_ = mux
	ordersSettings, err := spiceOrders.BindSettings_59ba7b6b(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/StevenBuglione/spice/examples/commerce/orders.Settings for bean Settings (source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|8:Settings): %w", err))
	}
	_ = ordersSettings
	orderRepository, orderRepositoryCleanup, err := func() (*storage.OrderRepository, spicelifecycle.Cleanup, error) {
		if options.Overrides.OrderRepository.Enabled() {
			return options.Overrides.OrderRepository.Acquire(ctx)
		}
		return spiceStorage.ConstructOrderRepository_abe0e37d()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean orderRepository (*github.com/StevenBuglione/spice/examples/commerce/storage.OrderRepository, source spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|15:OrderRepository): %w", err))
	}
	if orderRepositoryCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/storage", "spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|15:OrderRepository", orderRepositoryCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean orderRepository (source spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|15:OrderRepository): %w", err))
		}
	}
	_ = orderRepository
	storageSettings, err := spiceStorage.BindSettings_ee0cda8a(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/StevenBuglione/spice/examples/commerce/storage.Settings for bean Settings (source spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|8:Settings): %w", err))
	}
	_ = storageSettings
	openDatabase, openDatabaseCleanup, err := func() (*storage.Database, spicelifecycle.Cleanup, error) {
		if options.Overrides.OpenDatabase.Enabled() {
			return options.Overrides.OpenDatabase.Acquire(ctx)
		}
		return spiceStorage.ConstructOpenDatabase_cf56637a(storageSettings)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean openDatabase (*github.com/StevenBuglione/spice/examples/commerce/storage.Database, source spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|12:OpenDatabase): %w", err))
	}
	if openDatabaseCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/storage", "spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|12:OpenDatabase", openDatabaseCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean openDatabase (source spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|12:OpenDatabase): %w", err))
		}
	}
	_ = openDatabase
	native, nativeCleanup, err := func() (*sql.DB, spicelifecycle.Cleanup, error) {
		if options.Overrides.Native.Enabled() {
			return options.Overrides.Native.Acquire(ctx)
		}
		return spiceStorage.ConstructNative_b4ba2b27(openDatabase)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean native (*database/sql.DB, source spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|6:Native): %w", err))
	}
	if nativeCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/storage", "spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|6:Native", nativeCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean native (source spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|6:Native): %w", err))
		}
	}
	_ = native
	readExecutor, readExecutorCleanup, err := func() (spicedata.Executor, spicelifecycle.Cleanup, error) {
		if options.Overrides.ReadExecutor.Enabled() {
			return options.Overrides.ReadExecutor.Acquire(ctx)
		}
		return spiceStorage.ConstructReadExecutor_942a3a82(native)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean readExecutor (github.com/StevenBuglione/spice/data.Executor, source spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|12:ReadExecutor): %w", err))
	}
	if readExecutorCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/storage", "spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|12:ReadExecutor", readExecutorCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean readExecutor (source spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|12:ReadExecutor): %w", err))
		}
	}
	_ = readExecutor
	transactions, transactionsCleanup, err := func() (*spicedata.Manager, spicelifecycle.Cleanup, error) {
		if options.Overrides.Transactions.Enabled() {
			return options.Overrides.Transactions.Acquire(ctx)
		}
		return spiceStorage.ConstructTransactions_18761080(native)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean transactions (*github.com/StevenBuglione/spice/data.Manager, source spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|12:Transactions): %w", err))
	}
	if transactionsCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/storage", "spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|12:Transactions", transactionsCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean transactions (source spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|12:Transactions): %w", err))
		}
	}
	_ = transactions
	offlineProcessor, offlineProcessorCleanup, err := func() (*payments.OfflineProcessor, spicelifecycle.Cleanup, error) {
		if options.Overrides.OfflineProcessor.Enabled() {
			return options.Overrides.OfflineProcessor.Acquire(ctx)
		}
		return spicePayments.ConstructOfflineProcessor_863e8c2d()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean offlineProcessor (*github.com/StevenBuglione/spice/examples/commerce/payments.OfflineProcessor, source spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/payments|0:|16:OfflineProcessor): %w", err))
	}
	if offlineProcessorCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/payments", "spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/payments|0:|16:OfflineProcessor", offlineProcessorCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean offlineProcessor (source spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/payments|0:|16:OfflineProcessor): %w", err))
		}
	}
	_ = offlineProcessor
	paymentsSettings, err := spicePayments.BindSettings_e69fa000(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/StevenBuglione/spice/examples/commerce/payments.Settings for bean Settings (source spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/payments|0:|8:Settings): %w", err))
	}
	_ = paymentsSettings
	stripeProcessor, stripeProcessorCleanup, err := func() (*payments.Service, spicelifecycle.Cleanup, error) {
		if options.Overrides.StripeProcessor.Enabled() {
			return options.Overrides.StripeProcessor.Acquire(ctx)
		}
		return spicePayments.ConstructStripeProcessor_c8223730(paymentsSettings)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean stripeProcessor (*github.com/StevenBuglione/spice/examples/commerce/payments.Service, source spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/payments|0:|7:Service): %w", err))
	}
	if stripeProcessorCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/payments", "spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/payments|0:|7:Service", stripeProcessorCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean stripeProcessor (source spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/payments|0:|7:Service): %w", err))
		}
	}
	_ = stripeProcessor
	platformSettings, err := spicePlatform.BindSettings_bd78ddfa(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/StevenBuglione/spice/examples/commerce/platform.Settings for bean Settings (source spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|8:Settings): %w", err))
	}
	_ = platformSettings
	server, serverCleanup, err := func() (*platform.Server, spicelifecycle.Cleanup, error) {
		if options.Overrides.Server.Enabled() {
			return options.Overrides.Server.Acquire(ctx)
		}
		return spicePlatform.ConstructServer_593d6230(platformSettings, mux, openDatabase)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean newServer (*github.com/StevenBuglione/spice/examples/commerce/platform.Server, source spice:symbol:v1|function|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|9:NewServer): %w", err))
	}
	if serverCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/platform", "spice:symbol:v1|function|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|9:NewServer", serverCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean newServer (source spice:symbol:v1|function|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|9:NewServer): %w", err))
		}
	}
	_ = server
	inventorySettings, err := spiceInventory.BindSettings_8a49b112(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/StevenBuglione/spice/examples/commerce/inventory.Settings for bean Settings (source spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/commerce/inventory|0:|8:Settings): %w", err))
	}
	_ = inventorySettings
	inventoryService, inventoryServiceCleanup, err := func() (*inventory.Service, spicelifecycle.Cleanup, error) {
		if options.Overrides.InventoryService.Enabled() {
			return options.Overrides.InventoryService.Acquire(ctx)
		}
		return spiceInventory.ConstructService_538781be(inventorySettings)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean newService (*github.com/StevenBuglione/spice/examples/commerce/inventory.Service, source spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/commerce/inventory|0:|10:NewService): %w", err))
	}
	if inventoryServiceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/inventory", "spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/commerce/inventory|0:|10:NewService", inventoryServiceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean newService (source spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/commerce/inventory|0:|10:NewService): %w", err))
		}
	}
	_ = inventoryService
	ordersService, ordersServiceCleanup, err := func() (*orders.Service, spicelifecycle.Cleanup, error) {
		if options.Overrides.OrdersService.Enabled() {
			return options.Overrides.OrdersService.Acquire(ctx)
		}
		return spiceOrders.ConstructService_ce92b74a(ordersSettings, inventoryService, stripeProcessor, orderEvents, orderRepository, readExecutor)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean newService (*github.com/StevenBuglione/spice/examples/commerce/orders.Service, source spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|10:NewService): %w", err))
	}
	if ordersServiceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/orders", "spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|10:NewService", ordersServiceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean newService (source spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|10:NewService): %w", err))
		}
	}
	_ = ordersService
	systemClock, systemClockCleanup, err := func() (*notifications.SystemClock, spicelifecycle.Cleanup, error) {
		if options.Overrides.SystemClock.Enabled() {
			return options.Overrides.SystemClock.Acquire(ctx)
		}
		return spiceNotifications.ConstructSystemClock_6232152b()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean systemClock (*github.com/StevenBuglione/spice/examples/commerce/notifications.SystemClock, source spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|11:SystemClock): %w", err))
	}
	if systemClockCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/notifications", "spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|11:SystemClock", systemClockCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean systemClock (source spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|11:SystemClock): %w", err))
		}
	}
	_ = systemClock
	notificationsSettings, err := spiceNotifications.BindSettings_d8b9beed(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/StevenBuglione/spice/examples/commerce/notifications.Settings for bean Settings (source spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|8:Settings): %w", err))
	}
	_ = notificationsSettings
	delivery, deliveryCleanup, err := func() (*notifications.Delivery, spicelifecycle.Cleanup, error) {
		if options.Overrides.Delivery.Enabled() {
			return options.Overrides.Delivery.Acquire(ctx)
		}
		return spiceNotifications.ConstructDelivery_89970054(notificationsSettings)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean delivery (*github.com/StevenBuglione/spice/examples/commerce/notifications.Delivery, source spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|8:Delivery): %w", err))
	}
	if deliveryCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/notifications", "spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|8:Delivery", deliveryCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean delivery (source spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|8:Delivery): %w", err))
		}
	}
	_ = delivery
	notifier, notifierCleanup, err := func() (*notifications.Notifier, spicelifecycle.Cleanup, error) {
		if options.Overrides.Notifier.Enabled() {
			return options.Overrides.Notifier.Acquire(ctx)
		}
		return spiceNotifications.ConstructNotifier_f5f0b515(notificationsSettings, delivery, delivery, systemClock)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean notifier (*github.com/StevenBuglione/spice/examples/commerce/notifications.Notifier, source spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|8:Notifier): %w", err))
	}
	if notifierCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/notifications", "spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|8:Notifier", notifierCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean notifier (source spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|8:Notifier): %w", err))
		}
	}
	_ = notifier
	controller, controllerCleanup, err := func() (*orders.Controller, spicelifecycle.Cleanup, error) {
		if options.Overrides.Controller.Enabled() {
			return options.Overrides.Controller.Acquire(ctx)
		}
		return spiceOrders.ConstructController_c33744ce(ordersService, notifier)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean controller (*github.com/StevenBuglione/spice/examples/commerce/orders.Controller, source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|10:Controller): %w", err))
	}
	if controllerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce/orders", "spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|10:Controller", controllerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean controller (source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/commerce/orders|0:|10:Controller): %w", err))
		}
	}
	_ = controller
	return &applicationDependencies{
		viewAudit:             viewAudit,
		orderEvents:           orderEvents,
		mux:                   mux,
		ordersSettings:        ordersSettings,
		orderRepository:       orderRepository,
		storageSettings:       storageSettings,
		openDatabase:          openDatabase,
		native:                native,
		readExecutor:          readExecutor,
		transactions:          transactions,
		offlineProcessor:      offlineProcessor,
		paymentsSettings:      paymentsSettings,
		stripeProcessor:       stripeProcessor,
		platformSettings:      platformSettings,
		server:                server,
		inventorySettings:     inventorySettings,
		inventoryService:      inventoryService,
		ordersService:         ordersService,
		systemClock:           systemClock,
		notificationsSettings: notificationsSettings,
		delivery:              delivery,
		notifier:              notifier,
		controller:            controller,
	}, nil
}
