//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	spiceasync "github.com/StevenBuglione/spice/async"
	spiceconfig "github.com/StevenBuglione/spice/config"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
	spiceschedule "github.com/StevenBuglione/spice/schedule"
)

func configureGeneratedAsync(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
) (*Application, error) {
	_ = dependencies
	asyncConcurrency, err := configurationSnapshot.Integer("spice.async.max-concurrency")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode generated async concurrency: %w", err))
	}
	if asyncConcurrency < 1 || uint64(asyncConcurrency) > uint64(^uint(0)>>1) {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode generated async concurrency: value must fit a positive int"))
	}
	asyncContext := options.AsyncContext
	if asyncContext == nil {
		asyncContext = context.WithoutCancel(ctx)
	}
	generatedAsyncExecutor, err := spiceasync.NewExecutor(
		asyncContext,
		int(asyncConcurrency),
		options.AsyncObservers...,
	)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct generated async executor: %w", err))
	}
	if err := application.coordinator.RegisterModuleCleanup("github.com/StevenBuglione/spice/examples/commerce", "spice.async", generatedAsyncExecutor.Shutdown); err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated async cleanup: %w", err))
	}
	application.asyncExecutor = generatedAsyncExecutor
	application.submitServiceVerifySKU = func(admission context.Context, argument1 string) error {
		return generatedAsyncExecutor.Submit(
			admission,
			spiceasync.Definition{
				ID:     "spice:symbol:v1|method|59:github.com/StevenBuglione/spice/examples/commerce/inventory|7:Service|9:VerifySKU",
				Module: "github.com/StevenBuglione/spice/examples/commerce/inventory",
			},
			func(taskContext context.Context) error {
				return dependencies.inventoryService.VerifySKU(taskContext, argument1)
			},
		)
	}
	return application, nil
}

func configureGeneratedLifecycle(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	dependencies *applicationDependencies,
) (*Application, error) {
	_ = ctx
	_ = options
	_ = dependencies
	scheduleContext := options.ScheduleContext
	if scheduleContext == nil {
		scheduleContext = context.WithoutCancel(ctx)
	}
	generatedScheduler, err := spiceschedule.New(
		scheduleContext,
		[]spiceschedule.Job{
			{
				Definition: spiceschedule.Definition{
					ID:     "spice:symbol:v1|method|59:github.com/StevenBuglione/spice/examples/commerce/inventory|7:Service|5:Audit",
					Module: "github.com/StevenBuglione/spice/examples/commerce/inventory",
				},
				InitialDelay: 30000000000,
				Delay:        300000000000,
				Run:          dependencies.inventoryService.Audit,
			},
		},
		options.ScheduleWaiter,
		options.ScheduleObservers...,
	)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct generated scheduler: %w", err))
	}
	application.hooks = []spicelifecycle.Hook{
		{
			ID:     "spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|12:OpenDatabase",
			Module: "github.com/StevenBuglione/spice/examples/commerce/storage",
			Start:  dependencies.openDatabase.Migrate,
		},
		{
			ID:     "spice:symbol:v1|function|58:github.com/StevenBuglione/spice/examples/commerce/platform|0:|9:NewServer",
			Module: "github.com/StevenBuglione/spice/examples/commerce/platform",
			Start:  dependencies.server.Start,
			Stop:   dependencies.server.Stop,
		},
		{
			ID:     "spice.schedule",
			Module: "github.com/StevenBuglione/spice/examples/commerce",
			Start:  generatedScheduler.Start,
			Stop:   generatedScheduler.Shutdown,
		},
	}
	return application, nil
}
