//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	spiceconfig "github.com/StevenBuglione/spice/config"
	spicemanagement "github.com/StevenBuglione/spice/management"
	spicesecurity "github.com/StevenBuglione/spice/security"
	spiceweb "github.com/StevenBuglione/spice/web"
)

func configureGeneratedHTTP(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSchema spiceconfig.Schema,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
	httpObservers []spiceweb.HTTPObserver,
	managementMetrics *spicemanagement.HTTPMetrics,
	authorizer *spicesecurity.Authorizer,
) (*Application, error) {
	_ = configurationSchema
	_ = configurationSnapshot
	_ = dependencies
	_ = httpObservers
	routeMux := dependencies.provider2
	application.mux = routeMux
	application.handler = routeMux
	if _, err := registerGeneratedRoute125c6a7a37a0(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
		authorizer,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute8c548c3f0ad4(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
		authorizer,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoutefbc15ec550e7(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
		authorizer,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute04b28d782ae7(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
		authorizer,
	); err != nil {
		return nil, err
	}
	managementChecks, err := spicemanagement.LifecycleChecks(TargetID, "github.com/StevenBuglione/spice/examples/commerce", application.State)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management lifecycle checks: %w", err))
	}
	managementManager, err := spicemanagement.New(managementChecks...)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management checks: %w", err))
	}
	managementConfiguration, err := spicemanagement.NewConfigurationReport(configurationSchema, configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management configuration report: %w", err))
	}
	managementModules, err := spicemanagement.NewModuleReport(
		[]spicemanagement.ModuleDefinition{
			{
				ID:          "github.com/StevenBuglione/spice/examples/commerce/inventory",
				RootPackage: "github.com/StevenBuglione/spice/examples/commerce/inventory",
				Packages: []string{
					"github.com/StevenBuglione/spice/examples/commerce/inventory",
				},
			},
			{
				ID:          "github.com/StevenBuglione/spice/examples/commerce/notifications",
				RootPackage: "github.com/StevenBuglione/spice/examples/commerce/notifications",
				Packages: []string{
					"github.com/StevenBuglione/spice/examples/commerce/notifications",
				},
			},
			{
				ID:          "github.com/StevenBuglione/spice/examples/commerce/orders",
				RootPackage: "github.com/StevenBuglione/spice/examples/commerce/orders",
				Packages: []string{
					"github.com/StevenBuglione/spice/examples/commerce/orders",
				},
				AllowedDependencies: []string{
					"github.com/StevenBuglione/spice/examples/commerce/inventory",
					"github.com/StevenBuglione/spice/examples/commerce/notifications",
					"github.com/StevenBuglione/spice/examples/commerce/payments",
					"github.com/StevenBuglione/spice/examples/commerce/storage",
				},
			},
			{
				ID:          "github.com/StevenBuglione/spice/examples/commerce/payments",
				RootPackage: "github.com/StevenBuglione/spice/examples/commerce/payments",
				Packages: []string{
					"github.com/StevenBuglione/spice/examples/commerce/payments",
				},
			},
			{
				ID:          "github.com/StevenBuglione/spice/examples/commerce/platform",
				RootPackage: "github.com/StevenBuglione/spice/examples/commerce/platform",
				Packages: []string{
					"github.com/StevenBuglione/spice/examples/commerce/platform",
				},
				AllowedDependencies: []string{
					"github.com/StevenBuglione/spice/examples/commerce/storage",
				},
			},
			{
				ID:          "github.com/StevenBuglione/spice/examples/commerce/storage",
				RootPackage: "github.com/StevenBuglione/spice/examples/commerce/storage",
				Packages: []string{
					"github.com/StevenBuglione/spice/examples/commerce/storage",
				},
			},
		},
		[]spicemanagement.ModuleEdge{
			{FromModule: "github.com/StevenBuglione/spice/examples/commerce/orders", ToModule: "github.com/StevenBuglione/spice/examples/commerce/inventory", API: "default", FromPackage: "github.com/StevenBuglione/spice/examples/commerce/orders", ToPackage: "github.com/StevenBuglione/spice/examples/commerce/inventory"},
			{FromModule: "github.com/StevenBuglione/spice/examples/commerce/orders", ToModule: "github.com/StevenBuglione/spice/examples/commerce/notifications", API: "default", FromPackage: "github.com/StevenBuglione/spice/examples/commerce/orders", ToPackage: "github.com/StevenBuglione/spice/examples/commerce/notifications"},
			{FromModule: "github.com/StevenBuglione/spice/examples/commerce/orders", ToModule: "github.com/StevenBuglione/spice/examples/commerce/payments", API: "default", FromPackage: "github.com/StevenBuglione/spice/examples/commerce/orders", ToPackage: "github.com/StevenBuglione/spice/examples/commerce/payments"},
			{FromModule: "github.com/StevenBuglione/spice/examples/commerce/orders", ToModule: "github.com/StevenBuglione/spice/examples/commerce/storage", API: "default", FromPackage: "github.com/StevenBuglione/spice/examples/commerce/orders", ToPackage: "github.com/StevenBuglione/spice/examples/commerce/storage"},
			{FromModule: "github.com/StevenBuglione/spice/examples/commerce/platform", ToModule: "github.com/StevenBuglione/spice/examples/commerce/storage", API: "default", FromPackage: "github.com/StevenBuglione/spice/examples/commerce/platform", ToPackage: "github.com/StevenBuglione/spice/examples/commerce/storage"},
		},
		[]string{
			"github.com/StevenBuglione/spice/examples/commerce",
		},
	)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management module report: %w", err))
	}
	managementHandler, err := spicemanagement.NewHandler(spicemanagement.HandlerOptions{
		Manager: managementManager,
		Info: map[string]string{
			"application": TargetID,
			"module":      "github.com/StevenBuglione/spice/examples/commerce",
			"framework":   "Spice",
		},
		Metrics:       managementMetrics,
		Configuration: &managementConfiguration,
		Modules:       &managementModules,
		Expose: []spicemanagement.Endpoint{
			spicemanagement.EndpointConfigProps,
			spicemanagement.EndpointHealth,
			spicemanagement.EndpointInfo,
			spicemanagement.EndpointLiveness,
			spicemanagement.EndpointMetrics,
			spicemanagement.EndpointModules,
			spicemanagement.EndpointReadiness,
		},
		Access: spicemanagement.Access("loopback"),
	})
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management handler: %w", err))
	}
	if err := spiceweb.Register(routeMux, managementHandler.Pattern(), managementHandler); err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register management routes: %w", err))
	}
	return application, nil
}
