package genfs

import (
	"context"
	"encoding/json"
	"errors"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/spice-framework/spice/compiler/application"
	"github.com/spice-framework/spice/compiler/generate"
	"github.com/spice-framework/spice/compiler/load"
	"github.com/spice-framework/spice/compiler/resolve"
	"github.com/spice-framework/spice/internal/testannotation"
)

func TestApplyCreatesChecksAndPreservesUnchangedFiles(t *testing.T) {
	root := generationModule(t)
	plan := renderPlan(t, root, applicationSource)

	status, err := Check(plan)
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if status.Current ||
		!hasDifference(status, DifferenceMissingManifest) ||
		!hasDifference(status, DifferenceMissingFile) {
		t.Fatalf("initial Check() = %#v", status)
	}
	diff, err := Diff(plan)
	if err != nil {
		t.Fatalf("Diff() error = %v", err)
	}
	for _, expected := range []string{
		"--- a/internal/spicegen/application/spice_assembly_gen.go",
		"+++ b/internal/spicegen/application/spice_assembly_gen.go",
		"+// Code generated by Spice. DO NOT EDIT.",
	} {
		if !strings.Contains(diff, expected) {
			t.Fatalf("Diff() missing %q:\n%s", expected, diff)
		}
	}

	result, err := Apply(plan)
	if err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	if !result.Changed() ||
		!result.ManifestUpdated ||
		!slices.Equal(result.Written, generatedPaths(plan)) ||
		len(result.Removed) != 0 {
		t.Fatalf("Apply() = %#v", result)
	}
	generatedPath := filepath.Join(
		root,
		"internal",
		"spicegen",
		"application",
		"spice_assembly_gen.go",
	)
	manifestPath := filepath.Join(root, ".spice", "application.manifest.json")
	generatedInfo := mustStat(t, generatedPath)
	manifestInfo := mustStat(t, manifestPath)

	status, err = Check(plan)
	if err != nil || !status.Current || len(status.Differences) != 0 {
		t.Fatalf("current Check() = %#v, %v", status, err)
	}
	if diff, err = Diff(plan); err != nil || diff != "" {
		t.Fatalf("current Diff() = %q, %v", diff, err)
	}
	result, err = Apply(plan)
	if err != nil {
		t.Fatalf("second Apply() error = %v", err)
	}
	if result.Changed() {
		t.Fatalf("second Apply() = %#v, want no changes", result)
	}
	if got := mustStat(t, generatedPath).ModTime(); !got.Equal(generatedInfo.ModTime()) {
		t.Fatalf("unchanged generated mtime = %v, want %v", got, generatedInfo.ModTime())
	}
	if got := mustStat(t, manifestPath).ModTime(); !got.Equal(manifestInfo.ModTime()) {
		t.Fatalf("unchanged manifest mtime = %v, want %v", got, manifestInfo.ModTime())
	}
	if _, err := os.Stat(filepath.Join(root, ".spice", "application.lock")); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("generation lock remains after Apply: %v", err)
	}
}

func TestApplyApplicationPackagePreservesHandwrittenSource(t *testing.T) {
	tests := []struct {
		name       string
		sourcePath string
		pattern    string
		outputDir  string
	}{
		{
			name:       "nested command",
			sourcePath: "cmd/shop/main.go",
			pattern:    "./...",
			outputDir:  "internal/spicegen/shop",
		},
		{
			name:       "module root command",
			sourcePath: "main.go",
			pattern:    ".",
			outputDir:  "internal/spicegen/genfs",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := generationModule(t)
			targetID := path.Base(path.Dir(test.sourcePath))
			if path.Dir(test.sourcePath) == "." {
				targetID = "genfs"
			}
			source := mainApplicationSource(targetID)
			plan := renderMainPlan(
				t,
				root,
				test.sourcePath,
				test.pattern,
				source,
			)
			if plan.Target().Layout != generate.LayoutApplicationPackage ||
				plan.Target().OutputDir != test.outputDir ||
				plan.Target().BridgeDir !=
					path.Dir(filepath.ToSlash(test.sourcePath)) {
				t.Fatalf("Target() = %#v", plan.Target())
			}
			result, err := Apply(plan)
			if err != nil {
				t.Fatalf("Apply() error = %v", err)
			}
			if !result.Changed() {
				t.Fatalf("Apply() = %#v", result)
			}
			sourcePath := filepath.Join(
				root,
				filepath.FromSlash(test.sourcePath),
			)
			if content := mustRead(t, sourcePath); !slices.Equal(content, source) {
				t.Fatalf("handwritten source changed:\n%s", content)
			}
			status, err := Check(plan)
			if err != nil || !status.Current {
				t.Fatalf("Check() = %#v, %v", status, err)
			}
		})
	}
}

func TestApplicationPackageUnexpectedMarkerScanIsPackageLocal(t *testing.T) {
	root := generationModule(t)
	plan := renderMainPlan(
		t,
		root,
		"cmd/shop/main.go",
		"./...",
		mainApplicationSource("shop"),
	)
	if _, err := Apply(plan); err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	nested := filepath.Join(root, "cmd", "shop", "feature", "generated.go")
	writeFile(t, nested, []byte(generatedMarker+"\n\npackage feature\n"))
	status, err := Check(plan)
	if err != nil || !status.Current {
		t.Fatalf("Check(nested package marker) = %#v, %v", status, err)
	}
	direct := filepath.Join(root, "cmd", "shop", "foreign.go")
	writeFile(t, direct, []byte(generatedMarker+"\n\npackage main\n"))
	status, err = Check(plan)
	if err != nil ||
		!hasDifference(status, DifferenceUnexpectedGenerated) {
		t.Fatalf("Check(direct package marker) = %#v, %v", status, err)
	}
}

func TestApplyMigratesUnchangedLegacyGeneratedPackageOwnership(t *testing.T) {
	root := generationModule(t)
	legacyPlan := renderPlan(t, root, applicationSource)
	for _, file := range legacyPlan.Files() {
		writeFile(
			t,
			filepath.Join(root, filepath.FromSlash(file.Path)),
			file.Content(),
		)
	}
	legacyManifest := legacyPlan.Manifest()
	legacyManifest.Schema = 1
	legacyManifest.Target.Layout = ""
	writeManifest(
		t,
		filepath.Join(
			root,
			filepath.FromSlash(legacyPlan.Target().ManifestPath),
		),
		legacyManifest,
	)
	if err := os.Remove(filepath.Join(root, "app", "application.go")); err != nil {
		t.Fatal(err)
	}
	plan := renderMainPlan(
		t,
		root,
		"cmd/application/main.go",
		"./...",
		mainApplicationSource("application"),
	)
	status, err := Check(plan)
	if err != nil ||
		!hasDifference(status, DifferenceMissingFile) {
		t.Fatalf("Check(legacy migration) = %#v, %v", status, err)
	}
	result, err := Apply(plan)
	if err != nil {
		t.Fatalf("Apply(legacy migration) error = %v", err)
	}
	if !slices.Equal(
		result.Removed,
		[]string{
			"internal/spicegen/application/sources/app/application_spice_gen.go",
		},
	) ||
		!slices.Equal(
			result.Written,
			[]string{
				"internal/spicegen/application/sources/cmd/application/main_spice_gen.go",
				"internal/spicegen/application/spice_contracts_gen.go",
			},
		) ||
		!result.ManifestUpdated {
		t.Fatalf("Apply(legacy migration) = %#v", result)
	}
	if _, err := os.Stat(filepath.Join(
		root,
		"internal",
		"spicegen",
		"application",
		"spice_contracts_gen.go",
	)); err != nil {
		t.Fatalf("migrated generated application is missing: %v", err)
	}
}

func TestApplyRefusesModifiedLegacyGeneratedPackageMigration(t *testing.T) {
	root := generationModule(t)
	legacyPlan := renderPlan(t, root, applicationSource)
	legacyFile := legacyPlan.Files()[0]
	legacyPath := filepath.Join(root, filepath.FromSlash(legacyFile.Path))
	writeFile(t, legacyPath, append(legacyFile.Content(), []byte("// changed\n")...))
	legacyManifest := legacyPlan.Manifest()
	legacyManifest.Schema = 1
	legacyManifest.Target.Layout = ""
	writeManifest(
		t,
		filepath.Join(
			root,
			filepath.FromSlash(legacyPlan.Target().ManifestPath),
		),
		legacyManifest,
	)
	if err := os.Remove(filepath.Join(root, "app", "application.go")); err != nil {
		t.Fatal(err)
	}
	plan := renderMainPlan(
		t,
		root,
		"cmd/application/main.go",
		"./...",
		mainApplicationSource("application"),
	)
	_, err := Apply(plan)
	var conflict *ConflictError
	if !errors.As(err, &conflict) ||
		!hasDifference(
			Status{Differences: conflict.Differences},
			DifferenceManualEdit,
		) {
		t.Fatalf("Apply(modified legacy migration) error = %v", err)
	}
	if _, statErr := os.Stat(legacyPath); statErr != nil {
		t.Fatalf("modified legacy file was removed: %v", statErr)
	}
}

func TestApplyMigratesSchemaThreeAdjacentSourceShard(t *testing.T) {
	for _, test := range []struct {
		name     string
		modified bool
	}{
		{name: "unchanged"},
		{name: "modified", modified: true},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := generationModule(t)
			plan := renderPlan(t, root, applicationWithProviderSource)
			legacyContent := []byte(
				"//go:build !spice_generate\n\n" +
					generatedMarker + "\n\n" +
					"package app\n",
			)
			legacyPath := "app/application_application_spice_gen.go"
			for _, file := range plan.Files() {
				if file.Role == generate.FileRoleSourceUnit {
					continue
				}
				writeFile(
					t,
					filepath.Join(root, filepath.FromSlash(file.Path)),
					file.Content(),
				)
			}
			writeFile(
				t,
				filepath.Join(root, filepath.FromSlash(legacyPath)),
				legacyContent,
			)
			legacyManifest := plan.Manifest()
			legacyManifest.Schema = 3
			legacyManifest.Files = slices.DeleteFunc(
				legacyManifest.Files,
				func(file generate.ManifestFile) bool {
					return file.Role == generate.FileRoleSourceUnit
				},
			)
			legacyManifest.Files = append(
				legacyManifest.Files,
				generate.ManifestFile{
					Path:   legacyPath,
					SHA256: hashContent(legacyContent),
					Role:   generate.FileRole("source-shard"),
				},
			)
			slices.SortFunc(
				legacyManifest.Files,
				func(left, right generate.ManifestFile) int {
					return strings.Compare(left.Path, right.Path)
				},
			)
			writeManifest(
				t,
				filepath.Join(
					root,
					filepath.FromSlash(plan.Target().ManifestPath),
				),
				legacyManifest,
			)
			if test.modified {
				writeFile(
					t,
					filepath.Join(root, filepath.FromSlash(legacyPath)),
					append(legacyContent, []byte("// manual\n")...),
				)
			}

			result, err := Apply(plan)
			if test.modified {
				var conflict *ConflictError
				if !errors.As(err, &conflict) ||
					!hasDifference(
						Status{Differences: conflict.Differences},
						DifferenceManualEdit,
					) {
					t.Fatalf("Apply(modified schema-3 shard) error = %v", err)
				}
				if _, statErr := os.Stat(filepath.Join(
					root,
					filepath.FromSlash(legacyPath),
				)); statErr != nil {
					t.Fatalf("modified schema-3 shard was removed: %v", statErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("Apply(schema-3 shard) error = %v", err)
			}
			if !slices.Contains(result.Removed, legacyPath) {
				t.Fatalf("Apply(schema-3 shard).Removed = %v", result.Removed)
			}
			if _, statErr := os.Stat(filepath.Join(
				root,
				filepath.FromSlash(legacyPath),
			)); !errors.Is(statErr, fs.ErrNotExist) {
				t.Fatalf("unchanged schema-3 shard still exists: %v", statErr)
			}
		})
	}
}

func TestApplyMigratesSchemaFourMonolithicTarget(t *testing.T) {
	for _, test := range []struct {
		name     string
		modified bool
	}{
		{name: "unchanged"},
		{name: "modified", modified: true},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := generationModule(t)
			plan := renderPlan(t, root, applicationWithProviderSource)
			legacyContent := []byte(
				"//go:build !spice_generate\n\n" +
					generatedMarker + "\n\n" +
					"package spicegen\n",
			)
			legacyPath := path.Join(
				plan.Target().OutputDir,
				"zz_spice_gen.go",
			)
			legacyManifest := plan.Manifest()
			legacyManifest.Schema = 4
			legacyManifest.Files = slices.DeleteFunc(
				legacyManifest.Files,
				func(file generate.ManifestFile) bool {
					return file.Role != generate.FileRoleSourceUnit
				},
			)
			for _, file := range plan.Files() {
				if file.Role != generate.FileRoleSourceUnit {
					continue
				}
				writeFile(
					t,
					filepath.Join(root, filepath.FromSlash(file.Path)),
					file.Content(),
				)
			}
			writeFile(
				t,
				filepath.Join(root, filepath.FromSlash(legacyPath)),
				legacyContent,
			)
			legacyManifest.Files = append(
				legacyManifest.Files,
				generate.ManifestFile{
					Path:   legacyPath,
					SHA256: hashContent(legacyContent),
					Role:   generate.FileRoleTargetOrchestrator,
				},
			)
			slices.SortFunc(
				legacyManifest.Files,
				func(left, right generate.ManifestFile) int {
					return strings.Compare(left.Path, right.Path)
				},
			)
			writeManifest(
				t,
				filepath.Join(
					root,
					filepath.FromSlash(plan.Target().ManifestPath),
				),
				legacyManifest,
			)
			if test.modified {
				writeFile(
					t,
					filepath.Join(root, filepath.FromSlash(legacyPath)),
					append(legacyContent, []byte("// manual\n")...),
				)
			}

			result, err := Apply(plan)
			if test.modified {
				var conflict *ConflictError
				if !errors.As(err, &conflict) ||
					!hasDifference(
						Status{Differences: conflict.Differences},
						DifferenceManualEdit,
					) {
					t.Fatalf(
						"Apply(modified schema-4 target) error = %v",
						err,
					)
				}
				return
			}
			if err != nil {
				t.Fatalf("Apply(schema-4 target) error = %v", err)
			}
			if !slices.Contains(result.Removed, legacyPath) {
				t.Fatalf(
					"Apply(schema-4 target).Removed = %v",
					result.Removed,
				)
			}
			if _, statErr := os.Stat(filepath.Join(
				root,
				filepath.FromSlash(legacyPath),
			)); !errors.Is(statErr, fs.ErrNotExist) {
				t.Fatalf(
					"unchanged schema-4 target still exists: %v",
					statErr,
				)
			}
		})
	}
}

func TestApplyOwnsGeneratedOpenAPI(t *testing.T) {
	root := generationModule(t)
	plan := renderPlan(t, root, controllerApplicationSource)
	paths := generatedPaths(plan)
	for _, required := range []string{
		"internal/spicegen/application/artifacts/openapi.json",
		"internal/spicegen/application/sources/app/application_spice_gen.go",
		"internal/spicegen/application/spice_assembly_gen.go",
		"internal/spicegen/application/spice_http_gen.go",
	} {
		if !slices.Contains(paths, required) {
			t.Fatalf("generated files = %v, missing %s", paths, required)
		}
	}
	result, err := Apply(plan)
	if err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	if !slices.Equal(result.Written, generatedPaths(plan)) {
		t.Fatalf("Apply().Written = %v", result.Written)
	}
	openAPIPath := filepath.Join(root, filepath.FromSlash(plan.Files()[0].Path))
	content := mustRead(t, openAPIPath)
	if !json.Valid(content) || !strings.Contains(string(content), `"openapi": "3.1.0"`) {
		t.Fatalf("generated OpenAPI = %s", content)
	}
	writeFile(t, openAPIPath, append(content, ' '))
	status, err := Check(plan)
	if err != nil || !hasDifference(status, DifferenceManualEdit) {
		t.Fatalf("Check(manual OpenAPI edit) = %#v, %v", status, err)
	}
	if _, err := Apply(plan); err == nil {
		t.Fatal("Apply(manual OpenAPI edit) error = nil")
	}
}

func TestValidateGeneratedContentFormats(t *testing.T) {
	tests := []struct {
		name    string
		path    string
		content string
		wantErr bool
	}{
		{name: "Go", path: "generated.go", content: generatedMarker + "\npackage generated\n"},
		{name: "JSON", path: "generated.json", content: "{}\n"},
		{name: "missing JSON newline", path: "generated.json", content: "{}", wantErr: true},
		{name: "invalid JSON", path: "generated.json", content: "{]\n", wantErr: true},
		{name: "unsupported", path: "generated.yaml", content: "{}\n", wantErr: true},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			err := validateGeneratedContent(test.path, []byte(test.content))
			if (err != nil) != test.wantErr {
				t.Fatalf("validateGeneratedContent() error = %v, wantErr=%t", err, test.wantErr)
			}
		})
	}
}

func TestApplyUpdatesOnlyUnmodifiedOwnedOutput(t *testing.T) {
	root := generationModule(t)
	first := renderPlan(t, root, applicationSource)
	if _, err := Apply(first); err != nil {
		t.Fatalf("Apply(first) error = %v", err)
	}

	second := renderPlan(t, root, applicationWithProviderSource)
	status, err := Check(second)
	if err != nil {
		t.Fatalf("Check(second) error = %v", err)
	}
	if !hasDifference(status, DifferenceStaleFile) ||
		!hasDifference(status, DifferenceStaleManifest) {
		t.Fatalf("Check(second) = %#v", status)
	}
	result, err := Apply(second)
	if err != nil {
		t.Fatalf("Apply(second) error = %v", err)
	}
	if !result.Changed() ||
		!slices.Equal(result.Written, []string{
			"internal/spicegen/application/sources/app/application_spice_gen.go",
			"internal/spicegen/application/spice_assembly_gen.go",
			"internal/spicegen/application/spice_contracts_gen.go",
			"internal/spicegen/application/spice_providers_gen.go",
		}) ||
		!result.ManifestUpdated {
		t.Fatalf("Apply(second) = %#v", result)
	}
	status, err = Check(second)
	if err != nil || !status.Current {
		t.Fatalf("updated Check() = %#v, %v", status, err)
	}
	content := mustRead(t, filepath.Join(root, filepath.FromSlash(second.Files()[0].Path)))
	if !strings.Contains(string(content), "app.ValueProvider()") {
		t.Fatalf("updated generated source missing provider call:\n%s", content)
	}
}

func TestApplyRefusesManualEditsAndPreservesThem(t *testing.T) {
	root := generationModule(t)
	plan := renderPlan(t, root, applicationSource)
	if _, err := Apply(plan); err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	generatedPath := filepath.Join(root, filepath.FromSlash(plan.Files()[0].Path))
	edited := append(mustRead(t, generatedPath), []byte("\n// manual work\n")...)
	if err := os.WriteFile(generatedPath, edited, 0o600); err != nil {
		t.Fatal(err)
	}

	status, err := Check(plan)
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if !hasDifference(status, DifferenceManualEdit) {
		t.Fatalf("Check() = %#v", status)
	}
	_, err = Apply(plan)
	var conflict *ConflictError
	if !errors.As(err, &conflict) ||
		len(conflict.Differences) != 1 ||
		conflict.Differences[0].Kind != DifferenceManualEdit {
		t.Fatalf("Apply() error = %#v", err)
	}
	if got := mustRead(t, generatedPath); !bytesEqual(got, edited) {
		t.Fatal("Apply changed manually edited generated file")
	}
}

func TestApplyRefusesUnownedCollisionEvenWhenBytesMatch(t *testing.T) {
	root := generationModule(t)
	plan := renderPlan(t, root, applicationSource)
	generatedPath := filepath.Join(root, filepath.FromSlash(plan.Files()[0].Path))
	writeFile(t, generatedPath, plan.Files()[0].Content())

	status, err := Check(plan)
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if !hasDifference(status, DifferenceUnownedCollision) {
		t.Fatalf("Check() = %#v", status)
	}
	if _, err := Apply(plan); err == nil {
		t.Fatal("Apply() error = nil for unowned collision")
	}
	if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(plan.Target().ManifestPath))); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("manifest was written for unowned collision: %v", err)
	}
}

func TestApplyRemovesOnlyUnmodifiedStaleOwnedFiles(t *testing.T) {
	root := generationModule(t)
	plan := renderPlan(t, root, applicationSource)
	if _, err := Apply(plan); err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	stalePath := "internal/spicegen/application/old_spice_gen.go"
	staleContent := []byte(generatedMarker + "\n\npackage spicegen\n")
	writeFile(t, filepath.Join(root, filepath.FromSlash(stalePath)), staleContent)
	addManifestFile(t, root, plan, generate.ManifestFile{
		Path:   stalePath,
		SHA256: hashContent(staleContent),
	})

	status, err := Check(plan)
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if !hasDifference(status, DifferenceStaleOwnedFile) {
		t.Fatalf("Check() = %#v", status)
	}
	result, err := Apply(plan)
	if err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	if !slices.Equal(result.Removed, []string{stalePath}) {
		t.Fatalf("Apply().Removed = %v", result.Removed)
	}
	if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(stalePath))); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("stale file still exists: %v", err)
	}

	changedPath := "internal/spicegen/application/changed_spice_gen.go"
	writeFile(t, filepath.Join(root, filepath.FromSlash(changedPath)), staleContent)
	addManifestFile(t, root, plan, generate.ManifestFile{
		Path:   changedPath,
		SHA256: hashContent(staleContent),
	})
	changed := append([]byte(nil), staleContent...)
	changed = append(changed, []byte("// manual\n")...)
	writeFile(t, filepath.Join(root, filepath.FromSlash(changedPath)), changed)
	if _, err := Apply(plan); err == nil {
		t.Fatal("Apply() removed manually changed stale file")
	}
	if got := mustRead(t, filepath.Join(root, filepath.FromSlash(changedPath))); !bytesEqual(got, changed) {
		t.Fatal("changed stale file was not preserved")
	}
}

func TestApplyRejectsUnexpectedGeneratedFilesAndLocks(t *testing.T) {
	root := generationModule(t)
	plan := renderPlan(t, root, applicationSource)
	if _, err := Apply(plan); err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	extraPath := filepath.Join(root, "internal", "spicegen", "application", "extra.go")
	writeFile(t, extraPath, []byte(generatedMarker+"\n\npackage spicegen\n"))
	status, err := Check(plan)
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if !hasDifference(status, DifferenceUnexpectedGenerated) {
		t.Fatalf("Check() = %#v", status)
	}
	if _, err := Apply(plan); err == nil {
		t.Fatal("Apply() error = nil for unexpected generated file")
	}
	if err := os.Remove(extraPath); err != nil {
		t.Fatal(err)
	}

	lockPath := filepath.Join(root, ".spice", "application.lock")
	writeFile(t, lockPath, []byte("active"))
	if _, err := Apply(plan); err == nil || !strings.Contains(err.Error(), "is locked") {
		t.Fatalf("Apply(locked) error = %v", err)
	}
	if got := string(mustRead(t, lockPath)); got != "active" {
		t.Fatalf("existing lock changed to %q", got)
	}
}

func TestCheckRejectsUnsafeAndInvalidManifestState(t *testing.T) {
	root := generationModule(t)
	plan := renderPlan(t, root, applicationSource)
	manifestPath := filepath.Join(root, filepath.FromSlash(plan.Target().ManifestPath))
	writeFile(t, manifestPath, []byte("{not-json}\n"))
	if _, err := Check(plan); err == nil || !strings.Contains(err.Error(), "decode ownership manifest") {
		t.Fatalf("Check(malformed manifest) error = %v", err)
	}

	manifest := plan.Manifest()
	manifest.Schema++
	writeManifest(t, manifestPath, manifest)
	if _, err := Check(plan); err == nil || !strings.Contains(err.Error(), "schema") {
		t.Fatalf("Check(unsupported schema) error = %v", err)
	}

	manifest = plan.Manifest()
	manifest.Target.ID = "different"
	writeManifest(t, manifestPath, manifest)
	if _, err := Check(plan); err == nil || !strings.Contains(err.Error(), "target does not match") {
		t.Fatalf("Check(target mismatch) error = %v", err)
	}

	manifest = plan.Manifest()
	manifest.Files = append(manifest.Files, generate.ManifestFile{
		Path:   "../outside.go",
		SHA256: hashContent([]byte("outside")),
	})
	writeManifest(t, manifestPath, manifest)
	if _, err := Check(plan); err == nil || !strings.Contains(err.Error(), "ownership manifest path") {
		t.Fatalf("Check(unsafe manifest path) error = %v", err)
	}

	manifest = plan.Manifest()
	manifest.Files[0].SHA256 = "sha256:invalid"
	writeManifest(t, manifestPath, manifest)
	if _, err := Check(plan); err == nil || !strings.Contains(err.Error(), "invalid SHA-256") {
		t.Fatalf("Check(invalid hash) error = %v", err)
	}

	manifest = plan.Manifest()
	manifest.Files = append(manifest.Files, manifest.Files[0])
	writeManifest(t, manifestPath, manifest)
	if _, err := Check(plan); err == nil || !strings.Contains(err.Error(), "duplicate path") {
		t.Fatalf("Check(duplicate path) error = %v", err)
	}
}

func TestCheckRejectsSymlinkedOutput(t *testing.T) {
	root := generationModule(t)
	plan := renderPlan(t, root, applicationSource)
	output := filepath.Join(root, filepath.FromSlash(plan.Target().OutputDir))
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		t.Fatal(err)
	}
	outside := t.TempDir()
	if err := os.Symlink(outside, output); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if _, err := Check(plan); err == nil || !strings.Contains(err.Error(), "symbolic link") {
		t.Fatalf("Check(symlink) error = %v", err)
	}
}

func TestPathAndDiffHelpers(t *testing.T) {
	t.Parallel()
	for _, invalid := range []string{
		"",
		".",
		"../escape",
		"/absolute",
		`back\slash`,
		"dir/../escape",
		"CON/file.go",
		"dir/com1.txt",
		"dir/NUL",
	} {
		if err := validateRelativePath(invalid); err == nil {
			t.Errorf("validateRelativePath(%q) error = nil", invalid)
		}
	}
	for _, valid := range []string{
		"internal/spicegen/app",
		".spice/app.manifest.json",
		"dir/compile.go",
	} {
		if err := validateRelativePath(valid); err != nil {
			t.Errorf("validateRelativePath(%q) error = %v", valid, err)
		}
	}
	if !reservedWindowsName("LPT9.txt") || reservedWindowsName("LPT10.txt") {
		t.Fatal("reservedWindowsName did not enforce the portable device range")
	}
	if validHash("sha256:short") || !validHash(hashContent([]byte("valid"))) {
		t.Fatal("validHash returned an unexpected result")
	}

	var builder strings.Builder
	lines := appendDiff(&builder, "file.go", []byte("old\n"), []byte("new\n"), 20)
	if lines != 5 ||
		!strings.Contains(builder.String(), "-old") ||
		!strings.Contains(builder.String(), "+new") {
		t.Fatalf("appendDiff() = %d, %q", lines, builder.String())
	}
	if lines := splitLines(nil); lines != nil {
		t.Fatalf("splitLines(nil) = %#v", lines)
	}
}

func TestInvalidPlanAndConflictErrors(t *testing.T) {
	t.Parallel()
	if _, err := Check(generate.Plan{}); err == nil {
		t.Fatal("Check(zero plan) error = nil")
	}
	if _, err := Apply(generate.Plan{}); err == nil {
		t.Fatal("Apply(zero plan) error = nil")
	}
	if _, err := Diff(generate.Plan{}); err == nil {
		t.Fatal("Diff(zero plan) error = nil")
	}
	conflict := (*ConflictError)(nil)
	if conflict.Error() == "" {
		t.Fatal("nil ConflictError has empty message")
	}
	conflict = &ConflictError{Differences: []Difference{{
		Path:    "generated.go",
		Message: "manual edit",
	}}}
	if !strings.Contains(conflict.Error(), "generated.go: manual edit") {
		t.Fatalf("ConflictError.Error() = %q", conflict.Error())
	}
	result := Result{}
	if result.Changed() {
		t.Fatal("zero Result reports changes")
	}
	status := Status{Differences: []Difference{{Path: "file"}}}
	cloned := cloneStatus(status)
	cloned.Differences[0].Path = "changed"
	if status.Differences[0].Path == "changed" {
		t.Fatal("cloneStatus returned mutable difference storage")
	}
}

func TestPlanValidationBranches(t *testing.T) {
	root := generationModule(t)
	plan := renderPlan(t, root, applicationSource)
	if err := validatePlan(plan); err != nil {
		t.Fatalf("validatePlan() error = %v", err)
	}
	target := plan.Target()
	manifest := plan.Manifest()

	invalidTarget := target
	invalidTarget.OutputDir = ""
	if err := validatePlanTarget(invalidTarget); err == nil {
		t.Fatal("validatePlanTarget(empty output) error = nil")
	}
	invalidTarget = target
	invalidTarget.ManifestPath = ""
	if err := validatePlanTarget(invalidTarget); err == nil {
		t.Fatal("validatePlanTarget(empty manifest) error = nil")
	}
	invalidTarget = target
	invalidTarget.ManifestPath = target.OutputDir + "/manifest.json"
	if err := validatePlanTarget(invalidTarget); err == nil {
		t.Fatal("validatePlanTarget(nested manifest) error = nil")
	}

	invalidManifest := manifest
	invalidManifest.Schema++
	if err := validatePlanManifest(target, invalidManifest); err == nil {
		t.Fatal("validatePlanManifest(schema) error = nil")
	}
	invalidManifest = manifest
	invalidManifest.Target.ID = "different"
	if err := validatePlanManifest(target, invalidManifest); err == nil {
		t.Fatal("validatePlanManifest(target) error = nil")
	}

	invalidManifest = manifest
	invalidManifest.Files = nil
	if err := validatePlanFiles(plan, target, invalidManifest); err == nil {
		t.Fatal("validatePlanFiles(count) error = nil")
	}
	invalidManifest = manifest
	invalidManifest.Files[0].Path = "different.go"
	if err := validatePlanFiles(plan, target, invalidManifest); err == nil {
		t.Fatal("validatePlanFiles(order) error = nil")
	}
	manifest = plan.Manifest()
	collidingTarget := target
	collidingTarget.ManifestPath = plan.Files()[0].Path
	if err := validatePlanFiles(plan, collidingTarget, manifest); err == nil {
		t.Fatal("validatePlanFiles(manifest collision) error = nil")
	}
}

func TestApplyDropsAlreadyMissingOwnedFileAndIgnoresHandwrittenExtras(t *testing.T) {
	root := generationModule(t)
	plan := renderPlan(t, root, applicationSource)
	if _, err := Apply(plan); err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	missingPath := "internal/spicegen/application/missing_spice_gen.go"
	addManifestFile(t, root, plan, generate.ManifestFile{
		Path:   missingPath,
		SHA256: hashContent([]byte(generatedMarker + "\n")),
	})
	handwrittenPath := filepath.Join(root, "internal", "spicegen", "application", "notes.go")
	writeFile(t, handwrittenPath, []byte("package spicegen\n"))

	status, err := Check(plan)
	if err != nil {
		t.Fatalf("Check() error = %v", err)
	}
	if !hasDifference(status, DifferenceMissingOwnedFile) ||
		hasDifference(status, DifferenceUnexpectedGenerated) {
		t.Fatalf("Check() = %#v", status)
	}
	result, err := Apply(plan)
	if err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	if len(result.Removed) != 0 || !result.ManifestUpdated {
		t.Fatalf("Apply() = %#v", result)
	}
	if got := string(mustRead(t, handwrittenPath)); got != "package spicegen\n" {
		t.Fatalf("handwritten extra changed to %q", got)
	}
}

func TestRootedFilesystemHelpersRejectNonFiles(t *testing.T) {
	rootPath := t.TempDir()
	root, err := os.OpenRoot(rootPath)
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		if err := root.Close(); err != nil {
			t.Errorf("root.Close() error = %v", err)
		}
	}()
	if err := root.Mkdir("directory", 0o755); err != nil {
		t.Fatal(err)
	}
	if _, _, err := readOptional(root, "directory"); err == nil || !strings.Contains(err.Error(), "not a regular file") {
		t.Fatalf("readOptional(directory) error = %v", err)
	}
	if err := ensureDirectories(root, "directory/child"); err != nil {
		t.Fatalf("ensureDirectories() error = %v", err)
	}
	if err := root.WriteFile("file", []byte("value"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := ensureDirectories(root, "file/child"); err == nil || !strings.Contains(err.Error(), "not a directory") {
		t.Fatalf("ensureDirectories(file) error = %v", err)
	}
	if err := removeOwnedFile(root, "missing.go", hashContent(nil)); err != nil {
		t.Fatalf("removeOwnedFile(missing) error = %v", err)
	}
	if err := root.WriteFile("changed.go", []byte(generatedMarker+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := removeOwnedFile(root, "changed.go", hashContent([]byte("different"))); err == nil {
		t.Fatal("removeOwnedFile(changed) error = nil")
	}
}

const applicationSource = `package app

// @Application
func Application() {}
`

const applicationWithProviderSource = `package app

type Value struct{}

// @Bean
func ValueProvider() Value { return Value{} }

// @Application
func Application(Value) {}
`

const controllerApplicationSource = `package app

import "context"

type Request struct {
	ID string ` + "`path:\"id\"`" + `
}

type Response struct {
	ID string ` + "`json:\"id\"`" + `
}

// @Controller(prefix="/items")
type API struct{}

// @Bean
func NewAPI() *API { return &API{} }

// @Get("/{id}")
func (*API) Get(context.Context, Request) (Response, error) {
	return Response{}, nil
}

// @Application
func Application(*API) {}
`

func generationModule(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	repository, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	goMod := "module example.com/genfs\n\ngo 1.26.0\n\n" +
		"require github.com/spice-framework/spice v0.0.0\n\n" +
		"replace github.com/spice-framework/spice => " + filepath.ToSlash(repository) + "\n"
	writeFile(t, filepath.Join(root, "go.mod"), []byte(goMod))
	return root
}

func mainApplicationSource(targetID string) []byte {
	return []byte(
		"package main\n\n" +
			"import (\n" +
			"\t\"os\"\n\n" +
			"\tspiceapp \"example.com/genfs/internal/spicegen/" +
			targetID + "\"\n" +
			")\n\n" +
			"// @Application\n" +
			"func main() {\n" +
			"\tos.Exit(spiceapp.Main(os.Args[1:]))\n" +
			"}\n",
	)
}

func renderPlan(t *testing.T, root, source string) generate.Plan {
	t.Helper()
	writeFile(t, filepath.Join(root, "app", "application.go"), []byte(source))
	program, err := load.Load(context.Background(), load.Options{Dir: root}, "./app")
	if err != nil {
		t.Fatalf("load.Load() error = %v", err)
	}
	resolution := resolve.Annotations(program)
	if len(resolution.Diagnostics) != 0 {
		t.Fatalf("resolve.Annotations() diagnostics = %v", resolution.Diagnostics)
	}
	resolution, err = testannotation.AttachOfficial(resolution)
	if err != nil {
		t.Fatalf("AttachOfficial() error = %v", err)
	}
	model := application.Build(program, resolution)
	if diagnostics := model.Diagnostics(); len(diagnostics) != 0 {
		t.Fatalf("application.Build() diagnostics = %v", diagnostics)
	}
	targets := model.Targets()
	if len(targets) != 1 {
		t.Fatalf("Targets() = %#v", targets)
	}
	target, diagnostics := generate.DefaultTarget(program, targets[0])
	if len(diagnostics) != 0 {
		t.Fatalf("generate.DefaultTarget() diagnostics = %v", diagnostics)
	}
	plan, diagnostics := generate.Render(program, model, targets[0], target)
	if len(diagnostics) != 0 {
		t.Fatalf("generate.Render() diagnostics = %v", diagnostics)
	}
	return plan
}

func renderMainPlan(
	t *testing.T,
	root string,
	sourcePath string,
	pattern string,
	source []byte,
) generate.Plan {
	t.Helper()
	writeFile(
		t,
		filepath.Join(root, filepath.FromSlash(sourcePath)),
		source,
	)
	program, err := load.Load(context.Background(), load.Options{
		Dir:                                    root,
		BuildFlags:                             []string{"-tags=" + generate.AnalysisBuildTag},
		PrepareGeneratedApplicationEntrypoints: true,
	}, pattern)
	if err != nil {
		t.Fatalf("load.Load() error = %v", err)
	}
	resolution := resolve.Annotations(program)
	if len(resolution.Diagnostics) != 0 {
		t.Fatalf(
			"resolve.Annotations() diagnostics = %v",
			resolution.Diagnostics,
		)
	}
	resolution, err = testannotation.AttachOfficial(resolution)
	if err != nil {
		t.Fatalf("AttachOfficial() error = %v", err)
	}
	model := application.Build(program, resolution)
	if diagnostics := model.Diagnostics(); len(diagnostics) != 0 {
		t.Fatalf("application.Build() diagnostics = %v", diagnostics)
	}
	targets := model.Targets()
	if len(targets) != 1 {
		t.Fatalf("Targets() = %#v", targets)
	}
	target, diagnostics := generate.DefaultTarget(program, targets[0])
	if len(diagnostics) != 0 {
		t.Fatalf("generate.DefaultTarget() diagnostics = %v", diagnostics)
	}
	plan, diagnostics := generate.Render(program, model, targets[0], target)
	if len(diagnostics) != 0 {
		t.Fatalf("generate.Render() diagnostics = %v", diagnostics)
	}
	return plan
}

func generatedPaths(plan generate.Plan) []string {
	files := plan.Files()
	result := make([]string, len(files))
	for index, file := range files {
		result[index] = file.Path
	}
	return result
}

func addManifestFile(t *testing.T, root string, plan generate.Plan, file generate.ManifestFile) {
	t.Helper()
	manifestPath := filepath.Join(root, filepath.FromSlash(plan.Target().ManifestPath))
	content := mustRead(t, manifestPath)
	var manifest generate.Manifest
	if err := json.Unmarshal(content, &manifest); err != nil {
		t.Fatal(err)
	}
	manifest.Files = append(manifest.Files, file)
	writeManifest(t, manifestPath, manifest)
}

func writeManifest(t *testing.T, filePath string, manifest generate.Manifest) {
	t.Helper()
	content, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, filePath, append(content, '\n'))
}

func hasDifference(status Status, kind DifferenceKind) bool {
	for _, difference := range status.Differences {
		if difference.Kind == kind {
			return true
		}
	}
	return false
}

func mustStat(t *testing.T, filePath string) fs.FileInfo {
	t.Helper()
	info, err := os.Stat(filePath)
	if err != nil {
		t.Fatal(err)
	}
	return info
}

func mustRead(t *testing.T, filePath string) []byte {
	t.Helper()
	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatal(err)
	}
	return content
}

func writeFile(t *testing.T, filePath string, content []byte) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(filePath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filePath, content, 0o600); err != nil {
		t.Fatal(err)
	}
}

func bytesEqual(left, right []byte) bool {
	return slices.Equal(left, right)
}
