//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	time "time"

	spicebean "github.com/StevenBuglione/spice/bean"
	spiceconfig "github.com/StevenBuglione/spice/config"
	cli "github.com/StevenBuglione/spice/internal/cli"
	spiceentrypoint "github.com/StevenBuglione/spice/internal/spicegen/spice/sources/internal_/spiceapp"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

const TargetID = spiceentrypoint.ApplicationTargetSpice_b77b32e5

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// Command is bean "command".
	Command *cli.Command
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// Command replaces bean "command".
	Command spicebean.Override[*cli.Command]
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Observers                 []spicelifecycle.Observer
}
