//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	fmt "fmt"
	strings "strings"
	time "time"

	spicebean "github.com/StevenBuglione/spice/bean"
	spiceconfig "github.com/StevenBuglione/spice/config"
	cli "github.com/StevenBuglione/spice/internal/cli"
	spiceentrypoint "github.com/StevenBuglione/spice/internal/spicegen/spice/sources/internal_/spiceapp"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

const TargetID = spiceentrypoint.ApplicationTargetSpice_b77b32e5

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// Runtime is bean "runtime".
	Runtime *cli.Runtime
	// DevHandler is bean "devHandler".
	DevHandler cli.Handler
	// LspHandler is bean "lspHandler".
	LspHandler cli.Handler
	// RunHandler is bean "runHandler".
	RunHandler cli.Handler
	// HelpHandler is bean "helpHandler".
	HelpHandler cli.Handler
	// TestHandler is bean "testHandler".
	TestHandler cli.Handler
	// BeansHandler is bean "beansHandler".
	BeansHandler cli.Handler
	// BuildHandler is bean "buildHandler".
	BuildHandler cli.Handler
	// VerifyHandler is bean "verifyHandler".
	VerifyHandler cli.Handler
	// ModulesHandler is bean "modulesHandler".
	ModulesHandler cli.Handler
	// VersionHandler is bean "versionHandler".
	VersionHandler cli.Handler
	// GenerateHandler is bean "generateHandler".
	GenerateHandler cli.Handler
	// GeneratedHandler is bean "generatedHandler".
	GeneratedHandler cli.Handler
	// AnnotationsHandler is bean "annotationsHandler".
	AnnotationsHandler cli.Handler
	// Command is bean "command".
	Command *cli.Command
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// Runtime replaces bean "runtime".
	Runtime spicebean.Override[*cli.Runtime]
	// DevHandler replaces bean "devHandler".
	DevHandler spicebean.Override[cli.Handler]
	// LspHandler replaces bean "lspHandler".
	LspHandler spicebean.Override[cli.Handler]
	// RunHandler replaces bean "runHandler".
	RunHandler spicebean.Override[cli.Handler]
	// HelpHandler replaces bean "helpHandler".
	HelpHandler spicebean.Override[cli.Handler]
	// TestHandler replaces bean "testHandler".
	TestHandler spicebean.Override[cli.Handler]
	// BeansHandler replaces bean "beansHandler".
	BeansHandler spicebean.Override[cli.Handler]
	// BuildHandler replaces bean "buildHandler".
	BuildHandler spicebean.Override[cli.Handler]
	// VerifyHandler replaces bean "verifyHandler".
	VerifyHandler spicebean.Override[cli.Handler]
	// ModulesHandler replaces bean "modulesHandler".
	ModulesHandler spicebean.Override[cli.Handler]
	// VersionHandler replaces bean "versionHandler".
	VersionHandler spicebean.Override[cli.Handler]
	// GenerateHandler replaces bean "generateHandler".
	GenerateHandler spicebean.Override[cli.Handler]
	// GeneratedHandler replaces bean "generatedHandler".
	GeneratedHandler spicebean.Override[cli.Handler]
	// AnnotationsHandler replaces bean "annotationsHandler".
	AnnotationsHandler spicebean.Override[cli.Handler]
	// Command replaces bean "command".
	Command spicebean.Override[*cli.Command]
}

// BeanOverrideLayer is one named immutable override composition layer.
// Layers are applied in order; a later layer deliberately replaces an earlier value.
type BeanOverrideLayer struct {
	Name      string
	Overrides BeanOverrides
}

// ComposeBeanOverrides validates and deterministically composes named layers.
// It never mutates a running application or performs runtime bean lookup.
func ComposeBeanOverrides(layers ...BeanOverrideLayer) (BeanOverrides, error) {
	result := BeanOverrides{}
	seen := make(map[string]int, len(layers))
	for index, layer := range layers {
		if layer.Name == "" || strings.TrimSpace(layer.Name) != layer.Name {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %d requires a non-empty name without surrounding whitespace", index)
		}
		if previous, duplicate := seen[layer.Name]; duplicate {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %q repeats layer %d", layer.Name, previous)
		}
		seen[layer.Name] = index
		if layer.Overrides.Runtime.Enabled() {
			result.Runtime = layer.Overrides.Runtime
		}
		if layer.Overrides.DevHandler.Enabled() {
			result.DevHandler = layer.Overrides.DevHandler
		}
		if layer.Overrides.LspHandler.Enabled() {
			result.LspHandler = layer.Overrides.LspHandler
		}
		if layer.Overrides.RunHandler.Enabled() {
			result.RunHandler = layer.Overrides.RunHandler
		}
		if layer.Overrides.HelpHandler.Enabled() {
			result.HelpHandler = layer.Overrides.HelpHandler
		}
		if layer.Overrides.TestHandler.Enabled() {
			result.TestHandler = layer.Overrides.TestHandler
		}
		if layer.Overrides.BeansHandler.Enabled() {
			result.BeansHandler = layer.Overrides.BeansHandler
		}
		if layer.Overrides.BuildHandler.Enabled() {
			result.BuildHandler = layer.Overrides.BuildHandler
		}
		if layer.Overrides.VerifyHandler.Enabled() {
			result.VerifyHandler = layer.Overrides.VerifyHandler
		}
		if layer.Overrides.ModulesHandler.Enabled() {
			result.ModulesHandler = layer.Overrides.ModulesHandler
		}
		if layer.Overrides.VersionHandler.Enabled() {
			result.VersionHandler = layer.Overrides.VersionHandler
		}
		if layer.Overrides.GenerateHandler.Enabled() {
			result.GenerateHandler = layer.Overrides.GenerateHandler
		}
		if layer.Overrides.GeneratedHandler.Enabled() {
			result.GeneratedHandler = layer.Overrides.GeneratedHandler
		}
		if layer.Overrides.AnnotationsHandler.Enabled() {
			result.AnnotationsHandler = layer.Overrides.AnnotationsHandler
		}
		if layer.Overrides.Command.Enabled() {
			result.Command = layer.Overrides.Command
		}
	}
	return result, nil
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Observers                 []spicelifecycle.Observer
}
