//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/autoconfigure/autoconfigure.go:11

package spicegen

import (
	autoconfigure "github.com/StevenBuglione/spice/internal/autoconfigure"
	cli "github.com/StevenBuglione/spice/internal/cli"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructCommand_ea2da0e1 performs the direct construction selected for bean "command".
// Spice source identity: spice:symbol:v1|function|54:github.com/StevenBuglione/spice/internal/autoconfigure|0:|14:DefaultCommand.
func ConstructCommand_ea2da0e1() (*cli.Command, spicelifecycle.Cleanup, error) {
	value := autoconfigure.DefaultCommand()
	return value, nil, nil
}
