//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/autoconfigure/generate_handler.go:6

package spicegen

import (
	fmt "fmt"

	autoconfigure "github.com/spice-framework/spice/internal/autoconfigure"
	cli "github.com/spice-framework/spice/internal/cli"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructGenerateHandler_5c36cbc4 performs the direct construction selected for bean "generateHandler".
// Spice source identity: spice:symbol:v1|function|55:github.com/spice-framework/spice/internal/autoconfigure|0:|22:DefaultGenerateHandler.
func ConstructGenerateHandler_5c36cbc4(dependency0 *cli.Runtime) (cli.Handler, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultGenerateHandler(dependency0)
	if err != nil {
		var zero cli.Handler
		return zero, nil, fmt.Errorf("construct bean generateHandler (github.com/spice-framework/spice/internal/cli.Handler, source spice:symbol:v1|function|55:github.com/spice-framework/spice/internal/autoconfigure|0:|22:DefaultGenerateHandler): %w", err)
	}
	return value, nil, nil
}
