//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/autoconfigure/help_handler.go:6

package spicegen

import (
	fmt "fmt"

	autoconfigure "github.com/spice-framework/spice/internal/autoconfigure"
	cli "github.com/spice-framework/spice/internal/cli"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructHelpHandler_05b3fad6 performs the direct construction selected for bean "helpHandler".
// Spice source identity: spice:symbol:v1|function|55:github.com/spice-framework/spice/internal/autoconfigure|0:|18:DefaultHelpHandler.
func ConstructHelpHandler_05b3fad6(dependency0 *cli.Runtime) (cli.Handler, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultHelpHandler(dependency0)
	if err != nil {
		var zero cli.Handler
		return zero, nil, fmt.Errorf("construct bean helpHandler (github.com/spice-framework/spice/internal/cli.Handler, source spice:symbol:v1|function|55:github.com/spice-framework/spice/internal/autoconfigure|0:|18:DefaultHelpHandler): %w", err)
	}
	return value, nil, nil
}
