//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/autoconfigure/runtime.go:6

package spicegen

import (
	autoconfigure "github.com/spice-framework/spice/internal/autoconfigure"
	cli "github.com/spice-framework/spice/internal/cli"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRuntime_f87f17cd performs the direct construction selected for bean "runtime".
// Spice source identity: spice:symbol:v1|function|55:github.com/spice-framework/spice/internal/autoconfigure|0:|14:DefaultRuntime.
func ConstructRuntime_f87f17cd() (*cli.Runtime, spicelifecycle.Cleanup, error) {
	value := autoconfigure.DefaultRuntime()
	return value, nil, nil
}
