//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/autoconfigure/runtime.go:6

package spicegen

import (
	autoconfigure "github.com/StevenBuglione/spice/internal/autoconfigure"
	cli "github.com/StevenBuglione/spice/internal/cli"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructRuntime_db45b3f3 performs the direct construction selected for bean "runtime".
// Spice source identity: spice:symbol:v1|function|54:github.com/StevenBuglione/spice/internal/autoconfigure|0:|14:DefaultRuntime.
func ConstructRuntime_db45b3f3() (*cli.Runtime, spicelifecycle.Cleanup, error) {
	value := autoconfigure.DefaultRuntime()
	return value, nil, nil
}
