//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/autoconfigure/test_handler.go:6

package spicegen

import (
	fmt "fmt"

	autoconfigure "github.com/spice-framework/spice/internal/autoconfigure"
	cli "github.com/spice-framework/spice/internal/cli"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTestHandler_7c79fc53 performs the direct construction selected for bean "testHandler".
// Spice source identity: spice:symbol:v1|function|55:github.com/spice-framework/spice/internal/autoconfigure|0:|18:DefaultTestHandler.
func ConstructTestHandler_7c79fc53(dependency0 *cli.Runtime) (cli.Handler, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultTestHandler(dependency0)
	if err != nil {
		var zero cli.Handler
		return zero, nil, fmt.Errorf("construct bean testHandler (github.com/spice-framework/spice/internal/cli.Handler, source spice:symbol:v1|function|55:github.com/spice-framework/spice/internal/autoconfigure|0:|18:DefaultTestHandler): %w", err)
	}
	return value, nil, nil
}
