//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/autoconfigure/verify_handler.go:6

package spicegen

import (
	fmt "fmt"

	autoconfigure "github.com/StevenBuglione/spice/internal/autoconfigure"
	cli "github.com/StevenBuglione/spice/internal/cli"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructVerifyHandler_b8cd6b5d performs the direct construction selected for bean "verifyHandler".
// Spice source identity: spice:symbol:v1|function|54:github.com/StevenBuglione/spice/internal/autoconfigure|0:|20:DefaultVerifyHandler.
func ConstructVerifyHandler_b8cd6b5d(dependency0 *cli.Runtime) (cli.Handler, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultVerifyHandler(dependency0)
	if err != nil {
		var zero cli.Handler
		return zero, nil, fmt.Errorf("construct bean verifyHandler (github.com/StevenBuglione/spice/internal/cli.Handler, source spice:symbol:v1|function|54:github.com/StevenBuglione/spice/internal/autoconfigure|0:|20:DefaultVerifyHandler): %w", err)
	}
	return value, nil, nil
}
