//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/spiceapp/application.go:17

package spicegen

// ApplicationTargetSpice_bb7121fb identifies the generated target selected by spice:symbol:v1|function|50:github.com/spice-framework/spice/internal/spiceapp|0:|5:Spice.
const ApplicationTargetSpice_bb7121fb = "spice"
