name: Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions: {}

jobs:
  release:
    name: Keylessly attest and publish
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: spice-framework/.github/.github/workflows/go-distribution-release.yml@8735307890ba974ff7d2d998ac805ff390ebacdf
    with:
      module: github.com/spice-framework/toolchain
      workflow_commit: 8735307890ba974ff7d2d998ac805ff390ebacdf
