name: Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions: {}

jobs:
  release:
    name: Keylessly attest and publish
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: spice-framework/.github/.github/workflows/go-distribution-release.yml@e0a93a898fe39d59a33cbb3013fcbb3732a25db5
    with:
      module: github.com/spice-framework/toolchain
      workflow_commit: e0a93a898fe39d59a33cbb3013fcbb3732a25db5
